<?php


/**
 * This class adds structure of 'EMT_LOCATION_UPDATE' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 03/07/12 22:24:33
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class LocationUpdateMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.LocationUpdateMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(LocationUpdatePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(LocationUpdatePeer::TABLE_NAME);
		$tMap->setPhpName('LocationUpdate');
		$tMap->setClassname('LocationUpdate');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('EMT_LOCATION_UPDATE_SEQ');

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 10);

		$tMap->addColumn('OBJECT_ID', 'ObjectId', 'INTEGER', false, 10);

		$tMap->addForeignKey('OBJECT_TYPE_ID', 'ObjectTypeId', 'INTEGER', 'EMT_PRIVACY_NODE_TYPE', 'ID', true, 3);

		$tMap->addColumn('COUNTRY', 'Country', 'VARCHAR', false, 5);

		$tMap->addForeignKey('STATE', 'State', 'INTEGER', 'EXT_GEONAME', 'GEONAME_ID', false, 7);

		$tMap->addForeignKey('CITY', 'City', 'INTEGER', 'EXT_GEONAME', 'GEONAME_ID', false, 7);

		$tMap->addColumn('DATE_FROM', 'DateFrom', 'TIMESTAMP', false, null);

		$tMap->addColumn('DATE_TO', 'DateTo', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // LocationUpdateMapBuilder
