<?php


/**
 * This class adds structure of 'EMT_POST_LOCATION' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/10/12 16:10:54
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PostLocationMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PostLocationMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PostLocationPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PostLocationPeer::TABLE_NAME);
		$tMap->setPhpName('PostLocation');
		$tMap->setClassname('PostLocation');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('EMT_POST_LOCATION_SEQ');

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 10);

		$tMap->addColumn('DATA', 'Data', 'CLOB', false, null);

		$tMap->addColumn('LATITUDE', 'Latitude', 'DECIMAL', false, 19);

		$tMap->addColumn('LONGITUDE', 'Longitude', 'DECIMAL', false, 19);

		$tMap->addColumn('COUNTRY', 'Country', 'VARCHAR', false, 5);

		$tMap->addForeignKey('STATE', 'State', 'INTEGER', 'EXT_GEONAME', 'GEONAME_ID', false, 7);

		$tMap->addForeignKey('CITY', 'City', 'INTEGER', 'EXT_GEONAME', 'GEONAME_ID', false, 7);

		$tMap->addColumn('MESSAGE', 'Message', 'VARCHAR', false, 1024);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // PostLocationMapBuilder
