<?php


/**
 * This class adds structure of 'EMT_PRIVACY_PREFERENCE' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 03/07/12 22:24:25
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PrivacyPreferenceMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PrivacyPreferenceMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PrivacyPreferencePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PrivacyPreferencePeer::TABLE_NAME);
		$tMap->setPhpName('PrivacyPreference');
		$tMap->setClassname('PrivacyPreference');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('EMT_PRIVACY_PREFERENCE_SEQ');

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 15);

		$tMap->addColumn('USER_ID', 'UserId', 'INTEGER', false, 10);

		$tMap->addColumn('SUBJECT_ID', 'SubjectId', 'INTEGER', false, 10);

		$tMap->addForeignKey('SUBJECT_TYPE_ID', 'SubjectTypeId', 'INTEGER', 'EMT_PRIVACY_NODE_TYPE', 'ID', true, 3);

		$tMap->addForeignKey('ROLE_ON_SUBJECT', 'RoleOnSubject', 'INTEGER', 'EMT_ROLE', 'ID', false, 4);

		$tMap->addColumn('OBJECT_ID', 'ObjectId', 'INTEGER', false, 10);

		$tMap->addForeignKey('OBJECT_TYPE_ID', 'ObjectTypeId', 'INTEGER', 'EMT_PRIVACY_NODE_TYPE', 'ID', true, 3);

		$tMap->addForeignKey('ROLE_ON_OBJECT', 'RoleOnObject', 'INTEGER', 'EMT_ROLE', 'ID', false, 4);

		$tMap->addForeignKey('ACTION_ID', 'ActionId', 'INTEGER', 'EMT_ACTION', 'ID', false, 5);

		$tMap->addColumn('ALLOWED', 'Allowed', 'TINYINT', true, 1);

	} // doBuild()

} // PrivacyPreferenceMapBuilder
