<?php


/**
 * This class adds structure of 'EMT_PUBLICATION_I18N' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 03/07/12 22:24:30
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PublicationI18nMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PublicationI18nMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PublicationI18nPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PublicationI18nPeer::TABLE_NAME);
		$tMap->setPhpName('PublicationI18n');
		$tMap->setClassname('PublicationI18n');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('ID', 'Id', 'INTEGER' , 'EMT_PUBLICATION', 'ID', true, 10);

		$tMap->addPrimaryKey('CULTURE', 'Culture', 'VARCHAR', true, 7);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', true, 255);

		$tMap->addColumn('STRIPPED_TITLE', 'StrippedTitle', 'VARCHAR', true, 255);

		$tMap->addColumn('SUMMARY', 'Summary', 'VARCHAR', false, 100);

		$tMap->addColumn('INTRODUCTION', 'Introduction', 'VARCHAR', true, 512);

		$tMap->addColumn('CONTENT', 'Content', 'CLOB', false, null);

		$tMap->addColumn('I18N_ACTIVE', 'I18nActive', 'BOOLEAN', false, 1);

		$tMap->addColumn('I18N_CREATED_AT', 'I18nCreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('I18N_UPDATED_AT', 'I18nUpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('SHORT_TITLE', 'ShortTitle', 'VARCHAR', false, 60);

	} // doBuild()

} // PublicationI18nMapBuilder
