<?php


/**
 * This class adds structure of 'EMT_ROLE' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/10/12 16:10:08
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class RoleMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RoleMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(RolePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(RolePeer::TABLE_NAME);
		$tMap->setPhpName('Role');
		$tMap->setClassname('Role');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('EMT_ROLE_SEQ');

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 4);

		$tMap->addColumn('SYSNAME', 'Sysname', 'VARCHAR', true, 50);

		$tMap->addForeignKey('PARENT_ID', 'ParentId', 'INTEGER', 'EMT_ROLE', 'ID', false, 4);

		$tMap->addColumn('MODULE', 'Module', 'VARCHAR', false, 50);

		$tMap->addForeignKey('RELATED_TYPE_ID', 'RelatedTypeId', 'INTEGER', 'EMT_PRIVACY_NODE_TYPE', 'ID', false, 3);

		$tMap->addForeignKey('OPPOSITE_ROLE_ID', 'OppositeRoleId', 'INTEGER', 'EMT_ROLE', 'ID', false, 4);

	} // doBuild()

} // RoleMapBuilder
