<?php


/**
 * This class adds structure of 'EMT_TRADE_EXPERT_AREA' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/10/12 16:11:05
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TradeExpertAreaMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TradeExpertAreaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(TradeExpertAreaPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(TradeExpertAreaPeer::TABLE_NAME);
		$tMap->setPhpName('TradeExpertArea');
		$tMap->setClassname('TradeExpertArea');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('ID', 'Id', 'INTEGER' , 'EMT_TRADE_EXPERT', 'ID', true, 10);

		$tMap->addColumn('COUNTRY', 'Country', 'VARCHAR', false, 5);

		$tMap->addForeignKey('STATE', 'State', 'INTEGER', 'EXT_GEONAME', 'GEONAME_ID', false, 7);

		$tMap->addColumn('CITY', 'City', 'VARCHAR', false, 50);

	} // doBuild()

} // TradeExpertAreaMapBuilder
