<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/03 03:24:23
sfConfig::add(array(
  'app_cryptographp_reloadimg' => '/images/layout/button/reload.png',
  'app_cryptographp_char_nb_min' => 5,
  'app_cryptographp_char_nb_max' => 5,
  'app_cryptographp_noise_line_min' => 0,
  'app_cryptographp_noise_line_max' => 0,
  'app_cryptographp_nb_circle_max' => 0,
  'app_cryptographp_char_colorrnd' => false,
  'app_cryptographp_char_anglemax' => 25,
  'app_emailtrans_default' => array (
  'smtp_host' => 'mail.emarketturkey.com',
  'smtp_port' => 5000,
),
  'app_emailtrans_user_signup' => array (
  'email_sender_address' => 'notify@emarketturkey.com',
  'email_subject' => '__(\'REGISTRATION COMPLETE\')',
  'format' => '1            template_html: \'signup/registrationInformMailHtml\'',
  'template_text' => 'signup/registrationInformMailText',
  'rule_id' => '1            username:  \'notify\'',
  'password' => 'emtnotify',
),
  'app_password_readable' => true,
  'app_password_prefs' => array (
  'readable' => 
  array (
    'minDigits' => 3,
    'maxDigits' => 4,
    'syllables' => 2,
    'minLength' => 7,
    'maxLength' => 10,
  ),
  'hashed' => 
  array (
    'includeNumerals' => true,
    'includeLetters' => true,
    'includeSymbols' => false,
    'minLength' => 8,
    'maxLength' => 12,
  ),
),
  'app_i18n_cultures' => array (
  1 => 'en',
  2 => 'tr',
),
  'app_photoConfig_size' => array (
  1 => 
  array (
    'crop' => true,
    'small' => 
    array (
      'width' => 50,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 130,
      'height' => 130,
    ),
    'large' => 
    array (
      'width' => 540,
      'height' => 405,
    ),
  ),
  3 => 
  array (
    'small' => 
    array (
      'width' => 85,
      'height' => 90,
    ),
    'medium' => 
    array (
      'width' => 130,
      'height' => 130,
    ),
    'large' => 
    array (
      'width' => 600,
      'height' => 600,
    ),
  ),
  6 => 
  array (
    'small' => 
    array (
      'width' => 50,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 130,
      'height' => 130,
    ),
    'large' => 
    array (
      'width' => 600,
      'height' => 600,
    ),
  ),
  7 => 
  array (
    'crop' => true,
    'small' => 
    array (
      'width' => 100,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 180,
      'height' => 90,
    ),
    'large' => 
    array (
      'width' => 948,
      'height' => 474,
    ),
  ),
  9 => 
  array (
    'crop' => true,
    'small' => 
    array (
      'width' => 145,
      'height' => 82,
    ),
    'medium' => 
    array (
      'width' => 290,
      'height' => 164,
    ),
    'large' => 
    array (
      'width' => 610,
      'height' => 280,
    ),
  ),
  10 => 
  array (
    'small' => 
    array (
      'width' => 140,
      'height' => 25,
    ),
    'medium' => 
    array (
      'width' => 160,
      'height' => 60,
    ),
    'large' => 
    array (
      'width' => 600,
      'height' => 300,
    ),
  ),
  11 => 
  array (
    'small' => 
    array (
      'width' => 100,
      'height' => 100,
    ),
    'medium' => 
    array (
      'width' => 300,
      'height' => 300,
    ),
    'large' => 
    array (
      'width' => 600,
      'height' => 600,
    ),
  ),
  14 => 
  array (
    'small' => 
    array (
      'width' => 100,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 400,
      'height' => 200,
    ),
    'large' => 
    array (
      'width' => 800,
      'height' => 400,
    ),
  ),
  15 => 
  array (
    'small' => 
    array (
      'width' => 60,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 132,
      'height' => 110,
    ),
    'large' => 
    array (
      'width' => 264,
      'height' => 220,
    ),
  ),
  16 => 
  array (
    'small' => 
    array (
      'width' => 120,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 132,
      'height' => 55,
    ),
    'large' => 
    array (
      'width' => 264,
      'height' => 110,
    ),
  ),
  17 => 
  array (
    'small' => 
    array (
      'width' => 32,
      'height' => 27,
    ),
    'medium' => 
    array (
      'width' => 64,
      'height' => 54,
    ),
    'large' => 
    array (
      'width' => 128,
      'height' => 108,
    ),
  ),
  18 => 
  array (
    'crop' => true,
    'small' => 
    array (
      'width' => 50,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 160,
      'height' => 160,
    ),
    'large' => 
    array (
      'width' => 400,
      'height' => 400,
    ),
  ),
  19 => 
  array (
    'crop' => true,
    'small' => 
    array (
      'width' => 70,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 196,
      'height' => 140,
    ),
    'large' => 
    array (
      'width' => 560,
      'height' => 400,
    ),
  ),
  20 => 
  array (
    'crop' => true,
    'small' => 
    array (
      'width' => 70,
      'height' => 50,
    ),
    'medium' => 
    array (
      'width' => 196,
      'height' => 140,
    ),
    'large' => 
    array (
      'width' => 560,
      'height' => 400,
    ),
  ),
  21 => 
  array (
    'crop' => false,
    'small' => 
    array (
      'width' => 120,
      'height' => 90,
    ),
    'medium' => 
    array (
      'width' => 200,
      'height' => 150,
    ),
    'large' => 
    array (
      'width' => 400,
      'height' => 300,
    ),
  ),
),
  'app_swToolbox_cross_link_application' => array (
  'lobby' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'myemt' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'my.geek.emt',
          'test' => 'my.emarketturkey.com',
          'prod' => 'my.emarketturkey.com',
        ),
      ),
      'hr' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'hr.geek.emt',
          'test' => 'hr.emarketturkey.com',
          'prod' => 'hr.emarketturkey.com',
        ),
      ),
      'b2b' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'b2b.geek.emt',
          'test' => 'b2b.emarketturkey.com',
          'prod' => 'b2b.emarketturkey.com',
        ),
      ),
      'ac' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ac.geek.emt',
          'test' => 'ac.emarketturkey.com',
          'prod' => 'ac.emarketturkey.com',
        ),
      ),
      'cm' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'cm.geek.emt',
          'test' => 'cm.emarketturkey.com',
          'prod' => 'cm.emarketturkey.com',
        ),
      ),
      'tx' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'tx.geek.emt',
          'test' => 'tx.emarketturkey.com',
          'prod' => 'tx.emarketturkey.com',
        ),
      ),
      'ads' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ads.geek.emt',
          'test' => 'ads.emarketturkey.com',
          'prod' => 'ads.emarketturkey.com',
        ),
      ),
    ),
  ),
  'hr' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'myemt' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'my.geek.emt',
          'test' => 'my.emarketturkey.com',
          'prod' => 'my.emarketturkey.com',
        ),
      ),
      'lobby' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'geek.emt',
          'test' => 'emarketturkey.com',
          'prod' => 'emarketturkey.com',
        ),
      ),
      'b2b' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'b2b.geek.emt',
          'test' => 'b2b.emarketturkey.com',
          'prod' => 'b2b.emarketturkey.com',
        ),
      ),
      'ac' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ac.geek.emt',
          'test' => 'ac.emarketturkey.com',
          'prod' => 'ac.emarketturkey.com',
        ),
      ),
      'cm' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'cm.geek.emt',
          'test' => 'cm.emarketturkey.com',
          'prod' => 'cm.emarketturkey.com',
        ),
      ),
      'tx' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'tx.geek.emt',
          'test' => 'tx.emarketturkey.com',
          'prod' => 'tx.emarketturkey.com',
        ),
      ),
      'ads' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ads.geek.emt',
          'test' => 'ads.emarketturkey.com',
          'prod' => 'ads.emarketturkey.com',
        ),
      ),
    ),
  ),
  'myemt' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'hr' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'hr.geek.emt',
          'test' => 'hr.emarketturkey.com',
          'prod' => 'hr.emarketturkey.com',
        ),
      ),
      'lobby' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'geek.emt',
          'test' => 'emarketturkey.com',
          'prod' => 'emarketturkey.com',
        ),
      ),
      'b2b' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'b2b.geek.emt',
          'test' => 'b2b.emarketturkey.com',
          'prod' => 'b2b.emarketturkey.com',
        ),
      ),
      'ac' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ac.geek.emt',
          'test' => 'ac.emarketturkey.com',
          'prod' => 'ac.emarketturkey.com',
        ),
      ),
      'cm' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'cm.geek.emt',
          'test' => 'cm.emarketturkey.com',
          'prod' => 'cm.emarketturkey.com',
        ),
      ),
      'tx' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'tx.geek.emt',
          'test' => 'tx.emarketturkey.com',
          'prod' => 'tx.emarketturkey.com',
        ),
      ),
      'ads' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ads.geek.emt',
          'test' => 'ads.emarketturkey.com',
          'prod' => 'ads.emarketturkey.com',
        ),
      ),
    ),
  ),
  'b2b' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'hr' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'hr.geek.emt',
          'test' => 'hr.emarketturkey.com',
          'prod' => 'hr.emarketturkey.com',
        ),
      ),
      'lobby' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'geek.emt',
          'test' => 'emarketturkey.com',
          'prod' => 'emarketturkey.com',
        ),
      ),
      'myemt' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'my.geek.emt',
          'test' => 'my.emarketturkey.com',
          'prod' => 'my.emarketturkey.com',
        ),
      ),
      'ac' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ac.geek.emt',
          'test' => 'ac.emarketturkey.com',
          'prod' => 'ac.emarketturkey.com',
        ),
      ),
      'cm' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'cm.geek.emt',
          'test' => 'cm.emarketturkey.com',
          'prod' => 'cm.emarketturkey.com',
        ),
      ),
      'tx' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'tx.geek.emt',
          'test' => 'tx.emarketturkey.com',
          'prod' => 'tx.emarketturkey.com',
        ),
      ),
      'ads' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ads.geek.emt',
          'test' => 'ads.emarketturkey.com',
          'prod' => 'ads.emarketturkey.com',
        ),
      ),
    ),
  ),
  'cm' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'hr' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'hr.geek.emt',
          'test' => 'hr.emarketturkey.com',
          'prod' => 'hr.emarketturkey.com',
        ),
      ),
      'lobby' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'geek.emt',
          'test' => 'emarketturkey.com',
          'prod' => 'emarketturkey.com',
        ),
      ),
      'b2b' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'b2b.geek.emt',
          'test' => 'b2b.emarketturkey.com',
          'prod' => 'b2b.emarketturkey.com',
        ),
      ),
      'myemt' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'my.geek.emt',
          'test' => 'my.emarketturkey.com',
          'prod' => 'my.emarketturkey.com',
        ),
      ),
      'ac' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ac.geek.emt',
          'test' => 'ac.emarketturkey.com',
          'prod' => 'ac.emarketturkey.com',
        ),
      ),
      'tx' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'tx.geek.emt',
          'test' => 'tx.emarketturkey.com',
          'prod' => 'tx.emarketturkey.com',
        ),
      ),
      'ads' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ads.geek.emt',
          'test' => 'ads.emarketturkey.com',
          'prod' => 'ads.emarketturkey.com',
        ),
      ),
    ),
  ),
  'ac' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'hr' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'hr.geek.emt',
          'test' => 'hr.emarketturkey.com',
          'prod' => 'hr.emarketturkey.com',
        ),
      ),
      'lobby' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'geek.emt',
          'test' => 'emarketturkey.com',
          'prod' => 'emarketturkey.com',
        ),
      ),
      'b2b' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'b2b.geek.emt',
          'test' => 'b2b.emarketturkey.com',
          'prod' => 'b2b.emarketturkey.com',
        ),
      ),
      'myemt' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'my.geek.emt',
          'test' => 'my.emarketturkey.com',
          'prod' => 'my.emarketturkey.com',
        ),
      ),
      'cm' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'cm.geek.emt',
          'test' => 'cm.emarketturkey.com',
          'prod' => 'cm.emarketturkey.com',
        ),
      ),
      'tx' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'tx.geek.emt',
          'test' => 'tx.emarketturkey.com',
          'prod' => 'tx.emarketturkey.com',
        ),
      ),
      'ads' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ads.geek.emt',
          'test' => 'ads.emarketturkey.com',
          'prod' => 'ads.emarketturkey.com',
        ),
      ),
    ),
  ),
  'tx' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'hr' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'hr.geek.emt',
          'test' => 'hr.emarketturkey.com',
          'prod' => 'hr.emarketturkey.com',
        ),
      ),
      'lobby' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'geek.emt',
          'test' => 'emarketturkey.com',
          'prod' => 'emarketturkey.com',
        ),
      ),
      'b2b' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'b2b.geek.emt',
          'test' => 'b2b.emarketturkey.com',
          'prod' => 'b2b.emarketturkey.com',
        ),
      ),
      'myemt' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'my.geek.emt',
          'test' => 'my.emarketturkey.com',
          'prod' => 'my.emarketturkey.com',
        ),
      ),
      'ac' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ac.geek.emt',
          'test' => 'ac.emarketturkey.com',
          'prod' => 'ac.emarketturkey.com',
        ),
      ),
      'cm' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'cm.geek.emt',
          'test' => 'cm.emarketturkey.com',
          'prod' => 'cm.emarketturkey.com',
        ),
      ),
      'ads' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ads.geek.emt',
          'test' => 'ads.emarketturkey.com',
          'prod' => 'ads.emarketturkey.com',
        ),
      ),
    ),
  ),
  'ads' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'hr' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'hr.geek.emt',
          'test' => 'hr.emarketturkey.com',
          'prod' => 'hr.emarketturkey.com',
        ),
      ),
      'lobby' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'geek.emt',
          'test' => 'emarketturkey.com',
          'prod' => 'emarketturkey.com',
        ),
      ),
      'b2b' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'b2b.geek.emt',
          'test' => 'b2b.emarketturkey.com',
          'prod' => 'b2b.emarketturkey.com',
        ),
      ),
      'myemt' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'my.geek.emt',
          'test' => 'my.emarketturkey.com',
          'prod' => 'my.emarketturkey.com',
        ),
      ),
      'ac' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'ac.geek.emt',
          'test' => 'ac.emarketturkey.com',
          'prod' => 'ac.emarketturkey.com',
        ),
      ),
      'cm' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'cm.geek.emt',
          'test' => 'cm.emarketturkey.com',
          'prod' => 'cm.emarketturkey.com',
        ),
      ),
    ),
  ),
),
  'app_routerAction_createCV' => array (
  'actions' => 
  array (
    0 => 'basic',
    1 => 'contact',
    2 => 'education',
    3 => 'work',
    4 => 'courses',
    5 => 'languages',
    6 => 'skills',
    7 => 'publications',
    8 => 'awards',
    9 => 'references',
    10 => 'custom',
    11 => 'organisations',
    12 => 'materials',
  ),
),
  'app_file_extension_icons' => array (
  'doc' => '/images/layout/icon/filetypes/doc-ext.gif',
  'exe' => '/images/layout/icon/filetypes/exe-ext.gif',
  'gif' => '/images/layout/icon/filetypes/gif-ext.gif',
  'jpeg' => '/images/layout/icon/filetypes/jpeg-ext.gif',
  'jpg' => '/images/layout/icon/filetypes/jpg-ext.gif',
  'pdf' => '/images/layout/icon/filetypes/pdf-ext.gif',
  'png' => '/images/layout/icon/filetypes/png-ext.gif',
  'rar' => '/images/layout/icon/filetypes/rar-ext.gif',
  'txt' => '/images/layout/icon/filetypes/txt-ext.gif',
  'xls' => '/images/layout/icon/filetypes/xls-ext.gif',
  'xml' => '/images/layout/icon/filetypes/xml-ext.gif',
  'zip' => '/images/layout/icon/filetypes/zip-ext.gif',
  'default' => '/images/layout/icon/filetypes/all-ext.gif',
),
  'app_vault_domain' => array (
  'dev' => 'http://vault.geek.emt',
  'prod' => 'http://vault.emarketturkey.com',
),
  'app_vault_path' => array (
  'dev' => 'c:\\file_vault',
  'prod' => '/file_vault',
),
  'app_consent_live' => array (
  'debug' => false,
  'offers' => 'Contacts.View',
  'keyfile' => 'C:\\EMT.workspace\\geek\\config/DelAuth.xml',
  'cookie' => 'delauth',
  'index' => '@cm.friendfinder',
  'handler' => '@myemt.consent-handle',
  'import' => '@myemt.consent-import',
  'add-friend' => '@cm.consent-add',
  'invite-friend' => '@cm.consent-invite',
  'banned_emails' => 
  array (
  ),
),
  'app_consent_google' => array (
  'Consumer_Key' => 'my.emarketturkey.com',
  'Consumer_Secret' => 'JCxZ4GbDsZ/zZeVgEPvPrf/F',
  'Authorization' => 'OAuth',
  'Url' => 
  array (
    'OAuthGetRequestTokenUrl' => 'https://www.google.com/accounts/OAuthGetRequestToken',
    'OAuthAuthorizeTokenUrl' => 'https://www.google.com/accounts/OAuthAuthorizeToken',
    'OAuthGetAccessTokenUrl' => 'https://www.google.com/accounts/OAuthGetAccessToken',
  ),
  'OAuth' => 
  array (
    'oauth_consumer_key' => 'my.emarketturkey.com',
    'oauth_signature_method' => 'HMAC-SHA1',
    'oauth_version' => '1.0',
    'oauth_callback' => '@myemt.consent-handle-google',
    'oauth_signature' => 'MIICXQIBAAKBgQDMQNqbTXj1vXp+2BFIOjGF4R5ubkxTaTuQU1/51RcSv0f5MNeQ
khASlYmVaq70o7oyFFNToSYlp3gkF9H4y8q0QL2iWVvzr2nl0PZ9FDITDBBdn6zb
nDeEuRQt6xUfkhSG1x5ZTiFZLDr/ZECrIw0zMywZ6pEarP2sORFl3zz79wIDAQAB
AoGAdFSjrTwsnllygPfyr95lAkk7Gc48Lm2K/SJfUV1qLMVA6s5EmBR4jv0YRT9j
sfXmQEuPQdxQa7W8GWJvtnHrWkXgu/a37AMgjrkBncQ5N4cZFzjedOklRnk0+ny5
4foVegsGV9qRO4+cRQhB6tcgIXhynJUSuQU83piUIypqPmECQQDmztUNCifIJY4E
53QmFA1vA2jO1Ocw4mboNliX3n9liNc5xdTFfa4v7R39+cdBRwkDRdo/YKYg8CSd
tYd2ZT4ZAkEA4owKcD69FPROLzrshfwkh4ZA3O4xBguHCRigWiNOroEKbmrWavnL
w2vK9HXrDHtquLZF+w3my8vhopwwgHssjwJBAJjwAJhtXELxL5PsUjhRHT2sQqya
wr7PpmTEbhvj4QLEk+jCP+TFDMDRHAiIlBGbIku6440PW8WDmp+uA57eIzECQAa/
ZRAyzi7xl+KQPrs+51eiCAyMi6lCbqM2uI/2vUE1VrozNG+7QPZxH3poiLe2dVdL
FoqDv3wSdoYBYPByusECQQCg6Vu/QbxwHoIWWHGnL7R46sZKjsnTxN1OQ1liTMHt
lyxuhuK1MhnOUYOusrurKTVOiEwkCA8cTPkWMpw6cNIL',
  ),
  'scope' => 'https://www.google.com/m8/feeds/contacts/default/full',
  'index' => '@cm.friendfinder',
  'handler' => '@myemt.google-handle',
  'import' => '@myemt.google-import',
  'add-friend' => '@cm.consent-add',
  'invite-friend' => '@cm.consent-invite',
  'banned_emails' => 
  array (
  ),
),
  'app_jobs_criteria' => array (
  'industry' => NULL,
  'job_function' => NULL,
  'experience_level' => NULL,
  'salary' => NULL,
  'location' => NULL,
  'company' => NULL,
  'education_level' => NULL,
  'work_scheme' => NULL,
  'gender' => NULL,
  'special_cases' => NULL,
),
  'app_jobs_profileconf' => array (
  'max_folder_count' => 10,
  'messagetemps' => 
  array (
    1 => 'jobs/template_evaluating',
    2 => 'jobs/template_rejected',
    3 => 'jobs/template_accepted',
  ),
),
  'app_objectHandler_ResumeSchool' => array (
  'editor' => 'mycv/school-edit',
  'viewer' => 'mycv/school-view',
  'msgRemovalConfirm' => 'Please confirm the removal of education record.',
  'msgRemovalSuccess' => 'Education record has been successfully removed.',
  'msgSaveSuccess' => 'Education record has been successfully saved.',
),
  'app_objectHandler_ResumeWork' => array (
  'editor' => 'mycv/work-edit',
  'viewer' => 'mycv/work-view',
  'msgRemovalConfirm' => 'Please confirm the removal of work experience record.',
  'msgRemovalSuccess' => 'Work experience record has been successfully removed.',
  'msgSaveSuccess' => 'Work experience record has been successfully saved.',
),
  'app_objectHandler_ResumeCourse' => array (
  'editor' => 'mycv/course-edit',
  'viewer' => 'mycv/course-view',
  'msgRemovalConfirm' => 'Please confirm the removal of course/certificate record.',
  'msgRemovalSuccess' => 'Course/Certificate record has been successfully removed.',
  'msgSaveSuccess' => 'Course/Certificate record has been successfully saved.',
),
  'app_objectHandler_ResumeLanguage' => array (
  'editor' => 'mycv/language-edit',
  'viewer' => 'mycv/language-view',
  'msgRemovalConfirm' => 'Please confirm the removal of language record.',
  'msgRemovalSuccess' => 'Language record has been successfully removed.',
  'msgSaveSuccess' => 'Language record has been successfully saved.',
),
  'app_objectHandler_ResumePublication' => array (
  'editor' => 'mycv/publication-edit',
  'viewer' => 'mycv/publication-view',
  'msgRemovalConfirm' => 'Please confirm the removal of publication record.',
  'msgRemovalSuccess' => 'Publication record has been successfully removed.',
  'msgSaveSuccess' => 'Publication record has been successfully saved.',
),
  'app_objectHandler_ResumeAward' => array (
  'editor' => 'mycv/award-edit',
  'viewer' => 'mycv/award-view',
  'msgRemovalConfirm' => 'Please confirm the removal of award/honor record.',
  'msgRemovalSuccess' => 'Award/Honor record has been successfully removed.',
  'msgSaveSuccess' => 'Award/Honor record has been successfully saved.',
),
  'app_objectHandler_ResumeReference' => array (
  'editor' => 'mycv/reference-edit',
  'viewer' => 'mycv/reference-view',
  'msgRemovalConfirm' => 'Please confirm the removal of reference record.',
  'msgRemovalSuccess' => 'Reference record has been successfully removed.',
  'msgSaveSuccess' => 'Reference record has been successfully saved.',
),
  'app_objectHandler_ResumeOrganisation' => array (
  'editor' => 'mycv/organisation-edit',
  'viewer' => 'mycv/organisation-view',
  'msgRemovalConfirm' => 'Please confirm the removal of organisation record.',
  'msgRemovalSuccess' => 'Organisation record has been successfully removed.',
  'msgSaveSuccess' => 'Organisation record has been successfully saved.',
),
  'app_objectHandler_Publication' => array (
  'typed' => true,
  'types' => 
  array (
    1 => 
    array (
      'editor' => 'author/article-edit',
      'viewer' => 'author/article-view',
      'msgRemovalConfirm' => 'Please confirm the removal of selected article.',
      'msgRemovalSuccess' => 'Article has been successfully removed.',
      'msgSaveSuccess' => 'Article has been successfully saved.',
      'msgActivateSuccess' => 'Article has been activated.',
      'msgDeActivateSuccess' => 'Article has been de-activated.',
    ),
    2 => 
    array (
      'editor' => 'author/news-edit',
      'viewer' => 'author/news-view',
      'msgRemovalConfirm' => 'Please confirm the removal of selected news.',
      'msgRemovalSuccess' => 'News has been successfully removed.',
      'msgSaveSuccess' => 'News has been successfully saved.',
      'msgActivateSuccess' => 'News has been activated.',
      'msgDeActivateSuccess' => 'News has been de-activated.',
    ),
  ),
),
  'app_objectHandler_Author' => array (
  'editor' => 'author/author-edit',
  'viewer' => 'author/author-view',
  'msgRemovalConfirm' => 'Please confirm the removal of selected author.',
  'msgRemovalSuccess' => 'Author has been successfully removed.',
  'msgSaveSuccess' => 'Author has been successfully saved.',
  'msgActivateSuccess' => 'Author has been activated.',
  'msgDeActivateSuccess' => 'Author has been de-activated.',
),
  'app_objectHandler_PublicationSource' => array (
  'editor' => 'author/source-edit',
  'viewer' => 'author/source-view',
  'msgRemovalConfirm' => 'Please confirm the removal of selected publication source.',
  'msgRemovalSuccess' => 'Publication Source has been successfully removed.',
  'msgSaveSuccess' => 'Publication Source has been successfully saved.',
  'msgActivateSuccess' => 'Publication Source has been activated.',
  'msgDeActivateSuccess' => 'Publication Source has been de-activated.',
),
  'app_objectHandler_PublicationCategory' => array (
  'editor' => 'author/category-edit',
  'viewer' => 'author/category-view',
  'msgRemovalConfirm' => 'Please confirm the removal of selected publication category.',
  'msgRemovalSuccess' => 'Publication Category has been successfully removed.',
  'msgSaveSuccess' => 'Publication Category has been successfully saved.',
  'msgActivateSuccess' => 'Publication Category has been activated.',
  'msgDeActivateSuccess' => 'Publication Category has been de-activated.',
),
  'app_ticker_updateInterval' => 1,
  'app_ticker_feeds' => array (
  'google' => 
  array (
    'url' => 'http://www.google.com/finance/info?q=%symbols%',
    'seperator' => ',',
    'parser' => 'EmtGoogleFinanceResponseParser',
  ),
  'yahoo' => 
  array (
    'url' => 'http://finance.yahoo.com/d/quotes.csv?s=%symbols%&f=sl1',
    'seperator' => '+',
    'parser' => 'EmtYahooFinanceResponseParser',
  ),
),
  'app_main_emt_tables' => array (
  'articles' => 
  array (
    'modelClass' => 'Publication',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'author/articles_row',
    'rowCountLabel' => '%1 publications total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => 'author/article',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Article Name',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION.NAME',
        'applyFilter' => true,
      ),
      'category' => 
      array (
        'displayName' => 'Category',
        'isSortable' => false,
        'fieldName' => 'EMT_PUBLICATION_CATEGORY_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_PUBLICATION.CATEGORY_ID',
      ),
      'author' => 
      array (
        'displayName' => 'Author',
        'isSortable' => true,
        'fieldName' => 'EMT_AUTHOR.NAME || \' \' || EMT_AUTHOR.LASTNAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_PUBLICATION.AUTHOR_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'news' => 
  array (
    'modelClass' => 'Publication',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'author/news_row',
    'rowCountLabel' => '%1 news total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => 'author/news',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION.ID',
      ),
      'name' => 
      array (
        'displayName' => 'News Title',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION.NAME',
        'applyFilter' => true,
      ),
      'category' => 
      array (
        'displayName' => 'Category',
        'isSortable' => false,
        'fieldName' => 'EMT_PUBLICATION_CATEGORY_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_PUBLICATION.CATEGORY_ID',
      ),
      'source' => 
      array (
        'displayName' => 'Source',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION_SOURCE.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_PUBLICATION.SOURCE_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'authors' => 
  array (
    'modelClass' => 'Author',
    'showHeader' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'activateAction' => true,
    'rowPartial' => 'author/authors_row',
    'rowCountLabel' => '%1 authors total',
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_AUTHOR.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Author Name',
        'isSortable' => true,
        'fieldName' => 'EMT_AUTHOR.NAME',
        'applyFilter' => true,
      ),
    ),
  ),
  'companies' => 
  array (
    'modelClass' => 'Company',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/companies_row',
    'rowCountLabel' => '%1 companies total',
    'editAction' => true,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/company',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_COMPANY.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Company Name',
        'isSortable' => true,
        'fieldName' => 'EMT_COMPANY.NAME',
        'applyFilter' => true,
      ),
      'sector' => 
      array (
        'displayName' => 'Sector',
        'isSortable' => false,
        'fieldName' => 'EMT_BUSINESS_SECTOR_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_COMPANY.SECTOR_ID',
      ),
      'type' => 
      array (
        'displayName' => 'Type',
        'isSortable' => true,
        'fieldName' => 'EMT_BUSINESS_TYPE_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_COMPANY.BUSINESS_TYPE_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'sources' => 
  array (
    'modelClass' => 'PublicationSource',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'author/source_row',
    'rowCountLabel' => '%1 sources total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => 'author/source',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION_SOURCE.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Source Name',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION_SOURCE.NAME',
        'applyFilter' => true,
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'paymentterms' => 
  array (
    'modelClass' => 'PaymentTerm',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'code',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/paymentterm_row',
    'rowCountLabel' => '%1 payment terms total',
    'editAction' => true,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/paymentTerm',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_PAYMENT_TERM.ID',
      ),
      'code' => 
      array (
        'displayName' => 'Code',
        'isSortable' => true,
        'fieldName' => 'EMT_PAYMENT_TERM.CODE',
        'applyFilter' => true,
      ),
      'name' => 
      array (
        'displayName' => 'Payment Term Name',
        'isSortable' => true,
        'fieldName' => 'EMT_PAYMENT_TERM_I18N.NAME',
        'applyFilter' => true,
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'businesstypes' => 
  array (
    'modelClass' => 'BusinessType',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/businesstype_row',
    'rowCountLabel' => '%1 business types total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/businessType',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_BUSINESS_TYPE.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Business Type Name',
        'isSortable' => true,
        'fieldName' => 'EMT_BUSINESS_TYPE_I18N.NAME',
        'applyFilter' => true,
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'businesssectors' => 
  array (
    'modelClass' => 'BusinessSector',
    'showHeader' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/businesssector_row',
    'rowCountLabel' => '%1 sectors total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/businessSector',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_BUSINESS_SECTOR.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Business Sector Name',
        'isSortable' => true,
        'fieldName' => 'EMT_BUSINESS_SECTOR_I18N.NAME',
        'applyFilter' => true,
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'pubcategories' => 
  array (
    'modelClass' => 'PublicationCategory',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'id',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'author/pubcategory_row',
    'rowCountLabel' => '%1 categories total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => 'author/category',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION_CATEGORY.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Category Name',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION_CATEGORY_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_PUBLICATION_CATEGORY.ID',
      ),
      'parent' => 
      array (
        'displayName' => 'Parent Category',
        'isSortable' => true,
        'fieldName' => 'EMT_PUBLICATION_CATEGORY_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_PUBLICATION_CATEGORY.PARENT_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'users' => 
  array (
    'modelClass' => 'User',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'id',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/user_row',
    'rowCountLabel' => '%1 users total',
    'editAction' => true,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/user',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_USER.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Name',
        'isSortable' => true,
        'fieldName' => 'EMT_USER.NAME',
        'applyFilter' => true,
      ),
      'lastname' => 
      array (
        'displayName' => 'Lastname',
        'isSortable' => true,
        'fieldName' => 'EMT_USER.LASTNAME',
        'applyFilter' => true,
      ),
      'joinedat' => 
      array (
        'displayName' => 'Joined At',
        'isSortable' => true,
        'fieldName' => 'EMT_USER.CREATED_AT',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'mediaitems' => 
  array (
    'modelClass' => 'MediaItem',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'id',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/mediaitem_row',
    'rowCountLabel' => '%1 media items total',
    'editAction' => true,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/mediaItem',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_MEDIA_ITEM.ID',
      ),
      'filename' => 
      array (
        'displayName' => 'File Name',
        'isSortable' => true,
        'fieldName' => 'EMT_MEDIA_ITEM.FILENAME || \'.\' || EMT_MEDIA_ITEM.FILE_EXTENSION',
        'applyFilter' => true,
      ),
      'owner' => 
      array (
        'displayName' => 'Owner',
        'isSortable' => false,
        'fieldName' => 'EMT_MEDIA_ITEM.OWNER_ID',
        'applyFilter' => true,
      ),
      'filesize' => 
      array (
        'displayName' => 'File Size',
        'isSortable' => true,
        'fieldName' => 'EMT_MEDIA_ITEM.FILE_SIZE',
        'applyFilter' => true,
      ),
      'uploadedat' => 
      array (
        'displayName' => 'Uploaded At',
        'isSortable' => true,
        'fieldName' => 'EMT_MEDIA_ITEM.CREATED_AT',
      ),
      'status' => 
      array (
        'displayName' => 'Status',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'services' => 
  array (
    'modelClass' => 'Service',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'id',
    'itemsPerPage' => 10,
    'selectable' => '1',
    'rowPartial' => 'admin/service_row',
    'rowCountLabel' => '%1 services total',
    'editAction' => true,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/service',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_SERVICE.ID',
      ),
      'servicename' => 
      array (
        'displayName' => 'Service Name',
        'isSortable' => true,
        'fieldName' => 'EMT_SERVICE_I18N.NAME',
        'applyFilter' => true,
      ),
      'application' => 
      array (
        'displayName' => 'Application',
        'isSortable' => false,
        'fieldName' => 'EMT_APPLICATION.APP_CODE',
        'applyFilter' => false,
        'joinWith' => 'EMT_SERVICE.APPLICATION_ID',
      ),
      'appliesto' => 
      array (
        'displayName' => 'Applies To',
        'isSortable' => true,
        'fieldName' => 'EMT_PRIVACY_NODE_TYPE_I18N.NAME',
        'applyFilter' => false,
        'joinWith' => 'EMT_SERVICE.APPLIES_TO_TYPE_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'applications' => 
  array (
    'modelClass' => 'Application',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'id',
    'itemsPerPage' => 10,
    'selectable' => '1',
    'rowPartial' => 'admin/application_row',
    'rowCountLabel' => '%1 applications total',
    'editAction' => true,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/application',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_APPLICATION.ID',
      ),
      'appcode' => 
      array (
        'displayName' => 'App Code',
        'isSortable' => true,
        'fieldName' => 'EMT_APPLICATION.APP_CODE',
        'applyFilter' => true,
      ),
      'name' => 
      array (
        'displayName' => 'Application Name',
        'isSortable' => true,
        'fieldName' => 'EMT_APPLICATION_I18N.NAME',
        'applyFilter' => true,
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'packages' => 
  array (
    'modelClass' => 'MarketingPackage',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'id',
    'itemsPerPage' => 10,
    'selectable' => '1',
    'rowPartial' => 'admin/package_row',
    'rowCountLabel' => '%1 packages total',
    'editAction' => true,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/package',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_MARKETING_PACKAGE.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Package Name',
        'isSortable' => true,
        'fieldName' => 'EMT_MARKETING_PACKAGE_I18N.NAME',
        'applyFilter' => true,
      ),
      'appliesto' => 
      array (
        'displayName' => 'Applies To',
        'isSortable' => true,
        'fieldName' => 'EMT_PRIVACY_NODE_TYPE_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_MARKETING_PACKAGE.APPLIES_TO_TYPE_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'emailtransactions' => 
  array (
    'modelClass' => 'EmailTransaction',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'id',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/emailtransaction_row',
    'rowCountLabel' => '%1 transactions total',
    'editAction' => false,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/emailTransaction',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_EMAIL_TRANSACTION.ID',
      ),
      'email' => 
      array (
        'displayName' => 'Email',
        'isSortable' => true,
        'fieldName' => 'EMT_EMAIL_TRANSACTION.EMAIL',
        'applyFilter' => true,
      ),
      'namespace' => 
      array (
        'displayName' => 'Namespace',
        'isSortable' => false,
        'fieldName' => 'EMT_EMAIL_TRANSACTION_NS.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_EMAIL_TRANSACTION.NAMESPACE_ID',
      ),
      'recipient' => 
      array (
        'displayName' => 'Recipient',
        'isSortable' => false,
        'fieldName' => 'EMT_EMAIL_TRANSACTION.RCPNT_USER_ID',
        'applyFilter' => false,
      ),
      'updatedat' => 
      array (
        'displayName' => 'Updated At',
        'isSortable' => false,
        'fieldName' => 'EMT_EMAIL_TRANSACTION.UPDATED_AT',
        'applyFilter' => false,
      ),
      'status' => 
      array (
        'displayName' => 'Status',
        'isSortable' => true,
        'fieldName' => 'EMT_EMAIL_TRANSACTION.STATUS',
        'applyFilter' => false,
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'jobpositions' => 
  array (
    'modelClass' => 'JobPosition',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/jobposition_row',
    'rowCountLabel' => '%1 positions total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/jobPosition',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_JOB_POSITION.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Name',
        'isSortable' => true,
        'fieldName' => 'EMT_JOB_POSITION_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_JOB_POSITION.ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'jobgrades' => 
  array (
    'modelClass' => 'JobGrade',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'admin/jobgrade_row',
    'rowCountLabel' => '%1 grades total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/jobGrade',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_JOB_GRADE.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Name',
        'isSortable' => true,
        'fieldName' => 'EMT_JOB_GRADE_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_JOB_GRADE.ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'products' => 
  array (
    'modelClass' => 'Product',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'products/product_row',
    'rowCountLabel' => '%1 products total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => '@edit-product?hash={$row->getCompany()->getHash()}&id={$row->getId()}',
    ),
    'columns' => 
    array (
      'thumbnail' => 
      array (
        'displayName' => 'Thumbnail',
        'isSortable' => false,
        'fieldName' => 'EMT_PRODUCT.ID',
      ),
      'model' => 
      array (
        'displayName' => 'Model',
        'isSortable' => true,
        'fieldName' => 'EMT_PRODUCT.MODEL_NO',
        'applyFilter' => true,
      ),
      'name' => 
      array (
        'displayName' => 'Name',
        'isSortable' => true,
        'fieldName' => 'EMT_PRODUCT.NAME',
        'applyFilter' => true,
      ),
      'category' => 
      array (
        'displayName' => 'Category',
        'isSortable' => true,
        'fieldName' => 'EMT_PRODUCT_CATEGORY_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_PRODUCT.CATEGORY_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'leads' => 
  array (
    'modelClass' => 'B2bLead',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'name',
    'itemsPerPage' => 10,
    'selectable' => 'N',
    'rowPartial' => 'leads/lead_row',
    'rowCountLabel' => '%1 leads total',
    'editAction' => true,
    'deleteAction' => true,
    'activateAction' => true,
    'itemUrl' => 
    array (
      0 => '@edit-lead?hash={$row->getCompany()->getHash()}&id={$row->getId()}',
    ),
    'columns' => 
    array (
      'thumbnail' => 
      array (
        'displayName' => 'Thumbnail',
        'isSortable' => false,
        'fieldName' => 'EMT_B2B_LEAD.ID',
      ),
      'name' => 
      array (
        'displayName' => 'Name',
        'isSortable' => true,
        'fieldName' => 'EMT_B2B_LEAD.NAME',
        'applyFilter' => true,
      ),
      'category' => 
      array (
        'displayName' => 'Category',
        'isSortable' => true,
        'fieldName' => 'EMT_PRODUCT_CATEGORY_I18N.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_B2B_LEAD.CATEGORY_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
  'platformads' => 
  array (
    'modelClass' => 'PlatformAd',
    'showHeader' => true,
    'showItemsPerPage' => true,
    'orderColumn' => 'id',
    'itemsPerPage' => 10,
    'selectable' => '1',
    'rowPartial' => 'admin/platform_ad_row',
    'rowCountLabel' => '%1 ads total',
    'editAction' => true,
    'deleteAction' => true,
    'itemUrl' => 
    array (
      0 => 'admin/platformAd',
    ),
    'columns' => 
    array (
      'id' => 
      array (
        'displayName' => 'ID',
        'isSortable' => true,
        'fieldName' => 'EMT_PLATFORM_AD.ID',
      ),
      'title' => 
      array (
        'displayName' => 'Title',
        'isSortable' => true,
        'fieldName' => 'EMT_PLATFORM_AD.TITLE',
        'applyFilter' => true,
      ),
      'company' => 
      array (
        'displayName' => 'Company',
        'isSortable' => true,
        'fieldName' => 'EMT_COMPANY.NAME',
        'applyFilter' => true,
        'joinWith' => 'EMT_PLATFORM_AD.RELATED_COMPANY_ID',
      ),
      'actions' => 
      array (
        'displayName' => 'Actions',
        'isActionColumn' => true,
      ),
    ),
  ),
),
));
