<?php

/**
 * Base class that represents a row from the 'EMT_ANNOUNCEMENT' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/10/12 16:11:02
 *
 * @package    lib.model.om
 */
abstract class BaseAnnouncement extends BaseObject  implements Persistent {


  const PEER = 'AnnouncementPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AnnouncementPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the guid field.
	 * Note: this column has a database default value of: 'sys_guid()'
	 * @var        string
	 */
	protected $guid;

	/**
	 * The value for the owner_id field.
	 * @var        int
	 */
	protected $owner_id;

	/**
	 * The value for the owner_type_id field.
	 * @var        int
	 */
	protected $owner_type_id;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the channel_id field.
	 * @var        int
	 */
	protected $channel_id;

	/**
	 * The value for the layout_id field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $layout_id;

	/**
	 * The value for the delivery_mode_id field.
	 * @var        int
	 */
	protected $delivery_mode_id;

	/**
	 * The value for the deliver_from field.
	 * @var        string
	 */
	protected $deliver_from;

	/**
	 * The value for the deliver_by field.
	 * @var        string
	 */
	protected $deliver_by;

	/**
	 * The value for the object_id field.
	 * @var        int
	 */
	protected $object_id;

	/**
	 * The value for the object_type_id field.
	 * @var        int
	 */
	protected $object_type_id;

	/**
	 * The value for the content_type_id field.
	 * @var        int
	 */
	protected $content_type_id;

	/**
	 * The value for the recipient_rep_code field.
	 * @var        int
	 */
	protected $recipient_rep_code;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        PrivacyNodeType
	 */
	protected $aPrivacyNodeTypeRelatedByOwnerTypeId;

	/**
	 * @var        EmailLayout
	 */
	protected $aEmailLayout;

	/**
	 * @var        PrivacyNodeType
	 */
	protected $aPrivacyNodeTypeRelatedByObjectTypeId;

	/**
	 * @var        array AnnouncementI18n[] Collection to store aggregation of AnnouncementI18n objects.
	 */
	protected $collAnnouncementI18ns;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAnnouncementI18ns.
	 */
	private $lastAnnouncementI18nCriteria = null;

	/**
	 * @var        array AnnRecipient[] Collection to store aggregation of AnnRecipient objects.
	 */
	protected $collAnnRecipients;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAnnRecipients.
	 */
	private $lastAnnRecipientCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

  /**
   * The value for the culture field.
   * @var string
   */
  protected $culture;

	/**
	 * Initializes internal state of BaseAnnouncement object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->guid = 'sys_guid()';
		$this->layout_id = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [guid] column value.
	 * 
	 * @return     string
	 */
	public function getGuid()
	{
		return $this->guid;
	}

	/**
	 * Get the [owner_id] column value.
	 * 
	 * @return     int
	 */
	public function getOwnerId()
	{
		return $this->owner_id;
	}

	/**
	 * Get the [owner_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getOwnerTypeId()
	{
		return $this->owner_type_id;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [channel_id] column value.
	 * 
	 * @return     int
	 */
	public function getChannelId()
	{
		return $this->channel_id;
	}

	/**
	 * Get the [layout_id] column value.
	 * 
	 * @return     int
	 */
	public function getLayoutId()
	{
		return $this->layout_id;
	}

	/**
	 * Get the [delivery_mode_id] column value.
	 * 
	 * @return     int
	 */
	public function getDeliveryModeId()
	{
		return $this->delivery_mode_id;
	}

	/**
	 * Get the [optionally formatted] temporal [deliver_from] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeliverFrom($format = 'Y-M-D H:i:s')
	{
		if ($this->deliver_from === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->deliver_from);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deliver_from, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [deliver_by] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeliverBy($format = 'Y-M-D H:i:s')
	{
		if ($this->deliver_by === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->deliver_by);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deliver_by, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [object_id] column value.
	 * 
	 * @return     int
	 */
	public function getObjectId()
	{
		return $this->object_id;
	}

	/**
	 * Get the [object_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getObjectTypeId()
	{
		return $this->object_type_id;
	}

	/**
	 * Get the [content_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getContentTypeId()
	{
		return $this->content_type_id;
	}

	/**
	 * Get the [recipient_rep_code] column value.
	 * 
	 * @return     int
	 */
	public function getRecipientRepCode()
	{
		return $this->recipient_rep_code;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-M-D H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-M-D H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [guid] column.
	 * 
	 * @param      string $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setGuid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->guid !== $v || $v === 'sys_guid()') {
			$this->guid = $v;
			$this->modifiedColumns[] = AnnouncementPeer::GUID;
		}

		return $this;
	} // setGuid()

	/**
	 * Set the value of [owner_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setOwnerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->owner_id !== $v) {
			$this->owner_id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::OWNER_ID;
		}

		return $this;
	} // setOwnerId()

	/**
	 * Set the value of [owner_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setOwnerTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->owner_type_id !== $v) {
			$this->owner_type_id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::OWNER_TYPE_ID;
		}

		if ($this->aPrivacyNodeTypeRelatedByOwnerTypeId !== null && $this->aPrivacyNodeTypeRelatedByOwnerTypeId->getId() !== $v) {
			$this->aPrivacyNodeTypeRelatedByOwnerTypeId = null;
		}

		return $this;
	} // setOwnerTypeId()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = AnnouncementPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [channel_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setChannelId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->channel_id !== $v) {
			$this->channel_id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::CHANNEL_ID;
		}

		return $this;
	} // setChannelId()

	/**
	 * Set the value of [layout_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setLayoutId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->layout_id !== $v || $v === 0) {
			$this->layout_id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::LAYOUT_ID;
		}

		if ($this->aEmailLayout !== null && $this->aEmailLayout->getId() !== $v) {
			$this->aEmailLayout = null;
		}

		return $this;
	} // setLayoutId()

	/**
	 * Set the value of [delivery_mode_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setDeliveryModeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->delivery_mode_id !== $v) {
			$this->delivery_mode_id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::DELIVERY_MODE_ID;
		}

		return $this;
	} // setDeliveryModeId()

	/**
	 * Sets the value of [deliver_from] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setDeliverFrom($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->deliver_from !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->deliver_from !== null && $tmpDt = new DateTime($this->deliver_from)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->deliver_from = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AnnouncementPeer::DELIVER_FROM;
			}
		} // if either are not null

		return $this;
	} // setDeliverFrom()

	/**
	 * Sets the value of [deliver_by] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setDeliverBy($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->deliver_by !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->deliver_by !== null && $tmpDt = new DateTime($this->deliver_by)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->deliver_by = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AnnouncementPeer::DELIVER_BY;
			}
		} // if either are not null

		return $this;
	} // setDeliverBy()

	/**
	 * Set the value of [object_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setObjectId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->object_id !== $v) {
			$this->object_id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::OBJECT_ID;
		}

		return $this;
	} // setObjectId()

	/**
	 * Set the value of [object_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setObjectTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->object_type_id !== $v) {
			$this->object_type_id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::OBJECT_TYPE_ID;
		}

		if ($this->aPrivacyNodeTypeRelatedByObjectTypeId !== null && $this->aPrivacyNodeTypeRelatedByObjectTypeId->getId() !== $v) {
			$this->aPrivacyNodeTypeRelatedByObjectTypeId = null;
		}

		return $this;
	} // setObjectTypeId()

	/**
	 * Set the value of [content_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setContentTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->content_type_id !== $v) {
			$this->content_type_id = $v;
			$this->modifiedColumns[] = AnnouncementPeer::CONTENT_TYPE_ID;
		}

		return $this;
	} // setContentTypeId()

	/**
	 * Set the value of [recipient_rep_code] column.
	 * 
	 * @param      int $v new value
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setRecipientRepCode($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->recipient_rep_code !== $v) {
			$this->recipient_rep_code = $v;
			$this->modifiedColumns[] = AnnouncementPeer::RECIPIENT_REP_CODE;
		}

		return $this;
	} // setRecipientRepCode()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AnnouncementPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Announcement The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AnnouncementPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(AnnouncementPeer::GUID,AnnouncementPeer::LAYOUT_ID))) {
				return false;
			}

			if ($this->guid !== 'sys_guid()') {
				return false;
			}

			if ($this->layout_id !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->guid = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->owner_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->owner_type_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->title = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->channel_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->layout_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->delivery_mode_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->deliver_from = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->deliver_by = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->object_id = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->object_type_id = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->content_type_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->recipient_rep_code = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->created_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->updated_at = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = AnnouncementPeer::NUM_COLUMNS - AnnouncementPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Announcement object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPrivacyNodeTypeRelatedByOwnerTypeId !== null && $this->owner_type_id !== $this->aPrivacyNodeTypeRelatedByOwnerTypeId->getId()) {
			$this->aPrivacyNodeTypeRelatedByOwnerTypeId = null;
		}
		if ($this->aEmailLayout !== null && $this->layout_id !== $this->aEmailLayout->getId()) {
			$this->aEmailLayout = null;
		}
		if ($this->aPrivacyNodeTypeRelatedByObjectTypeId !== null && $this->object_type_id !== $this->aPrivacyNodeTypeRelatedByObjectTypeId->getId()) {
			$this->aPrivacyNodeTypeRelatedByObjectTypeId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AnnouncementPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AnnouncementPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPrivacyNodeTypeRelatedByOwnerTypeId = null;
			$this->aEmailLayout = null;
			$this->aPrivacyNodeTypeRelatedByObjectTypeId = null;
			$this->collAnnouncementI18ns = null;
			$this->lastAnnouncementI18nCriteria = null;

			$this->collAnnRecipients = null;
			$this->lastAnnRecipientCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAnnouncement:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AnnouncementPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			AnnouncementPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseAnnouncement:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAnnouncement:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(AnnouncementPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(AnnouncementPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AnnouncementPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseAnnouncement:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			AnnouncementPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPrivacyNodeTypeRelatedByOwnerTypeId !== null) {
				if ($this->aPrivacyNodeTypeRelatedByOwnerTypeId->isModified() || ($this->aPrivacyNodeTypeRelatedByOwnerTypeId->getCulture() && $this->aPrivacyNodeTypeRelatedByOwnerTypeId->getCurrentPrivacyNodeTypeI18n()->isModified()) || $this->aPrivacyNodeTypeRelatedByOwnerTypeId->isNew()) {
					$affectedRows += $this->aPrivacyNodeTypeRelatedByOwnerTypeId->save($con);
				}
				$this->setPrivacyNodeTypeRelatedByOwnerTypeId($this->aPrivacyNodeTypeRelatedByOwnerTypeId);
			}

			if ($this->aEmailLayout !== null) {
				if ($this->aEmailLayout->isModified() || ($this->aEmailLayout->getCulture() && $this->aEmailLayout->getCurrentEmailLayoutI18n()->isModified()) || $this->aEmailLayout->isNew()) {
					$affectedRows += $this->aEmailLayout->save($con);
				}
				$this->setEmailLayout($this->aEmailLayout);
			}

			if ($this->aPrivacyNodeTypeRelatedByObjectTypeId !== null) {
				if ($this->aPrivacyNodeTypeRelatedByObjectTypeId->isModified() || ($this->aPrivacyNodeTypeRelatedByObjectTypeId->getCulture() && $this->aPrivacyNodeTypeRelatedByObjectTypeId->getCurrentPrivacyNodeTypeI18n()->isModified()) || $this->aPrivacyNodeTypeRelatedByObjectTypeId->isNew()) {
					$affectedRows += $this->aPrivacyNodeTypeRelatedByObjectTypeId->save($con);
				}
				$this->setPrivacyNodeTypeRelatedByObjectTypeId($this->aPrivacyNodeTypeRelatedByObjectTypeId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AnnouncementPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AnnouncementPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AnnouncementPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAnnouncementI18ns !== null) {
				foreach ($this->collAnnouncementI18ns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collAnnRecipients !== null) {
				foreach ($this->collAnnRecipients as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPrivacyNodeTypeRelatedByOwnerTypeId !== null) {
				if (!$this->aPrivacyNodeTypeRelatedByOwnerTypeId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPrivacyNodeTypeRelatedByOwnerTypeId->getValidationFailures());
				}
			}

			if ($this->aEmailLayout !== null) {
				if (!$this->aEmailLayout->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEmailLayout->getValidationFailures());
				}
			}

			if ($this->aPrivacyNodeTypeRelatedByObjectTypeId !== null) {
				if (!$this->aPrivacyNodeTypeRelatedByObjectTypeId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPrivacyNodeTypeRelatedByObjectTypeId->getValidationFailures());
				}
			}


			if (($retval = AnnouncementPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAnnouncementI18ns !== null) {
					foreach ($this->collAnnouncementI18ns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collAnnRecipients !== null) {
					foreach ($this->collAnnRecipients as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AnnouncementPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getGuid();
				break;
			case 2:
				return $this->getOwnerId();
				break;
			case 3:
				return $this->getOwnerTypeId();
				break;
			case 4:
				return $this->getTitle();
				break;
			case 5:
				return $this->getChannelId();
				break;
			case 6:
				return $this->getLayoutId();
				break;
			case 7:
				return $this->getDeliveryModeId();
				break;
			case 8:
				return $this->getDeliverFrom();
				break;
			case 9:
				return $this->getDeliverBy();
				break;
			case 10:
				return $this->getObjectId();
				break;
			case 11:
				return $this->getObjectTypeId();
				break;
			case 12:
				return $this->getContentTypeId();
				break;
			case 13:
				return $this->getRecipientRepCode();
				break;
			case 14:
				return $this->getCreatedAt();
				break;
			case 15:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AnnouncementPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getGuid(),
			$keys[2] => $this->getOwnerId(),
			$keys[3] => $this->getOwnerTypeId(),
			$keys[4] => $this->getTitle(),
			$keys[5] => $this->getChannelId(),
			$keys[6] => $this->getLayoutId(),
			$keys[7] => $this->getDeliveryModeId(),
			$keys[8] => $this->getDeliverFrom(),
			$keys[9] => $this->getDeliverBy(),
			$keys[10] => $this->getObjectId(),
			$keys[11] => $this->getObjectTypeId(),
			$keys[12] => $this->getContentTypeId(),
			$keys[13] => $this->getRecipientRepCode(),
			$keys[14] => $this->getCreatedAt(),
			$keys[15] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AnnouncementPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setGuid($value);
				break;
			case 2:
				$this->setOwnerId($value);
				break;
			case 3:
				$this->setOwnerTypeId($value);
				break;
			case 4:
				$this->setTitle($value);
				break;
			case 5:
				$this->setChannelId($value);
				break;
			case 6:
				$this->setLayoutId($value);
				break;
			case 7:
				$this->setDeliveryModeId($value);
				break;
			case 8:
				$this->setDeliverFrom($value);
				break;
			case 9:
				$this->setDeliverBy($value);
				break;
			case 10:
				$this->setObjectId($value);
				break;
			case 11:
				$this->setObjectTypeId($value);
				break;
			case 12:
				$this->setContentTypeId($value);
				break;
			case 13:
				$this->setRecipientRepCode($value);
				break;
			case 14:
				$this->setCreatedAt($value);
				break;
			case 15:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AnnouncementPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setGuid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setOwnerId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setOwnerTypeId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTitle($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setChannelId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setLayoutId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDeliveryModeId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDeliverFrom($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDeliverBy($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setObjectId($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setObjectTypeId($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setContentTypeId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setRecipientRepCode($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCreatedAt($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setUpdatedAt($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AnnouncementPeer::DATABASE_NAME);

		if ($this->isColumnModified(AnnouncementPeer::ID)) $criteria->add(AnnouncementPeer::ID, $this->id);
		if ($this->isColumnModified(AnnouncementPeer::GUID)) $criteria->add(AnnouncementPeer::GUID, $this->guid);
		if ($this->isColumnModified(AnnouncementPeer::OWNER_ID)) $criteria->add(AnnouncementPeer::OWNER_ID, $this->owner_id);
		if ($this->isColumnModified(AnnouncementPeer::OWNER_TYPE_ID)) $criteria->add(AnnouncementPeer::OWNER_TYPE_ID, $this->owner_type_id);
		if ($this->isColumnModified(AnnouncementPeer::TITLE)) $criteria->add(AnnouncementPeer::TITLE, $this->title);
		if ($this->isColumnModified(AnnouncementPeer::CHANNEL_ID)) $criteria->add(AnnouncementPeer::CHANNEL_ID, $this->channel_id);
		if ($this->isColumnModified(AnnouncementPeer::LAYOUT_ID)) $criteria->add(AnnouncementPeer::LAYOUT_ID, $this->layout_id);
		if ($this->isColumnModified(AnnouncementPeer::DELIVERY_MODE_ID)) $criteria->add(AnnouncementPeer::DELIVERY_MODE_ID, $this->delivery_mode_id);
		if ($this->isColumnModified(AnnouncementPeer::DELIVER_FROM)) $criteria->add(AnnouncementPeer::DELIVER_FROM, $this->deliver_from);
		if ($this->isColumnModified(AnnouncementPeer::DELIVER_BY)) $criteria->add(AnnouncementPeer::DELIVER_BY, $this->deliver_by);
		if ($this->isColumnModified(AnnouncementPeer::OBJECT_ID)) $criteria->add(AnnouncementPeer::OBJECT_ID, $this->object_id);
		if ($this->isColumnModified(AnnouncementPeer::OBJECT_TYPE_ID)) $criteria->add(AnnouncementPeer::OBJECT_TYPE_ID, $this->object_type_id);
		if ($this->isColumnModified(AnnouncementPeer::CONTENT_TYPE_ID)) $criteria->add(AnnouncementPeer::CONTENT_TYPE_ID, $this->content_type_id);
		if ($this->isColumnModified(AnnouncementPeer::RECIPIENT_REP_CODE)) $criteria->add(AnnouncementPeer::RECIPIENT_REP_CODE, $this->recipient_rep_code);
		if ($this->isColumnModified(AnnouncementPeer::CREATED_AT)) $criteria->add(AnnouncementPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(AnnouncementPeer::UPDATED_AT)) $criteria->add(AnnouncementPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AnnouncementPeer::DATABASE_NAME);

		$criteria->add(AnnouncementPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Announcement (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setGuid($this->guid);

		$copyObj->setOwnerId($this->owner_id);

		$copyObj->setOwnerTypeId($this->owner_type_id);

		$copyObj->setTitle($this->title);

		$copyObj->setChannelId($this->channel_id);

		$copyObj->setLayoutId($this->layout_id);

		$copyObj->setDeliveryModeId($this->delivery_mode_id);

		$copyObj->setDeliverFrom($this->deliver_from);

		$copyObj->setDeliverBy($this->deliver_by);

		$copyObj->setObjectId($this->object_id);

		$copyObj->setObjectTypeId($this->object_type_id);

		$copyObj->setContentTypeId($this->content_type_id);

		$copyObj->setRecipientRepCode($this->recipient_rep_code);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAnnouncementI18ns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAnnouncementI18n($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getAnnRecipients() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAnnRecipient($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Announcement Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AnnouncementPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AnnouncementPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a PrivacyNodeType object.
	 *
	 * @param      PrivacyNodeType $v
	 * @return     Announcement The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPrivacyNodeTypeRelatedByOwnerTypeId(PrivacyNodeType $v = null)
	{
		if ($v === null) {
			$this->setOwnerTypeId(NULL);
		} else {
			$this->setOwnerTypeId($v->getId());
		}

		$this->aPrivacyNodeTypeRelatedByOwnerTypeId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the PrivacyNodeType object, it will not be re-added.
		if ($v !== null) {
			$v->addAnnouncementRelatedByOwnerTypeId($this);
		}

		return $this;
	}


	/**
	 * Get the associated PrivacyNodeType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     PrivacyNodeType The associated PrivacyNodeType object.
	 * @throws     PropelException
	 */
	public function getPrivacyNodeTypeRelatedByOwnerTypeId(PropelPDO $con = null)
	{
		if ($this->aPrivacyNodeTypeRelatedByOwnerTypeId === null && ($this->owner_type_id !== null)) {
			$c = new Criteria(PrivacyNodeTypePeer::DATABASE_NAME);
			$c->add(PrivacyNodeTypePeer::ID, $this->owner_type_id);
			$this->aPrivacyNodeTypeRelatedByOwnerTypeId = PrivacyNodeTypePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPrivacyNodeTypeRelatedByOwnerTypeId->addAnnouncementsRelatedByOwnerTypeId($this);
			 */
		}
		return $this->aPrivacyNodeTypeRelatedByOwnerTypeId;
	}

	/**
	 * Declares an association between this object and a EmailLayout object.
	 *
	 * @param      EmailLayout $v
	 * @return     Announcement The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEmailLayout(EmailLayout $v = null)
	{
		if ($v === null) {
			$this->setLayoutId(0);
		} else {
			$this->setLayoutId($v->getId());
		}

		$this->aEmailLayout = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the EmailLayout object, it will not be re-added.
		if ($v !== null) {
			$v->addAnnouncement($this);
		}

		return $this;
	}


	/**
	 * Get the associated EmailLayout object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     EmailLayout The associated EmailLayout object.
	 * @throws     PropelException
	 */
	public function getEmailLayout(PropelPDO $con = null)
	{
		if ($this->aEmailLayout === null && ($this->layout_id !== null)) {
			$c = new Criteria(EmailLayoutPeer::DATABASE_NAME);
			$c->add(EmailLayoutPeer::ID, $this->layout_id);
			$this->aEmailLayout = EmailLayoutPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEmailLayout->addAnnouncements($this);
			 */
		}
		return $this->aEmailLayout;
	}

	/**
	 * Declares an association between this object and a PrivacyNodeType object.
	 *
	 * @param      PrivacyNodeType $v
	 * @return     Announcement The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPrivacyNodeTypeRelatedByObjectTypeId(PrivacyNodeType $v = null)
	{
		if ($v === null) {
			$this->setObjectTypeId(NULL);
		} else {
			$this->setObjectTypeId($v->getId());
		}

		$this->aPrivacyNodeTypeRelatedByObjectTypeId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the PrivacyNodeType object, it will not be re-added.
		if ($v !== null) {
			$v->addAnnouncementRelatedByObjectTypeId($this);
		}

		return $this;
	}


	/**
	 * Get the associated PrivacyNodeType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     PrivacyNodeType The associated PrivacyNodeType object.
	 * @throws     PropelException
	 */
	public function getPrivacyNodeTypeRelatedByObjectTypeId(PropelPDO $con = null)
	{
		if ($this->aPrivacyNodeTypeRelatedByObjectTypeId === null && ($this->object_type_id !== null)) {
			$c = new Criteria(PrivacyNodeTypePeer::DATABASE_NAME);
			$c->add(PrivacyNodeTypePeer::ID, $this->object_type_id);
			$this->aPrivacyNodeTypeRelatedByObjectTypeId = PrivacyNodeTypePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPrivacyNodeTypeRelatedByObjectTypeId->addAnnouncementsRelatedByObjectTypeId($this);
			 */
		}
		return $this->aPrivacyNodeTypeRelatedByObjectTypeId;
	}

	/**
	 * Clears out the collAnnouncementI18ns collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAnnouncementI18ns()
	 */
	public function clearAnnouncementI18ns()
	{
		$this->collAnnouncementI18ns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAnnouncementI18ns collection (array).
	 *
	 * By default this just sets the collAnnouncementI18ns collection to an empty array (like clearcollAnnouncementI18ns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAnnouncementI18ns()
	{
		$this->collAnnouncementI18ns = array();
	}

	/**
	 * Gets an array of AnnouncementI18n objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Announcement has previously been saved, it will retrieve
	 * related AnnouncementI18ns from storage. If this Announcement is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AnnouncementI18n[]
	 * @throws     PropelException
	 */
	public function getAnnouncementI18ns($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AnnouncementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAnnouncementI18ns === null) {
			if ($this->isNew()) {
			   $this->collAnnouncementI18ns = array();
			} else {

				$criteria->add(AnnouncementI18nPeer::ID, $this->id);

				AnnouncementI18nPeer::addSelectColumns($criteria);
				$this->collAnnouncementI18ns = AnnouncementI18nPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AnnouncementI18nPeer::ID, $this->id);

				AnnouncementI18nPeer::addSelectColumns($criteria);
				if (!isset($this->lastAnnouncementI18nCriteria) || !$this->lastAnnouncementI18nCriteria->equals($criteria)) {
					$this->collAnnouncementI18ns = AnnouncementI18nPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAnnouncementI18nCriteria = $criteria;
		return $this->collAnnouncementI18ns;
	}

	/**
	 * Returns the number of related AnnouncementI18n objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AnnouncementI18n objects.
	 * @throws     PropelException
	 */
	public function countAnnouncementI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AnnouncementPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAnnouncementI18ns === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AnnouncementI18nPeer::ID, $this->id);

				$count = AnnouncementI18nPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AnnouncementI18nPeer::ID, $this->id);

				if (!isset($this->lastAnnouncementI18nCriteria) || !$this->lastAnnouncementI18nCriteria->equals($criteria)) {
					$count = AnnouncementI18nPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAnnouncementI18ns);
				}
			} else {
				$count = count($this->collAnnouncementI18ns);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AnnouncementI18n object to this object
	 * through the AnnouncementI18n foreign key attribute.
	 *
	 * @param      AnnouncementI18n $l AnnouncementI18n
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAnnouncementI18n(AnnouncementI18n $l)
	{
		if ($this->collAnnouncementI18ns === null) {
			$this->initAnnouncementI18ns();
		}
		if (!in_array($l, $this->collAnnouncementI18ns, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAnnouncementI18ns, $l);
			$l->setAnnouncement($this);
		}
	}

	/**
	 * Clears out the collAnnRecipients collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAnnRecipients()
	 */
	public function clearAnnRecipients()
	{
		$this->collAnnRecipients = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAnnRecipients collection (array).
	 *
	 * By default this just sets the collAnnRecipients collection to an empty array (like clearcollAnnRecipients());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAnnRecipients()
	{
		$this->collAnnRecipients = array();
	}

	/**
	 * Gets an array of AnnRecipient objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Announcement has previously been saved, it will retrieve
	 * related AnnRecipients from storage. If this Announcement is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AnnRecipient[]
	 * @throws     PropelException
	 */
	public function getAnnRecipients($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AnnouncementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAnnRecipients === null) {
			if ($this->isNew()) {
			   $this->collAnnRecipients = array();
			} else {

				$criteria->add(AnnRecipientPeer::ANN_ID, $this->id);

				AnnRecipientPeer::addSelectColumns($criteria);
				$this->collAnnRecipients = AnnRecipientPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AnnRecipientPeer::ANN_ID, $this->id);

				AnnRecipientPeer::addSelectColumns($criteria);
				if (!isset($this->lastAnnRecipientCriteria) || !$this->lastAnnRecipientCriteria->equals($criteria)) {
					$this->collAnnRecipients = AnnRecipientPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAnnRecipientCriteria = $criteria;
		return $this->collAnnRecipients;
	}

	/**
	 * Returns the number of related AnnRecipient objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AnnRecipient objects.
	 * @throws     PropelException
	 */
	public function countAnnRecipients(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AnnouncementPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAnnRecipients === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AnnRecipientPeer::ANN_ID, $this->id);

				$count = AnnRecipientPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AnnRecipientPeer::ANN_ID, $this->id);

				if (!isset($this->lastAnnRecipientCriteria) || !$this->lastAnnRecipientCriteria->equals($criteria)) {
					$count = AnnRecipientPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAnnRecipients);
				}
			} else {
				$count = count($this->collAnnRecipients);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AnnRecipient object to this object
	 * through the AnnRecipient foreign key attribute.
	 *
	 * @param      AnnRecipient $l AnnRecipient
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAnnRecipient(AnnRecipient $l)
	{
		if ($this->collAnnRecipients === null) {
			$this->initAnnRecipients();
		}
		if (!in_array($l, $this->collAnnRecipients, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAnnRecipients, $l);
			$l->setAnnouncement($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Announcement is new, it will return
	 * an empty collection; or if this Announcement has previously
	 * been saved, it will retrieve related AnnRecipients from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Announcement.
	 */
	public function getAnnRecipientsJoinPrivacyNodeType($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AnnouncementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAnnRecipients === null) {
			if ($this->isNew()) {
				$this->collAnnRecipients = array();
			} else {

				$criteria->add(AnnRecipientPeer::ANN_ID, $this->id);

				$this->collAnnRecipients = AnnRecipientPeer::doSelectJoinPrivacyNodeType($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AnnRecipientPeer::ANN_ID, $this->id);

			if (!isset($this->lastAnnRecipientCriteria) || !$this->lastAnnRecipientCriteria->equals($criteria)) {
				$this->collAnnRecipients = AnnRecipientPeer::doSelectJoinPrivacyNodeType($criteria, $con, $join_behavior);
			}
		}
		$this->lastAnnRecipientCriteria = $criteria;

		return $this->collAnnRecipients;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAnnouncementI18ns) {
				foreach ((array) $this->collAnnouncementI18ns as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collAnnRecipients) {
				foreach ((array) $this->collAnnRecipients as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAnnouncementI18ns = null;
		$this->collAnnRecipients = null;
			$this->aPrivacyNodeTypeRelatedByOwnerTypeId = null;
			$this->aEmailLayout = null;
			$this->aPrivacyNodeTypeRelatedByObjectTypeId = null;
	}


  /**
   * Returns the culture.
   *
   * @return string The culture
   */
  public function getCulture()
  {
    return $this->culture;
  }

  /**
   * Sets the culture.
   *
   * @param string $culture The culture to set
   *
   * @return void
   */
  public function setCulture($culture)
  {
    $this->culture = $culture;
  }

  public function getDisplayTitle($culture = null)
  {
    return $this->getCurrentAnnouncementI18n($culture)->getDisplayTitle();
  }

  public function setDisplayTitle($value, $culture = null)
  {
    $this->getCurrentAnnouncementI18n($culture)->setDisplayTitle($value);
  }

  public function getData($culture = null)
  {
    return $this->getCurrentAnnouncementI18n($culture)->getData();
  }

  public function setData($value, $culture = null)
  {
    $this->getCurrentAnnouncementI18n($culture)->setData($value);
  }

  public function getSmsMessage($culture = null)
  {
    return $this->getCurrentAnnouncementI18n($culture)->getSmsMessage();
  }

  public function setSmsMessage($value, $culture = null)
  {
    $this->getCurrentAnnouncementI18n($culture)->setSmsMessage($value);
  }

  protected $current_i18n = array();

  public function getCurrentAnnouncementI18n($culture = null)
  {
    if (is_null($culture))
    {
      $culture = is_null($this->culture) ? sfPropel::getDefaultCulture() : $this->culture;
    }

    if (!isset($this->current_i18n[$culture]))
    {
      $obj = AnnouncementI18nPeer::retrieveByPK($this->getId(), $culture);
      if ($obj)
      {
        $this->setAnnouncementI18nForCulture($obj, $culture);
      }
      else
      {
        $this->setAnnouncementI18nForCulture(new AnnouncementI18n(), $culture);
        $this->current_i18n[$culture]->setCulture($culture);
      }
    }

    return $this->current_i18n[$culture];
  }

  public function setAnnouncementI18nForCulture($object, $culture)
  {
    $this->current_i18n[$culture] = $object;
    $this->addAnnouncementI18n($object);
  }


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseAnnouncement:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseAnnouncement::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseAnnouncement
