<?php

/**
 * Base class that represents a row from the 'EMT_PRODUCT_ATTR_DEF' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 03/07/12 22:24:29
 *
 * @package    lib.model.om
 */
abstract class BaseProductAttrDef extends BaseObject  implements Persistent {


  const PEER = 'ProductAttrDefPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ProductAttrDefPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the category_id field.
	 * @var        int
	 */
	protected $category_id;

	/**
	 * The value for the sequence_no field.
	 * @var        int
	 */
	protected $sequence_no;

	/**
	 * The value for the active field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $active;

	/**
	 * @var        ProductCategory
	 */
	protected $aProductCategory;

	/**
	 * @var        array ProductAttrDefI18n[] Collection to store aggregation of ProductAttrDefI18n objects.
	 */
	protected $collProductAttrDefI18ns;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProductAttrDefI18ns.
	 */
	private $lastProductAttrDefI18nCriteria = null;

	/**
	 * @var        array ProductAttrOption[] Collection to store aggregation of ProductAttrOption objects.
	 */
	protected $collProductAttrOptions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProductAttrOptions.
	 */
	private $lastProductAttrOptionCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

  /**
   * The value for the culture field.
   * @var string
   */
  protected $culture;

	/**
	 * Initializes internal state of BaseProductAttrDef object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->active = true;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [category_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryId()
	{
		return $this->category_id;
	}

	/**
	 * Get the [sequence_no] column value.
	 * 
	 * @return     int
	 */
	public function getSequenceNo()
	{
		return $this->sequence_no;
	}

	/**
	 * Get the [active] column value.
	 * 
	 * @return     boolean
	 */
	public function getActive()
	{
		return $this->active;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     ProductAttrDef The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ProductAttrDefPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [category_id] column.
	 * 
	 * @param      int $v new value
	 * @return     ProductAttrDef The current object (for fluent API support)
	 */
	public function setCategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_id !== $v) {
			$this->category_id = $v;
			$this->modifiedColumns[] = ProductAttrDefPeer::CATEGORY_ID;
		}

		if ($this->aProductCategory !== null && $this->aProductCategory->getId() !== $v) {
			$this->aProductCategory = null;
		}

		return $this;
	} // setCategoryId()

	/**
	 * Set the value of [sequence_no] column.
	 * 
	 * @param      int $v new value
	 * @return     ProductAttrDef The current object (for fluent API support)
	 */
	public function setSequenceNo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->sequence_no !== $v) {
			$this->sequence_no = $v;
			$this->modifiedColumns[] = ProductAttrDefPeer::SEQUENCE_NO;
		}

		return $this;
	} // setSequenceNo()

	/**
	 * Set the value of [active] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ProductAttrDef The current object (for fluent API support)
	 */
	public function setActive($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->active !== $v || $v === true) {
			$this->active = $v;
			$this->modifiedColumns[] = ProductAttrDefPeer::ACTIVE;
		}

		return $this;
	} // setActive()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(ProductAttrDefPeer::ACTIVE))) {
				return false;
			}

			if ($this->active !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->category_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->sequence_no = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->active = ($row[$startcol + 3] !== null) ? (boolean) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = ProductAttrDefPeer::NUM_COLUMNS - ProductAttrDefPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating ProductAttrDef object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aProductCategory !== null && $this->category_id !== $this->aProductCategory->getId()) {
			$this->aProductCategory = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProductAttrDefPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ProductAttrDefPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aProductCategory = null;
			$this->collProductAttrDefI18ns = null;
			$this->lastProductAttrDefI18nCriteria = null;

			$this->collProductAttrOptions = null;
			$this->lastProductAttrOptionCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProductAttrDef:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProductAttrDefPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ProductAttrDefPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseProductAttrDef:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseProductAttrDef:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProductAttrDefPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseProductAttrDef:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ProductAttrDefPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aProductCategory !== null) {
				if ($this->aProductCategory->isModified() || ($this->aProductCategory->getCulture() && $this->aProductCategory->getCurrentProductCategoryI18n()->isModified()) || $this->aProductCategory->isNew()) {
					$affectedRows += $this->aProductCategory->save($con);
				}
				$this->setProductCategory($this->aProductCategory);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ProductAttrDefPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ProductAttrDefPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ProductAttrDefPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collProductAttrDefI18ns !== null) {
				foreach ($this->collProductAttrDefI18ns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collProductAttrOptions !== null) {
				foreach ($this->collProductAttrOptions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aProductCategory !== null) {
				if (!$this->aProductCategory->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProductCategory->getValidationFailures());
				}
			}


			if (($retval = ProductAttrDefPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collProductAttrDefI18ns !== null) {
					foreach ($this->collProductAttrDefI18ns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collProductAttrOptions !== null) {
					foreach ($this->collProductAttrOptions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProductAttrDefPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCategoryId();
				break;
			case 2:
				return $this->getSequenceNo();
				break;
			case 3:
				return $this->getActive();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ProductAttrDefPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCategoryId(),
			$keys[2] => $this->getSequenceNo(),
			$keys[3] => $this->getActive(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProductAttrDefPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCategoryId($value);
				break;
			case 2:
				$this->setSequenceNo($value);
				break;
			case 3:
				$this->setActive($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ProductAttrDefPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCategoryId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setSequenceNo($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setActive($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ProductAttrDefPeer::DATABASE_NAME);

		if ($this->isColumnModified(ProductAttrDefPeer::ID)) $criteria->add(ProductAttrDefPeer::ID, $this->id);
		if ($this->isColumnModified(ProductAttrDefPeer::CATEGORY_ID)) $criteria->add(ProductAttrDefPeer::CATEGORY_ID, $this->category_id);
		if ($this->isColumnModified(ProductAttrDefPeer::SEQUENCE_NO)) $criteria->add(ProductAttrDefPeer::SEQUENCE_NO, $this->sequence_no);
		if ($this->isColumnModified(ProductAttrDefPeer::ACTIVE)) $criteria->add(ProductAttrDefPeer::ACTIVE, $this->active);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ProductAttrDefPeer::DATABASE_NAME);

		$criteria->add(ProductAttrDefPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of ProductAttrDef (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCategoryId($this->category_id);

		$copyObj->setSequenceNo($this->sequence_no);

		$copyObj->setActive($this->active);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getProductAttrDefI18ns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProductAttrDefI18n($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getProductAttrOptions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProductAttrOption($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     ProductAttrDef Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ProductAttrDefPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ProductAttrDefPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a ProductCategory object.
	 *
	 * @param      ProductCategory $v
	 * @return     ProductAttrDef The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProductCategory(ProductCategory $v = null)
	{
		if ($v === null) {
			$this->setCategoryId(NULL);
		} else {
			$this->setCategoryId($v->getId());
		}

		$this->aProductCategory = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ProductCategory object, it will not be re-added.
		if ($v !== null) {
			$v->addProductAttrDef($this);
		}

		return $this;
	}


	/**
	 * Get the associated ProductCategory object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ProductCategory The associated ProductCategory object.
	 * @throws     PropelException
	 */
	public function getProductCategory(PropelPDO $con = null)
	{
		if ($this->aProductCategory === null && ($this->category_id !== null)) {
			$c = new Criteria(ProductCategoryPeer::DATABASE_NAME);
			$c->add(ProductCategoryPeer::ID, $this->category_id);
			$this->aProductCategory = ProductCategoryPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProductCategory->addProductAttrDefs($this);
			 */
		}
		return $this->aProductCategory;
	}

	/**
	 * Clears out the collProductAttrDefI18ns collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProductAttrDefI18ns()
	 */
	public function clearProductAttrDefI18ns()
	{
		$this->collProductAttrDefI18ns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProductAttrDefI18ns collection (array).
	 *
	 * By default this just sets the collProductAttrDefI18ns collection to an empty array (like clearcollProductAttrDefI18ns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProductAttrDefI18ns()
	{
		$this->collProductAttrDefI18ns = array();
	}

	/**
	 * Gets an array of ProductAttrDefI18n objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this ProductAttrDef has previously been saved, it will retrieve
	 * related ProductAttrDefI18ns from storage. If this ProductAttrDef is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProductAttrDefI18n[]
	 * @throws     PropelException
	 */
	public function getProductAttrDefI18ns($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductAttrDefPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductAttrDefI18ns === null) {
			if ($this->isNew()) {
			   $this->collProductAttrDefI18ns = array();
			} else {

				$criteria->add(ProductAttrDefI18nPeer::ID, $this->id);

				ProductAttrDefI18nPeer::addSelectColumns($criteria);
				$this->collProductAttrDefI18ns = ProductAttrDefI18nPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProductAttrDefI18nPeer::ID, $this->id);

				ProductAttrDefI18nPeer::addSelectColumns($criteria);
				if (!isset($this->lastProductAttrDefI18nCriteria) || !$this->lastProductAttrDefI18nCriteria->equals($criteria)) {
					$this->collProductAttrDefI18ns = ProductAttrDefI18nPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProductAttrDefI18nCriteria = $criteria;
		return $this->collProductAttrDefI18ns;
	}

	/**
	 * Returns the number of related ProductAttrDefI18n objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProductAttrDefI18n objects.
	 * @throws     PropelException
	 */
	public function countProductAttrDefI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductAttrDefPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProductAttrDefI18ns === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProductAttrDefI18nPeer::ID, $this->id);

				$count = ProductAttrDefI18nPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProductAttrDefI18nPeer::ID, $this->id);

				if (!isset($this->lastProductAttrDefI18nCriteria) || !$this->lastProductAttrDefI18nCriteria->equals($criteria)) {
					$count = ProductAttrDefI18nPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProductAttrDefI18ns);
				}
			} else {
				$count = count($this->collProductAttrDefI18ns);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProductAttrDefI18n object to this object
	 * through the ProductAttrDefI18n foreign key attribute.
	 *
	 * @param      ProductAttrDefI18n $l ProductAttrDefI18n
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProductAttrDefI18n(ProductAttrDefI18n $l)
	{
		if ($this->collProductAttrDefI18ns === null) {
			$this->initProductAttrDefI18ns();
		}
		if (!in_array($l, $this->collProductAttrDefI18ns, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProductAttrDefI18ns, $l);
			$l->setProductAttrDef($this);
		}
	}

	/**
	 * Clears out the collProductAttrOptions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProductAttrOptions()
	 */
	public function clearProductAttrOptions()
	{
		$this->collProductAttrOptions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProductAttrOptions collection (array).
	 *
	 * By default this just sets the collProductAttrOptions collection to an empty array (like clearcollProductAttrOptions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProductAttrOptions()
	{
		$this->collProductAttrOptions = array();
	}

	/**
	 * Gets an array of ProductAttrOption objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this ProductAttrDef has previously been saved, it will retrieve
	 * related ProductAttrOptions from storage. If this ProductAttrDef is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProductAttrOption[]
	 * @throws     PropelException
	 */
	public function getProductAttrOptions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductAttrDefPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductAttrOptions === null) {
			if ($this->isNew()) {
			   $this->collProductAttrOptions = array();
			} else {

				$criteria->add(ProductAttrOptionPeer::ATTRIBUTE_ID, $this->id);

				ProductAttrOptionPeer::addSelectColumns($criteria);
				$this->collProductAttrOptions = ProductAttrOptionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProductAttrOptionPeer::ATTRIBUTE_ID, $this->id);

				ProductAttrOptionPeer::addSelectColumns($criteria);
				if (!isset($this->lastProductAttrOptionCriteria) || !$this->lastProductAttrOptionCriteria->equals($criteria)) {
					$this->collProductAttrOptions = ProductAttrOptionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProductAttrOptionCriteria = $criteria;
		return $this->collProductAttrOptions;
	}

	/**
	 * Returns the number of related ProductAttrOption objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProductAttrOption objects.
	 * @throws     PropelException
	 */
	public function countProductAttrOptions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProductAttrDefPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProductAttrOptions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProductAttrOptionPeer::ATTRIBUTE_ID, $this->id);

				$count = ProductAttrOptionPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProductAttrOptionPeer::ATTRIBUTE_ID, $this->id);

				if (!isset($this->lastProductAttrOptionCriteria) || !$this->lastProductAttrOptionCriteria->equals($criteria)) {
					$count = ProductAttrOptionPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProductAttrOptions);
				}
			} else {
				$count = count($this->collProductAttrOptions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProductAttrOption object to this object
	 * through the ProductAttrOption foreign key attribute.
	 *
	 * @param      ProductAttrOption $l ProductAttrOption
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProductAttrOption(ProductAttrOption $l)
	{
		if ($this->collProductAttrOptions === null) {
			$this->initProductAttrOptions();
		}
		if (!in_array($l, $this->collProductAttrOptions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProductAttrOptions, $l);
			$l->setProductAttrDef($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collProductAttrDefI18ns) {
				foreach ((array) $this->collProductAttrDefI18ns as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collProductAttrOptions) {
				foreach ((array) $this->collProductAttrOptions as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collProductAttrDefI18ns = null;
		$this->collProductAttrOptions = null;
			$this->aProductCategory = null;
	}


  /**
   * Returns the culture.
   *
   * @return string The culture
   */
  public function getCulture()
  {
    return $this->culture;
  }

  /**
   * Sets the culture.
   *
   * @param string $culture The culture to set
   *
   * @return void
   */
  public function setCulture($culture)
  {
    $this->culture = $culture;
  }

  public function getName($culture = null)
  {
    return $this->getCurrentProductAttrDefI18n($culture)->getName();
  }

  public function setName($value, $culture = null)
  {
    $this->getCurrentProductAttrDefI18n($culture)->setName($value);
  }

  protected $current_i18n = array();

  public function getCurrentProductAttrDefI18n($culture = null)
  {
    if (is_null($culture))
    {
      $culture = is_null($this->culture) ? sfPropel::getDefaultCulture() : $this->culture;
    }

    if (!isset($this->current_i18n[$culture]))
    {
      $obj = ProductAttrDefI18nPeer::retrieveByPK($this->getId(), $culture);
      if ($obj)
      {
        $this->setProductAttrDefI18nForCulture($obj, $culture);
      }
      else
      {
        $this->setProductAttrDefI18nForCulture(new ProductAttrDefI18n(), $culture);
        $this->current_i18n[$culture]->setCulture($culture);
      }
    }

    return $this->current_i18n[$culture];
  }

  public function setProductAttrDefI18nForCulture($object, $culture)
  {
    $this->current_i18n[$culture] = $object;
    $this->addProductAttrDefI18n($object);
  }


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseProductAttrDef:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseProductAttrDef::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseProductAttrDef
