all:
    metas:
        title: Messages | eMarketTurkey
compose:
    metas:
        title: Compose Message | eMarketTurkey
readSuccess:
    metas:
        title: Read Message | eMarketTurkey
composedSuccess:
    metas:
        title: Send Successful | eMarketTurkey
