indexSuccess:
  metas:
    title: "Trade Experts | eMarketTurkey"
  stylesheets:   [b2b-styles.css]

applySuccess:
  metas:
    title: "Apply for Trade Experts | eMarketTurkey"

applicationReceivedSuccess:
  metas:
    title: "Apply for Trade Experts | eMarketTurkey"

tradeExpertsProfileSuccess:
  metas:
    title: "Apply for Trade Experts | eMarketTurkey"

findSuccess:
  metas:
    title: "Find Trade Experts | eMarketTurkey"
