all:
    metas:
        title: Account Settings
transferSuccess:
    metas:
        title: Account Transfer

verifySuccess:
    metas:
        title: Verify Now
editSuccess:
    metas:
        title: Edit Account Settings
changePasswordSuccess:
    metas:
        title: Change Password
privacySuccess:
    metas:
        title: Privacy Settings
        