link-trash:
  url: /*/_LINK_
  param: { module: default, action: gone }

search:
  url:   /:sf_culture/search
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: default, action: searchBC }

search-groups:
  url:   /:sf_culture/groups/search
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: groups, action: directory }

search-users:
  url:   /:sf_culture/people/search
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: people, action: directory }

user-profile-temp-bc:
  url:   /:sf_culture/profile/:id
  requirements: { sf_culture: (?:en|de|tr), id: \d+ }
  param: { module: user, action: profileBC }

user-profile-temp-bc-action:
  url:   /:sf_culture/profile/:id/:paction
  requirements: { sf_culture: (?:en|de|tr), id: \d+, action: (photos|career|info|companies|groups|friends) }
  param: { module: user, action: profileBC }

user-profile-group-bc-action:
  url:   /:sf_culture/profile/:hash/groups
  requirements: { sf_culture: (?:en|de|tr), action: (groups) }
  param: { module: user, action: profileGroupBC }

group-profile-action:
  url:   /:sf_culture/group/:stripped_name/:action
  requirements: { sf_culture: (?:en|de|tr), action: (info|discussions|connections|photos|events|career|contact|posts) } 
  param: { module: group }

group-profile-BC:
  url:   /:sf_culture/group/:stripped_name/jobs
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: group, action: jobsBC }

group-profile:
  url:   /:sf_culture/group/:stripped_name
  requirements: { sf_culture: (?:en|de|tr) }
  param: { module: group, action: posts }

user-profile-action:
  url:   /:sf_culture/profile/:hash/:action
  requirements: { sf_culture: (?:en|de|tr), action: (connections|photos|events|career) } 
  param: { module: user }

user-profile:
  url:   /:sf_culture/profile/:hash
  requirements: { sf_culture: (?:en|de|tr) }
  param: { module: user, action: profile }

venues-action:
  url:   /:sf_culture/venues/:action
  requirements: { sf_culture: (?:en|de|tr), action: (featured|byCountry|byName) }
  param: { module: venues }

venues-dir:
  url:   /:sf_culture/venues/:substitute
  requirements: { sf_culture: (?:en|de|tr), substitute: '[A-Za-z\-@]+' } 
  param: { module: venues, action: directory }

venues:
  url:   /:sf_culture/venues
  requirements: { sf_culture: (?:en|de|tr) }
  param: { module: venues, action: index }

events-action:
  url:   /:sf_culture/events/:action
  requirements: { sf_culture: (?:en|de|tr), action: (featured|attenders|byCountry|byIndustry|byName) }
  param: { module: events }

event-detail:
  url:   /:sf_culture/event/:guid
  requirements: { sf_culture: (?:en|de|tr) }
  param: { module: event, action: view }

events-dir:
  url:   /:sf_culture/events/:substitute
  requirements: { sf_culture: (?:en|de|tr), substitute: '[A-Za-z\-@]+' } 
  param: { module: events, action: directory }

events:
  url:   /:sf_culture/events
  requirements: { sf_culture: (?:en|de|tr) }
  param: { module: events, action: index }

join-group:
  url:   /:sf_culture/group/join
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: groups, action: join }

edit-group-mem:
  url:   /:sf_culture/group/join
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: groups, action: join }

groups-action:
  url:   /:sf_culture/groups/:action
  requirements: { sf_culture: (?:en|de|tr), action: (featured|connected|byCountry|byIndustry|byName|results) } 
  param: { module: groups }

groups-dir:
  url:   /:sf_culture/groups/:substitute
  requirements: { sf_culture: (?:en|de|tr), substitute: '[A-Za-z\-@]+' } 
  param: { module: groups, action: directory }

groups:
  url:   /:sf_culture/groups
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: groups, action: index }

connect-user:
  url:   /:sf_culture/people/connect
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: people, action: connect }

connect-edit-user:
  url:   /:sf_culture/people/connection
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: people, action: connection }

pymk:
  url:   /:sf_culture/pymk
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: people, action: pymk }

people-action:
  url:   /:sf_culture/people/:action
  requirements: { sf_culture: (?:en|de|tr), action: (pymk|connected|byCountry|byIndustry|byName|results) } 
  param: { module: people }

people-dir:
  url:   /:sf_culture/people/:substitute
  requirements: { sf_culture: (?:en|de|tr), substitute: '[A-Za-z\-@]+' } 
  param: { module: people, action: directory }

people:
  url:   /:sf_culture/people
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: people, action: index }

bulletin:
  url:   /:sf_culture/bulletin
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: bulletin, action: index }

####-----------

find-city:
  url:   /:sf_culture/profile/findlocation
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: profile, action: findlocation }

invite-friends:
  url:   /:sf_culture/inviteFriends
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: friendfinder, action: inviteFriends }

consent-invite:
  url:   /:sf_culture/live-contacts/inviteFriends
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: friendfinder, action: inviteConsentFriends }

consent-add:
  url:   /:sf_culture/live-contacts/addFriends
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: friendfinder, action: addConsentFriends }

livecontacts:
  url:   /:sf_culture/live-contacts
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: friendfinder, action: addConsentFriends }

friendfinder:
  url:   /:sf_culture/friendfinder
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: friendfinder, action: index }

notifications:
  url:   /:sf_culture/notifications
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: network, action: notifications }

network-activity:
  url:   /:sf_culture/activity
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: network, action: activity }

requests:
  url:   /:sf_culture/requests
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: network, action: requests }

network:
  url:   /:sf_culture/network
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: network, action: index }

location-query:
  url:   /:sf_culture/profile/locationQuery
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: profile, action: locationQuery }

location-update:
  url:   /profile/updateLocation
  param: { module: profile, action: updateLocation }

status-update:
  url:   /profile/updateStatus
  param: { module: profile, action: updateStatus }

group-status-update:
  url:   /group/updateStatus
  param: { module: group, action: updateStatus }

group-photos:
  url:   /:sf_culture/group/:stripped_name/photos
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: group, action: photos }

group-members:
  url:   /:sf_culture/group/:stripped_name/members
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: group, action: members }

group-action:
  url:   /:sf_culture/group/:stripped_name/:action
  requirements: { sf_culture: (?:en|de|tr), action: (updateStatus|upload|join) } 
  param: { module: group }

group-profile-tab:
  url:   /:sf_culture/group/:stripped_name/:action
  requirements: { sf_culture: (?:en|de|tr), id: ^[0-9]+$, action: (?:info|people|companies|groups) } 
  param: { module: group, action: index }

group-upload-photo:
  url:   /:sf_culture/group/:stripped_name/photos/upload
  requirements: { sf_culture: (?:en|de|tr), id: ^[0-9]+$ } 
  param: { module: group, action: upload }

profile-action:
  url:   /:sf_culture/profile/:action
  requirements: { sf_culture: (?:en|de|tr), action: (locationQuery|updateLocation|updateStatus|upload|comment) } 
  param: { module: profile }

# default rules
homepage:
  url:   /:sf_culture/
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { module: default, action: index }

homepage1:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:sf_culture/:module
  requirements: { sf_culture: (?:en|de|tr) } 
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*
  requirements: { sf_culture: (?:en|de|tr) } 
  