default:
  http_metas:
    content-type: text/html

  metas:
    title:        'Community | eMarketTurkey'
    description:  'eMarketTurkey Community Platform'
    keywords:     'human networking, professional, network, community, event, calender, personal profiles'
    #language:     en
    robots:       index, follow
    base:         'http://cm.emarketturkey.com'

  stylesheets:    [master-1.1.css, cm-styles.css]

  javascripts:    [jquery-1.7.1.min.js, jquery-ui-1.8.13.core.min.js, jquery.tools-1.2.5.min.js, emt-dynabox-1.0.js, emt-toolbar-init.js]

  has_layout:     on
  layout:         layoutBoxModel
