default:
  http_metas:
    content-type: text/html

  metas:
    title:        'Academy | eMarketTurkey'
    description:  'eMarketTurkey Academy Portal'
    keywords:     'article, trade, information, research, survey, news, import export knowledgebase'
    #language:     en
    robots:       index, follow
    base:         'http://ac.emarketturkey.com'

  stylesheets:    [master-1.4.css, ac-styles-0.2.css]

  javascripts:    [jquery-1.7.1.min.js, jquery-ui-1.8.13.core.min.js, jquery.tools-1.2.5.min.js, emt-dynabox-1.0.js, emt-toolbar-init.js]

  has_layout:     on
  layout:         layoutBoxModel
  