indexSuccess:
  metas:
    title: "Find a Product | eMarketTurkey"

spotlightSuccess:
  metas:
    title: "Products Spotlight | eMarketTurkey"

networkSuccess:
  metas:
    title: "Products from Your Network | eMarketTurkey"

byCountrySuccess:
  metas:
    title: "Products by Country | eMarketTurkey"

byCategorySuccess:
  metas:
    title: "Products by Category | eMarketTurkey"

byNameSuccess:
  metas:
    title: "Products by Name | eMarketTurkey"
