<?php

class EmailTransactionNamespacePeer extends BaseEmailTransactionNamespacePeer
{
    CONST   EML_TR_NS_SIGNUP            = 1;
    CONST   EML_TR_NS_NEW_MESSAGE       = 2;
    CONST   EML_TR_NS_NETWORK_REQUEST   = 3;
    CONST   EML_TR_NS_REGISTER_COMPANY  = 4;
    CONST   EML_TR_NS_RESET_PASSWORD    = 5;
    CONST   EML_TR_NS_INVITE_FRIEND     = 6;
    CONST   EML_TR_NS_CREATE_GROUP      = 7;
    CONST   EML_TR_NS_INVITE_TO_GROUP   = 8;
    CONST   EML_TR_NS_INVITE_USER_TO_GROUP = 9;
    CONST   EML_TR_NS_COMMENT           = 10;
    CONST   EML_TR_NS_VERIFY_EMAIL_ADDR = 11;
    CONST   EML_TR_NS_INVITE_TO_EVENT = 12;
    CONST   EML_TR_NS_INVITE_USER_TO_EVENT = 13;
    CONST   EML_TR_NS_NOTIFY_ACCOUNT_TRANSFER = 14;
    CONST   EML_TR_NS_CONFIRM_ACCOUNT_TRANSFER = 15;
    CONST   EML_TR_NS_ACCOUNT_TRANSFER_UPDATE  = 16;
}
