all:
    metas:
        title: "My Network | eMarketTurkey"
    layout: layoutTripleColumn

activitySuccess:
    metas:
        title: "Network Activity | eMarketTurkey"

requestsSuccess:
    metas:
        title: "Network Requests | eMarketTurkey"

pymkSuccess:
    metas:
        title: "People You May Know | eMarketTurkey"

