<em>(Güncelleme 20 Nisan, 2010)</em>
<div class="hrsplit-1"></div>
<h5>eMarketTurkey.com Hizmet ve Servislerine Yönelik Genel Şartlar ve Kullanım Koşulları</h5>
<div>
<div class="hrsplit-2"></div>
<style>
ul.order { list-style-type: decimal; padding: 10px 15px; margin-left: 20px; font-size: 1.2em;}
ul.order a {}
ul.order ul { list-style-type: lower-roman; padding: 10px 15px;}
</style>

<ul class="order">
<li><a href="#1">Giriş, Taraflar, Tanımlar</a></li>
<li><a href="#2">Sözleşmenin Konusu</a></li>
<li><a href="#3">Üyelik İşlemleri ve Hizmetin Kullanımı</a></li>
<li><a href="#4">Hak ve Yükümlülükler</a>
<ul>
<li><a href="#4-1">eMarketTurkey'in Hak ve Yükümlülükleri</a></li>
<li><a href="#4-2">Kullanıcıların Hak ve Yükümlülükleri</a></li>
<li><a href="#4-3">İşverenlerin ve İş Arayanların Hak ve Yükümlülükleri</a></li>
</ul></li>
<li><a href="#5">Genel Koşullar</a>
<ul>
<li><a href="#5-1">Yasaklı Ürünler</a></li>
<li><a href="#5-2">Garantiden Feragat</a></li>
<li><a href="#5-3">Mali Yükümlülüğün Sınırlandırılması</a></li>
<li><a href="#5-4">Talep ve Şikayet</a></li>
</ul></li>
<li><a href="#6">Gizlilik</a></li>
<li><a href="#7">Fikri Mülkiyet Hakları</a></li>
<li><a href="#8">Sözleşme Üzerinde Yapılacak Değişiklikler</a></li>
<li><a href="#9">Devir ve Temlik</a></li>
<li><a href="#10">Mücbir Sebepler</a></li>
<li><a href="#11">İhtilafların Çözümü</a></li>
<li><a href="#12">Fesih</a></li>
<li><a href="#13">Tazminat</a></li>
<li><a href="#14">Sözleşmenin Yürürlülüğü</a></li>
</ul>
</div>

<h5 id="1">1. Giriş, Taraflar, Tanımlar</h5>
<div>
<p>Bu Web Sitesi, eMarketTurkey Business Services Ltd.Şti ’ne aittir.</p>
<p><b>eMarketTurkey.com, ticaret, sanayi ve hizmet sektörlerine yönelik dizin servisleri, insan kaynakları, uluslar arası ticaret ve yatırım danışmanlığı alanlarında bir çok servisi tek bir platformda barındıran yeni nesil ticaret portalıdır.</b></p> 
<p><span><b>Kullanıcı/Üye : </b></span>Site'ye üye olan ve Site'de sunulan Servis ve Hizmet'lerden, işbu sözleşmede belirtilen koşullar dâhilinde yararlanan gerçek veya tüzel kişi</p>
<p><span><b>Alıcı : </b></span>Site'de sunulan Servis ve Hizmet'leri kullanmak suretiyle, Satıcı tarafından satışa arz edilen mal ve/veya hizmetleri satın alan Kullanıcı</p>
<p><span><b>Satıcı : </b></span>Site'de sunulan Servis ve Hizmet'leri kullanmak suretiyle, hukuken mülkiyetini haiz bulunduğu ve mülkiyet üzerinde tasarrufta bulunabilme hak ve yetkisine sahip olduğu mal ve/veya hizmetleri, diğer Kullanıcı'lara yönelik olarak satışa arz eden Kullanıcı</p>
<p><span><b>Site/Website : </b></span>www.emarketturkey.com isimli alan adından ve bu alan adına bağlı alt alan adlarından oluşan web sitesi,</p>
<p><span><b>Servis ve Hizmetler : </b></span>Kullanıcı'ların Kullanıcı Sözleşmesi'nde tanımlı olan iş ve işlemlerini gerçekleştirmelerini sağlamak amacıyla, eMarketTurkey ve/veya www.emarketturkey.com tarafından, Site içerisinde ortaya konulan uygulamalar,</p>
<p><span><b>Üyelik : </b></span>Site'nin ilgili bölümünden, Kullanıcı olmak isteyen kişi tarafından Site'ye üye olmak için gerekli kimlik bilgilerinin gönderilmesi suretiyle kayıt işleminin yaptırılması ve eMarketTurkey ve/veya www.emarketturkey.comt tarafından kayıt işleminin onaylanmasıdır.</p>
<p><span><b>İşveren : </b></span>İşçileri ücretle çalıştıran gerçek veya tüzel kişi,</p> 
<p><span><b>İş arayan : </b></span>İşsiz veya daha iyi bir iş imkanı arayan kişi,</p>
<p><span><b>CV : </b></span>Eğitim ve kariyer özgeçmişi, </p>
<p><span><b>myEMT/emarketim : </b></span>eMarketTurkey.com'un üyelerine yönelik yönetim arayüzü,</p> 
<p><span><b>Kullanıcı İçeriği/İçerik : </b></span>Kullanıcı tarafından Web Sitesi’nde veya Web Sitesi aracılığıyla sunduğu, ilan ettiği veya teşhir ettiği bütün bilgiler, veriler, metinler, yazılımlar, forumlar, müzik ve ses unsurları, fotoğraflar, grafikler, videolar, reklamlar, mesajlar veya eser niteliğindeki diğer materyallerdir,</p> 
<p><span><b>Sözleşme/Kullanıcı Sözleşmesi/Kullanım Koşulları : </b></span>işbu sözleşme ve ekleri ile Site içerisinde yer alan, kullanıma, üyeliğe ve Servis ve Hizmet'lere ilişkin olarak eMarketTurkey ve/veya www.emarketturkey.com tarafından yapılmış olan bilcümle uyarı, yazı ve açıklama gibi beyanlardır. </p>
</div>

<h5 id="2">2. Sözleşmenin Konusu</h5>
<div>
<p>Kullanıcı Sözleşmesi'nin amacı, www.emarketturkey.com internet sitesinde ürünlerini sergileyen, firmasını tanıtan, anlaşma yapan, çevrimiçi ticaret sisteminin üyeler veya 3.şahıslar tarafından kullanılmasının ve sitenin diğer hizmetlerinden yararlanılmasının kayıt ve koşullarını ortaya koymaktır. Ayrıca www.emarketturkey.com , potansiyel işverenlerin iş olanaklarını ilan etmesi ve Kullanıcıların da özgeçmişlerini  Web Sitesi veri tabanına kaydetmesi yolu ile sanal bir buluşma imkanı sunmaktadır.</p>
<p>www.emarketturkey.com  Kullanıcılar arasında, ortak deneyimler ve ilgi alanlarına bağlı olarak profesyonel ve kişisel bir ağ oluşturacak şekilde tasarlanmış olan online toplulukları içermektedir (“eMarketTurkey Toplulukları”). Web Sitesi, aynı zamanda Kullanıcılar’ın, kişisel bilgiler de içerebilecek olan kişisel profiller (”Profiller”) oluşturmalarına ve bu Profilleri kısmen yahut tamamen umuma arz etmelerine imkan tanımaktadır.</p>
<p>Nihai olarak bu sözleşme, sitemizdeki hizmetlerden faydalanabilmeniz, güvenli ticaret ve üyeler ile etkili ilişki kurabilmeniz için gerekli kuralları içermektedir.</p>
</div>

<h5 id="3">3. Üyelik İşlemleri ve Hizmetin Kullanımı</h5>
<div>
<p>Kullanıcılar, eMarketTurkey Web sitelerindeki herhangi bir hizmeti kullanmadan önce kayıt yaptırmalıdırlar.</p>
<p>Kullanıcı, kendisi tarafından kayıt için sağlanan tüm verilerin doğru ve eksiksiz olduğunu taahhüt ve beyan etmiştir. Kullanıcı, kayıt verilerinde olabilecek her türlü değişikliği gecikmeksizin eMarketTurkey’e bildirecektir.</p>
<p>Üyelik işlemi tamamlanmadan, işbu sözleşmede tanımlanan Kullanıcı olma hak ve yetkisine sahip olunamaz.</p>
<p>Site'ye üye olabilmek için, reşit olmak, eMarketTurkey ve/veya www.emarketturkey.com tarafından, geçici olarak üyelikten uzaklaştırılmış veya üyelikten süresiz yasaklanmış olmamak gerekmektedir. Reşit olmayan veya geçici olarak üyelikten uzaklaştırılmış veya üyelikten süresiz yasaklanmış olan kişilerin Site kayıt işlemlerini tamamlamış olmaları, Site üyesi olmaları sonucunu doğurmayacaktır.</p>
<p>Kullanıcı, rumuz veya yazar adı kullanmayacaktır.</p>
<p>Kullanıcı, kayıt sırasında kendisine bir şifre seçecektir. Kullanıcı, bu şifreyi gizli tutmakla yükümlüdür. eMarketTurkey, bu şifreyi hiçbir üçüncü kişiye ifşa etmeyecek ve Kullanıcı’nın şifresini hiçbir zaman istemeyecektir. eMarketTurkey, Kullanıcılar’ın şifrelerinin, üyelik hesaplarının, kullanıcı adlarının üçüncü şahıslar tarafından ele geçirilmesinden sorumlu tutulmayacağını beyan etmektedir. Kullanıcılar şifrelerinin güvenlik açısından riskli durumlar arzetmesi halinde şifresini değiştireceğini, herhangi bir yetkisiz kullanımı hakkında bilgi sahibi olur ise eMarketTurkey’a derhal haber vermeyi kabul etmişlerdir.</p>
<p>Her Kullanıcı’nın eMarketTurkey’e sadece bir kez kaydolma hakkı bulunur ve Kullanıcı sadece bir kullanıcı profili oluşturabilir.</p>
<p>eMarketTurkey.com Web sitelerinde, kayıtlı kullanıcılara iki üyelik modeli sunulmaktadır:</p> 
<ul class="order"><li>Ücretsiz Üyelik</li>
<li>Ücretli Üyelik
<ul><li>Gold Üyelik</li>
<li>Premium Üyelik</li>
</ul></li></ul>
<p>Gold ve Premium Üyelikler için geçerli ücretlerin ayrıntıları eMarketTurkey Web sitelerindeki "Üyelik" bölümünde açıklanmaktadır.  "Üyelik” bölümü altında listelenen ücretler bağlayıcıdır. Gold ve Premium Üyelik ödemelerinin faturanın düzenlenmesi üzerine derhal yapılması gerekecektir. Ödeme için çeşitli borçlandırma prosedürleri mevcuttur. Özellikle, kabul edilen kredi kartlarıyla veya mevcut online ödeme sistemleri üzerinden ödeme yapılabilir.</p>
<p>eMarketTurkey, Kullanıcıya e-postayla faturalar ve ödeme hatırlatmaları gönderebilecektir. eMarketTurkey, ayrıca, söz konusu faturaları fatura tarihinden itibaren bir (1) yıl süreyle Kullanıcı tarafından indirilebilmeleri için eMarketTurkey Web sitelerinin myEMT bölümünde hazır tutacaktır.</p>
<p>Kayıt esnasında Kullanıcılar’dan ad, soyad, adres, e-posta adresi, telefon numarası ile Kullanıcılar’ın kimliğinin tanımlanabileceği diğer bilgiler talep edilebilecektir. Kullanıcılar bu bilgilerin potansiyel işverenlere tanıtımları için ve bu Kullanım Şartları’nda sayılan amaçların ifası için gerekli bilgiler olduğunu bilmektedir ve bu bilgiler rızalarına dayanarak kayda alınmaktadır.</p> 
<p>İnternette kullanıcı doğrulamasının güç olmasından ötürü, eMarketTurkey, her Kullanıcı’nın iddia ettiği kişi olduğunu teyit etmemektedir. Kullanıcılar arası işlemlere dahil olmadığımızdan/olamadığımızdan veya Web Sitesi’nin katılımcılarının davranışlarını kontrol edemememizden ötürü, diğer Kullanıcılar ile ihtilaf yaşamanız durumunda, eMarketTurkey’ı (ve iştiraklerimizi ve çalışanlarımızı), yasaların izin verdiği azami dereceye kadar olmak üzere) söz konusu ihtilaflarla ilgili olarak ortaya çıkabilecek her türlü tazmin ve ödeme talepleri ile (fiili, sonuç olarak ortaya çıkan ve doğrudan veya dolaylı) zararlardan ibra etmektesiniz. Ayrıca ilgili konularda eMarketTurkey’a rücu hakkınız bulunmadığını kabul etmektesiniz.</p>
<p>Kullanıcılar istedikleri zaman üyeliklerini yazılı olarak bildirmek kaydı ile iptal edebilirler. Ancak üyelik iptalinden önce sunulan hizmetlerden dolayı eMarketTurkey nezdinde doğan haklar saklıdır.</p>
<p>Grup moderatörleri, üyelerini seçme hakkına sahiptirler. Bir kullanıcının gruplarına katılıp katılmamasına karar vermek konusunda özgürdürler.</p> 
</div>

<h5 id="4">4. Hak ve Yükümlülükler</h5>
<div>
<br />
<h5 id="4-1">4.1. eMarketTurkey'in Hak ve Yükümlülükleri</h5>
<p><span><b>Servis Ve Hizmetlerde Değişiklik : </b></span>eMarketTurkey ve/veya www.emarketturkey.com Kullanıcı'ların Kullanıcı Sözleşmesi'nde tanımlı olan iş ve işlemleri daha etkin şekilde gerçekleştirebilmelerini sağlamak üzere, dilediği zaman Servis ve Hizmet'lerinde değişiklikler ve/veya uyarlamalar yapabilir. eMarketTurkey ve/veya www.emarketturkey.com tarafından yapılan bu değişiklikler ve/veya uyarlamalarla ilgili olarak Kullanıcı'ların uymakla yükümlü olduğu kural ve koşullar, eMarketTurkey ve/veya www.emarketturkey.com tarafından, ilgili Servis ve/veya Hizmet'in kullanımıyla ilgili açıklamaların bulunduğu web sayfasından Kullanıcı'lara duyurulur.</p>
<p><span><b>Teklif Sunma : </b></span>eMarketTurkey, kaydınız sırasında veya daha sonra belirtmiş olduğunuz tercihlere bağlı olarak veya almayı kabul etmiş olduğunuz üçüncü kişi hizmet ve ürünlerini Size teklif etme hakkını saklı tutmaktadır. Söz konusu teklifler eMarketTurkey veya üçüncü kişilerce yapılabilecektir. Bilgilerinize ilişkin ilave detaylar için eMarketTurkey’ın Gizlilik Sözleşmesi’ne bakınız.</p>
<p><span><b>Üyeliğin iptali : </b></span>Hesabınız üzerinde hiç bir mülkiyet hakkına sahip olmadığınızı ve eMarketTurkey hesabınızı iptal etmeniz veya eMarketTurkey hesabınızın kapatılması durumunda, CV’ler, Profiller, kapak mektupları, kaydedilen işler, anket formları da dahil olmak üzere eMarketTurkey hesabınıza ilişkin bütün bilgilerin silinmiş olarak işaretleneceğini ve eMarketTurkey’ın veritabanlarından silinebileceğini ve Web Sitesi’nin umuma açık alanlarından kaldırılacağını kabul etmektesiniz. Söz konusu silme işlemlerinin eMarketTurkey’ın web sunucuları aracılığıyla gerçekleştirilmesinde yaşanabilecek gecikmelerden ötürü bilgiler bir süre boyunca saklanmaya devam edebilecektir. Ayrıca, üçüncü kişiler, bilgilerinizin saklanmış kopyalarını muhafaza edebileceklerdir.</p>
<p><span><b>Pasif Hesaplar : </b></span>eMarketTurkey, önemli bir süre boyunca aktivitede bulunulmaması durumunda hesabınızın ve bilgilerinizin tamamını silme hakkını saklı tutmaktadır.</p>
<p><span><b>Elektronik Postaları ve Mesajları Kısıtlama : </b></span>eMarketTurkey, Kullanıcılar’ını ticari reklamlar veya taleplerden korumak üzere, Kullanıcıların diğer Kullanıcılar’a gönderebileceği e-postaların ve mesajların sayısını ve büyüklüğünü, uygun göreceği bir sayı ve büyüklük ile kısıtlama hakkını saklı tutmaktadır.</p>
<p><span><b>eMarketTurkey.com'un Üyelere Ait Ürün ve Hizmetler Hakkında Sorumsuzluğu : </b></span>eMarketTurkey, Web Sitesi aracılığıyla satın alınmış olan üçüncü kişi ürünleri veya hizmetlerinin kalitesi veya mahiyetine ilişkin hiç bir taahhütte veya beyanda veya garantide bulunmamaktadır. Bu türden bir beyan, taahhüt veya garanti yalnızca sağlayıcının mutabık kaldığı koşullara bağlı olarak söz konusu üçüncü kişi ürünleri veya hizmetlerinin sağlayıcıları tarafından verilecektir. eMarketTurkey ve/veya www.emarketturkey.com sadece, üyelere, kullanıcılara iletişim köprüsü kurmaya çalışmaktadır. Sitedeki taleplerin doğruluğundan, sitede satıldığı duyurulan mal ve hizmetlerin kalitesinden, güvenilirliğinden, indirimli satış, kampanya ve promosyonların uygulanmasından, üyeler veya üye olmayan alıcılar ile ürün sağlayıcılar arasındaki alışveriş ve ticari anlaşmalardan sorumlu değildir.</p> 
<p><span><b>Kullanım Koşulları’na Uygun Olmayan İçerik : </b></span>eMarketTurkey, Kullanım Koşulları’na uygun olmadığı iddia edilen bir içerik veya diğer bir materyal ile ilgili olarak bilgilendirilmesi durumunda, takdir hakkı yalnızca kendisine ait olmak üzere, iddiayı araştırabilecek ve söz konusu içeriği kaldırıp kaldırmamayı veya kaldırılmasını talep edip etmemeyi karara bağlayacaktır. eMarketTurkey’ın, söz konusu aktivitelerin icra edilmesi veya edilmemesinden ötürü Kullanıcılara karşı mali yahut sair bir sorumluluğu bulunmamaktadır.</p>
<p><span><b>Web Sitesi Üzerinde Verilen Servis ve Hizmetler Hakkında Garanti : </b></span>eMarketTurkey Web Sitesi’nin hatasız ve/veya kesintisiz çalışacağını veya herhangi bir eMarketTurkey sitesinin ve onun sunucusunun bilgisayar virüsü veya diğer zararlı mekanizmaları taşımayacağını garanti etmez. Web Sitesi’nin ve eMarketTurkey İçeriği’nin kullanımının içerdiği tüm riski üstlenmektesiniz. Web Sitesi’nde periyodik olarak değişiklikler yapılmaktadır ve bu değişiklikler herhangi bir zamanda yapılabilecektir. eMarketTurkey, Web Sitesi’nin kullanımından elde edilecek spesifik sonuçları garanti edememektedir ve bu sonuçlara ilişkin hiç bir vaatte bulunmamaktadır.</p> 
<p><span><b>Web Sitesi Üzerinde Verilen İnsan Kaynakları Servis ve Hizmetleri  :  </b></span>eMarketTurkey, sunulan Profiller de dahil olmak üzere listeleri taramamakta veya sansürlememektedir. eMarketTurkey, işverenler ile iş arayanlar arasındaki fiili işlemlerde yer almamaktadır. eMarketTurkey bu nedenle Kullanıcı İçeriği’nden, ilan edilen işlerin veya CV’lerin kalitesi, emniyeti veya yasallığından, listelerin gerçekliği veya doğruluğundan, işverenlerin iş arayanlara iş fırsatlarını teklif etme kabiliyetinden veya iş arayanların boş iş pozisyonlarını doldurma kabiliyetinden sorumlu bulunmamaktadır ve eMarketTurkey, Web Sitesi’nde bulunan işler, CV’ler veya Kullanıcı İçeriği’ne ilişkin hiç bir taahhütte bulunmamaktadır.</p>
<p><span><b>Web Sitesi Üzerinde Verilen İnsan Kaynakları Servis ve Hizmetleri  : </b></span>eMarketTurkey’ın, karar hakkı yalnızca kendisine ait olmak üzere, Kullanıcı İçeriği’ni, iş ilanlarını, CV’leri veya diğer materyalleri zaman zaman Web Sitesi’nden kaldırma ya da ilanı askıya alma hakkını saklı tutmasına karşın, eMarketTurkey bu şekilde hareket etme yükümlülüğüne sahip değildir ve yasaların izin verdiği dereceye kadar bu türden bir eylemde bulunmamasına bağlı mali yükümlülüklerden sorumlu tutulamaz. Yabancılar, reşit olmayan kişiler veya sahte beyanlarda bulunan kişiler ile yahut işbu Kullanıcı Koşulları’nda belirtilen sakıncaları taşıyan Kullanıcılar ilişki kurmanın, fiziksel zararlar da dahil fakat bunlarla sınırlı olmamak üzere riskleri bulunmaktadır.</p> 
<p><span><b>Kullanıcı İsimleri : </b></span>Kullanıcı'ların, Site'ye üye olurken sisteme yükledikleri "kullanıcı isimleri" veya sair tanıtıcı isimleri de işbu Kullanıcı Sözleşmesi içinde yer alan hükümlere tabi olup, Kullanıcı'ların "kullanıcı ismi" veya sair tanıtıcı isimleri belirlerken üçüncü şahısların telif hakkı, marka, ticari unvan gibi yasal haklarını ihlal etmemesi gerekmektedir. Kullanıcı'ların işbu madde hükmüne aykırı davranması durumunda, eMarketTurkey ve/veya www.emarketturkey.com, Kullanıcı Sözleşmesi'ne aykırı bu durumun düzeltilmesini Kullanıcı'dan talep edebileceği gibi, dilerse Kullanıcı'ya önceden haber vermeksizin Kullanıcı'nın üyeliğini geçici veya kalıcı olarak iptal edebilir.</p>
<p><span><b>Yasadışı İçerik : </b></span>eMarketTurkey’in Kullanıcı tarafından sağlanan veri ve/veya bilgileri diğer kullanıcılara sunması, ancak bu veri ve/veya bilgilerin herhangi bir yasayı veya işbu Sözleşmeyi’yi ihlal etmemesi kaydıyla mümkün olacaktır. eMarketTurkey, herhangi bir yasadışı veya yasaklı veri ve/veya bilgiyi, Kullanıcı’ya önceden haber vermeksizin eMarketTurkey Web sitelerinden kaldırma hakkına sahiptir.</p> 
<p><span><b>Geçici Teknik Problemlerde eMarketTurkey'in Sorumsuzluğu : </b></span>Kullanıcı, eMarketTurkey Web sitelerinde %100 kullanılabilirlik düzeyine ulaşmanın teknik açıdan imkânsız olduğunu kabul etmiş ve buna razı gelmiştir. eMarketTurkey, yine de eMarketTurkey Web sitelerini kesintisiz olarak kullanılabilir durumda tutmaya çalışacaktır. Bakım, güvenlik veya kapasite gereksinimlerine bağlı durumlar ve/veya eMarketTurkey’in kontrolü dışında gerçekleşen durumlar (örn. kamu iletişim şebekelerinde yaşanan aksaklıklar, elektrik kesintileri vb.), eMarketTurkey Web siteleri üzerinden sunulan hizmetlerde kısa süreli bozulma veya geçici kesintilere yol açabilir.</p>  
<p><span><b>Kullanıcıların Kendi Aralarındaki Ticari İlişkiler : </b></span>Kullanıcılar eMarketTurkey Web siteleri üzerinden birbirleriyle sözleşmeler yaptıkları takdirde, eMarketTurkey bu sözleşmelere taraf olmayacaktır. Kullanıcılar, birbirleriyle yaptıkları sözleşmelerin akdedilmesi ve/veya icrasından kendi başlarına sorumlu olacaklardır. eMarketTurkey, kullanıcıların birbirleriyle, eMarketTurkey Web siteleri üzerinden, bu tür sözleşmelerle ilgili bağlantı kuramamalarından sorumlu tutulmayacaktır. eMarketTurkey, kullanıcılar arasında yapılan sözleşmelerle ilgili görevlerin yerine getirilmemesinden de sorumlu tutulmayacaktır.</p> 
<p><span><b>Ücretsiz Servis ve Hizmetlerin Değiştirilmesi : </b></span>eMarketTurkey, eMarketTurkey Web sitelerinde sunulmakta olan Ücretsiz Servis ve Hizmetleri  kullanıcılara bildirmeden değiştirme ve/veya  farklı Servis ve Hizmetleri sunma hakkını saklı tutar. Ayrıca eMarketTurkey, gerekli görmesi halinde, üyelik gerektirmeyen servisleri, üyelik gerektiren servisler haline dönüştürebileceği gibi üyelik gerektiren servisleri de üyelik gerektirmeyen servisler haline dönüştürme hakkına sahiptir. Üyelik ücretsizdir. Ancak eMarketTurkey İlave yeni servisler açabileceği gibi, mevcut servisleri ücretli hale getirebilir veya tamamen kullanımdan kaldırabilir.</p>
<p><span><b>Verilerin Güvenliği ve Gizlilik Politikası : </b></span>eMarketTurkey, Kullanıcı tarafından eMarketTurkey’e sunulan her türlü verinin Kullanıcı açısından son derece önemli olduğunu kabul etmektedir. eMarketTurkey, bu nedenle, bu tür verileri ele alırken özel hassasiyet gösterecektir. eMarketTurkey, veri korumaya ilişkin tüm geçerli mevzuata  uyacaktır. eMarketTurkey, özellikle, Kullanıcı’ya ait herhangi bir özel veriyi izinsiz olarak herhangi bir üçüncü kişiye vermeyecek ya da başka şekilde ifşa etmeyecektir. eMarketTurkey’in Kullanıcı’nın verilerini muamele ediş şeklinin ayrıntıları, eMarketTurkey Web sitelerinin her birinden erişilebilen eMarketTurkey Gizlilik Politikası kapsamında sunulmuştur.</p>
<p><span><b>eMarkeTurkey.com Web Sitesindeki Linkler : </b></span>eMarketTurkey ve/veya www.emarketturkey.com, Site üzerinden, eMarketTurkey ve/veya www.emarketturkey.com'un kendi kontrolünde olmayan üçüncü kişi satıcılar, sağlayıcılar ve başkaca üçüncü kişilerin sahip olduğu ve işlettiği başka web sitelerine ve/veya portallara, dosyalara veya içeriklere 'link' verebilir. Bu 'link'ler, Kullanıcı'lar tarafından veya sadece referans kolaylığı nedeniyle eMarketTurkey ve/veya www.emarketturkey.com tarafından sağlanmış olabilir ve web sitesini veya siteyi işleten kişiyi desteklemek amacı veya web sitesi veya içerdiği bilgilere yönelik herhangi bir türde bir beyan veya garanti niteliği taşımamaktadır. Site üzerindeki 'link'ler vasıtasıyla erişilen portallar, web siteleri, dosyalar ve içerikler, bu 'link'ler vasıtasıyla erişilen portallar veya web sitelerinden sunulan hizmetler veya ürünler veya bunların içeriği hakkında eMarketTurkey ve/veya www.emarketturkey.com’un herhangi bir sorumluluğu yoktur.</p>
<p><span><b>Verilerin İşlenmesi ve Kullanılması : </b></span>eMarketTurkey ve/veya www.emarketturkey.com, Site'de yer alan Kullanıcı bilgilerini veya üyeliğe ilişkin Kullanıcı bilgilerini, Kullanıcı güvenliği, kendi yükümlülüğünü ifa ve bazı istatistikî değerlendirmeler için dilediği biçimde kullanabilir. Bunları bir veritabanı üzerinde tasnif edip muhafaza edebilir. Bunun yanı sıra bazı alanlarda genel demografik ve istatistiki bilgiler de toplanabilecektir.</p> 
<p><span><b>Arabuluculuk ve Hakemlik : </b></span>eMarketTurkey ve/veya www.emarketturkey.com, Site'de sağlanan Servis ve Hizmet'ler kapsamında Kullanıcı'lar arasında ortaya çıkan uyuşmazlıklarda, arabulucu veya hakem sıfatlarıyla görev almaz.</p>
<p><span><b>Genel Ahlak Kurallarına Aykırı İçerik : </b></span>eMarketTurkey ve/veya www.emarketturkey.com, Kullanıcılar arasında site üzerinden gerçekleşen ve Site'nin işleyişine ve/veya Kullanıcı Sözleşmesine ve/veya Site'nin genel kurallarına ve/veya genel ahlak kurallarına aykırı ve eMarketTurkey ve/veya www.emarketturkey.com tarafından kabul edilmesi mümkün olmayan mesajların ve/veya içeriklerin tespit edilmesi amacıyla gerekli içerik ve/veya mesaj taraması yapabilir ve tespit ettiği mesaj ve/veya içerikleri istediği zaman ve şekilde erişimden kaldırabilir; eMarketTurkey ve/veya www.emarketturkey.com, bu mesaj ve/veya içeriği oluşturan Kullanıcıyı yazılı uyarabilir ve/veya Kullanıcı'nın üyeliğine, herhangi bir ihbar yapmadan, geçici veya kalıcı olarak, son verebilir.</p>
<p><span><b>Üyeliğe Son Verme : </b></span>Üyelik kaydı yaptıracak olan firma kaydını yaparken ilgili bölümleri mutlaka okumalıdır. Üye ve kullanıcı kurallara aykırı davrandığı taktirde, eMarketTurkey ve/veya www.emarketturkey.com yöneticileri gerekli müdahalelerde bulunma, uyarma veya servis dışına çıkarma ve üyeliğine, kullanıcılığına son verme hakkına sahip olduğunu kabul eder.</p>
<p><span><b>İçeriğe Müdahale Etme : </b></span>Kullanıcı tarafından gönderilen içeriği silme, uyarıda bulunma veya Kullanıcı’nın eMarketTurkey Web sitelerindeki hizmetlere erişimini engelleme hakkına sahiptir.</p>
<p><span><b>Yanlış Beyanda Bulunma ve Sözleşmenin İhlali : </b></span>Bu Kullanım Koşulları’ndan herhangi birini ihlal etmeniz veya bir Web Sitesi’ne kayıt olmak için eMarketTurkey’a sunmuş olduğunuz bilgileri eMarketTurkey’ın teyit edebilecek durumda olmaması halinde, eMarketTurkey, Kullanıcı İçeriği’nizin Web Sitesi’nden kaldırılması ve Web Sitesi’ne yaptırdığınız kaydın ve/veya Web Sitesi’ne ve/veya eMarketTurkey’ın Size sunmuş olduğu diğer hizmetlere erişiminizin hemen iptali de dahil fakat bunlarla sınırlı olmamak üzere sahip olduğu yasal çözüm yollarının ve talep haklarının tamamını kullanma hakkını saklı tutmaktadır.</p> 
<p><span><b>Web Sitesinin İçeriği Hakkında Garantisi : </b></span>eMarketTurkey ve/veya www.emarketturkey.com, websitesi’nin veya Servis ve Hizmetlerin hatasız çalışacağını veya websitesi’nin veya sunucularının bilgisayar virüsleri veya diğer zararlı mekanizmaları içermeyeceğini garanti etmemektedir. Site’yi veya hizmeti kullanmanızın, ekipmanlara, kullanıcının donanımına zarar vermesi veya sair materyale zarar vermesi halinde, ilgili maliyetlerden sorumlu olmayacaktır.  kullanıcılara ait Servis ve Hizmetler hakkındaki içeriği hiç bir garanti söz konusu olmaksızın “olduğu gibi” sunulmaktadır. eMarketTurkey ve/veya www.emarketturkey.com, pazarlanabilirliğe, belirli bir amaca uygunluğa ve herhangi bir hakkın ihlal edilmediğine ilişkin garantiler de dahil olmak üzere açık veya zımni tüm garantilerden aridir.eMarketTurkey ve/veya www.emarketturkey.com, Servis ve Hizmetlerin, yazlımların, metinlerin, grafiklerin ve linklerin doğruluğuna, güvenilirliğine, tamlığına, kesintisizliğine ilişkin hiç bir garantide bulunmamaktadır.</p>
</div>

<h5 id="4-2">4.2. Kullanıcıların Hak ve Yükümlülükleri</h5>
<div>
<p><span><b>Kullanım Sözleşmesinin Kabulü : </b></span>Kullanıcı, Kullanıcı Sözleşmesi'nin hükümlerini kabul etmekle, Site içinde yer alan, kullanıma, üyeliğe ve Servis ve Hizmet'lere ilişkin olarak eMarketTurkey ve/veya www.emarketturkey.com tarafından açıklanan her türlü beyanı da kabul etmiş olmaktadır. Kullanıcı, bahsi geçen beyanlarda belirtilen her türlü hususa uygun olarak davranacağını kabul, beyan ve taahhüt eder.</p> 
<p><span><b>Kullanıcılara(Üyelere) ve Ürün ve/veya Hizmelerine Ait İçerik : </b></span>eMarketTurkey ve/veya www.emarketturkey.com,  Site'de sunulan Servis ve Hizmet'leri ve içerikleri her zaman değiştirebilme, üçüncü kişilerin erişimine kapatabilme ve silme hakkını saklı tutmaktadır. eMarketTurkey ve/veya www.emarketturkey.com, bu hakkını, hiçbir bildirimde bulunmadan ve önel vermeden kullanabilir. eMarketTurkey ve/veya www.emarketturkey.com tarafından talep edilen değişiklik ve/veya düzeltme istekleri, gerekli görüldüğü takdirde, eMarketTurkey ve/veya www.emarketturkey.com tarafından herhangi bir bildirim yapılmaksızın yapılabilir. Kullanıcı'lar, eMarketTurkey ve/veya www.emarketturkey.com’un talep ettiği değişiklik ve/veya düzeltmeleri ivedi olarak yerine getirmek zorundadırlar. eMarketTurkey ve/veya www.emarketturkey.com tarafından talep edilen değişiklik ve/veya düzeltme taleplerinin Kullanıcı'lar tarafından zamanında yerine getirilmemesi sebebiyle doğan veya doğabilecek zararlar, hukuki ve cezai sorumluluklar tamamen Kullanıcı'lara aittir.</p>
<p><span><b>İçeriğin Özenle Seçilmesi : </b></span>Sitede iş ilanı bırakmak, ticari talepleri yayınlamak, firma ürünlerini resimli olarak yayınlamak vs. kullanıcıya tanınan her türlü yetkilendirme kapsamında iş ve işlemler özenle yapılmak zorundadır.</p>
<p><span><b>Yasadışı İçerik  ve Kullanıcının Sorumluluğu : </b></span>Kullanıcı, Kullanıcı tarafından eMarketTurkey Web sitelerine gönderilen içeriğin başka kullanıcıların veya üçüncü kişilerin haklarının ihlaline yol açması sonucunda, tazminat talepleri de dâhil olmak üzere bu kişilerin eMarketTurkey’e açacakları tüm davalarla ilgili olarak eMarketTurkey’in zararını karşılayacak ve eMarketTurkey’i bunlardan muaf tutacaktır. Kullanıcı, tüm makul hukuki savunma giderleri de dâhil olmak üzere, eMarketTurkey’in üçüncü kişi haklarının ihlali nedeniyle maruz kalacağı tüm makul giderleri üstlenecektir. eMarketTurkey’in tazminat talebinde bulunma hakkı dâhil başka hiçbir hak bundan etkilenmeyecektir. Kullanıcı, eMarketTurkey'in iddia edilenden daha az masraf üstlendiğini ispat etme hakkına sahiptir.</p>
<p><span><b>Ödemelerin İadesi : </b></span>Kullanıcı’nın sözleşmeyi feshetmiş olması. Ancak, Kullanıcı’nın sözleşmeyi eMarketTurkey’e bağlanabilir bir haklı gerekçeyle feshetmiş olması halinde, Kullanıcı’nın herhangi bir peşin ödemenin iadesini talep etme hakkı baki kalacaktır.</p>
<p><span><b>Bilgilerin Resmi Kurumlara Ve Hak Sahiplerine Aktarılması : </b></span>Kullanıcı, yürürlükteki emredici mevzuat hükümleri gereğince veya diğer Kullanıcılar ile üçüncü şahısların haklarının ihlal edildiğinin iddia edilmesi durumlarında, eMarketTurkey ve/veya www.emarketturkey.com’un kendisine ait gizli/özel/ticari bilgileri gerek resmi makamlara ve gerekse hak sahibi kişilere açıklamaya yetkili olacağını ve bu sebeple eMarketTurkey ve/veya www.emarketturkey.com'dan her ne nam altında olursa olsun tazminat talep edilemeyeceğini kabul, beyan ve taahhüt eder.</p>
<p><span><b>İhbar : </b></span>Kullanıcı, başka herhangi bir kullanıcının geçerli yasaları ve/veya işbu Genel Şart ve Koşulları ihlal eden her türlü faaliyetini (rumuz veya sahte kimlik kullanımı dâhil) tüm eMarketTurkey Web sitelerinde bulunan iletişim formunu kullanarak rapor edebilir.</p>
<p><span><b>İçeriğin İzin Alınarak Kullanılması : </b></span>eMarketTurkey Web sitelerinde sunulan hizmetler ve içeriğin herhangi bir şekilde eMarketTurkey tarafından sunulan seçeneklerin kapsamı dışında kullanımı, eMarketTurkey’in önceden yazılı izninin alınmasını gerektirir.</p> 
<p><span><b>Sözleşmenin İhlali ve Askıya Alma : </b></span>İşbu Kullanım Koşulları’nda belirtilen hükümleri ihlal eden Kullanıcılar’ın Web Sitesi’ne erişimde bulunmaları ve Site’yi kullanmaları, herhangi bir ihbara gerek kalmaksızın askıya alınabilir veya iptal edilebilir.</p>
<p><span><b>İçeriğin Şekli : </b></span>eMarketTurkey ve/veya www.emarketturkey.com üyenin girdiği bilgilerin kamu düzenini bozucu, kamu güvenliğine ve genel ahlaka aykırı, başkalarını rahatsız edici ve yasalara aykırı olması durumunda şikâyet üzerine veya resen üyenin ve kullanıcının www.emarketturkey.com üyeliğine son verme hakkını saklı tutar.</p>
<p><span><b>Sergilenen Ürün Ve Hizmetler : </b></span>Üye ve kullanıcı, site'de satışa arz ettiği, tanıttığı ürünün/ürünlerin mülkiyetinin kendisine ait olduğunu ve ürünün/ürünlerin kendisi tarafından satılmasına karşı herhangi bir hukuki veya diğer engel bulunmadığını kabul, beyan ve taahhüt eder. Satıcı, satışa arz ettiği ürünün/ürünlerin, Yasaklı Ürünler de dahil olmak üzere, Kullanıcı Sözleşmesi hükümlerince belirlenen veya Site'nin belirli yerlerinde belirtilen, Site'nin ve Site'de sunulan Servis ve Hizmet'lerin kullanımına ilişkin kurallara ve üyeliğe ilişkin koşullara aykırı olmadığını ve yürürlükteki tüm mevzuata uygun olduğunu kabul, beyan ve taahhüt eder.</p> 
<p><span><b>Kullanıcıya ait profil : </b></span>eMarketTurkey Web Sitesine, Kullanıcı’nın beş (5) yıldan eski olmayan ve Kullanıcı’nın açıkça ve kolayca tanınabildiği fotoğraflarını göndermek. Kullanıcı, Kullanıcı tarafından ulaştırılan fotoğrafların herkese açık olarak görüntülenmesinin yasak olmadığını taahhüt ve beyan etmiştir. Kullanıcı, Kullanıcı dışında herhangi bir kişinin ya da gerçek olmayan kişi veya varlıkların (hayvanlar, hayali yaratıklar gibi) hiçbir fotoğraf veya görüntüsünü yüklemeyecektir. Kullanıcı tarafından iletilen fotoğraflarda hiçbir şirket logosu bulunmayacaktır. eMarketTurkey çalışanlarının fotoğrafları bundan istisnadır.</p>
<p><span><b>Grup Logosu : </b></span>Şirket logosu içeren grup logolarına da izin verilmemektedir. Ancak, Premium üyelerin oluşturduğu Gruplar özel izinle bu kuralın dışında tutulabilir.</p>
<p><span><b>Kullanıcı site kullanımı ile bağlantılı olarak şu maddeleri kabul ve beyan etmektedir : </b></span></p>
<p><span><b>Yasalara ve mevzuatlara uymak : </b></span>Yürürlükteki hiçbir Türkiye Cumhuriyeti yasasını, uluslar arası sözleşmeyi veya diğer herhangi bir devletin yasalarını herhangi bir şekilde ihlal etmeyeceğini, Türkiye Cumhuriyeti Yasalarına, Türkiye Cumhuriyeti’nin taraf olduğu uluslar arası sözleşmelere, diğer uluslar arası sözleşmelere ve diğer ülke yasalarına aykırı, zararlı, tehdit, hakaret ve sövme içeren, suistimal veya taciz edici, haksız fiil veya iftira niteliğinde, kaba, müstehcen, kötüleyici veya başka birinin gizlilik haklarini ihlal edebilecek şekilde veya diğer herhangi bir biçimde Kullanıcı’nın hukuki ve cezai sorumluluğunu gerektiren hiçbir mesaj, bilgi, veri, metin, yazılım veya imajlar veya diğer herhangi bir tür materyali iletmeyeceğini, Kullanıcı, özellikle, kendisine ait içeriğin başka bir kullanıcıyı veya eMarketTurkey personelini ya da diğer şirketleri hedef alıp almadığına bakılmaksızın, hakaret içeren veya birinin itibarını lekeleyen hiçbir içeriği kullanmayacak, azınlıkların korunmasına ilişkin herhangi bir geçerli yasaya aykırı hiçbir pornografik malzeme veya içerik kullanmayacak ya da azınlıkların korunmasına ilişkin herhangi bir geçerli yasaya uygun olmayan hiçbir pornografik ürün veya ürünlerin reklamını ya da tanıtımını yapmayacak, bunları sunmayacak veya dağıtmayacak,</p>
<p><span><b>Temsil : </b></span>Bu Web sitesi’nin sahibi/sahipleri, görevlileri veya çözüm ortaklarını da kapsayan ancak bununla sınırlı olmayarak, herhangi bir kişi veya işletmeyi, o kişi veya işletmenin temsilcisiymiş gibi 3. şahıslar nezdinde temsil etmeyeceğini veya yanıltıcı ve halkın kafasında iltibas yaratabilecek biçimde bu kişi ve işletmeler ile ilgisi olduğunu ifade etmeyeceğini,</p>
<p><span><b>Web Sitesi İçeriğinin Yetkisiz Değiştirilmesi : </b></span>Web Sitesi içeriğine Web Sitesi görevlilerinin veya diğer gerçek veya tüzel kişilerin ilettiği metin, resim, grafik, tescilli markalar, ticari unvanlar ve isimler gibi ve bunlarla sınırlı olmayarak Web sitesi içeriğine dahil edilen herhangi bir materyali değiştirmeyeceğini veya silmeyeceğini,</p>
<p><span><b>Teknik Saldırı, Yetkisiz Ve Olumsuz Müdahale : </b></span>Virüsler, truva atları, casus programlar ve dialer programları gibi her türlü kötü amaçlı kodları ve materyalleri yerleştirmeyeceğini veya iletmeyeceğini, Sitenin iletişim özelliklerini, sitenin kaynaklarını herhangi bir yöntemle diğer Kullanıcı’ların elde edebilmesini kısıtlayacak biçimde kullanmayacağını, eMarketTurkey Web sitelerini kullanırken herhangi bir mekanizma, yazılım veya komut dosyası kullanmayacağını,  (Ancak, Kullanıcı, eMarketTurkey Web Sitelerinde sunulan hizmetler kapsamında eMarketTurkey tarafından sağlanan ara yüzleri veya yazılımları kullanabilir.) Ayrıca eMarketTurkey Web Sitelerinin herhangi bir içeriğini engellemek, üzerine yazmak, değiştirmek ve kopyalamak gibi eMarketTurkey altyapısının işleyişine zarar verebilecek, özellikle de söz konusu altyapının aşırı yüklenmesine neden olacak herhangi bir eylemde bulunmayacağını, aşağıda sıralanan metodları uygulamayacağını :</p> 
<ul>
<li>Web Sitesi’nde gezinmek veya arama yapmak maksadıyla Site’de mevcut olan imkanlar ile genel olarak kullanılan üçüncü taraf web tarayıcıları veya eMarketTurkey’ın onayladığı diğer imkanlar haricindeki bir cihazın kullanılması;</li>
<li>Veri madenciliği, robotlar veya benzeri veri toplama ve alma yöntemlerinin kullanılması; Bir sistem veya networkün risklere açıklığının yoklanması, taranması veya test edilmesi teşebbüsleri de dahil olmak üzere, Web Sitesi’nin güvenliğinin ihlal edilmesi veya güvenliğini tehlikeye düşürecek teşebbüslerde bulunulması veya gerekli yetkiye sahip olmaksızın güvenlik veya doğrulama önlemlerinin ihlal edilmesi;</li>
<li>Bir elektronik postada veya haber grubu ilanında yer alan bir TCP/IP paket başlığının veya başlık bilgilerinin herhangi bir kısmının tahrif edilmesi;</li>
<li>Web Sitesi’nin herhangi bir kısmının ters mühendisliğe tabi tutulması veya kaynak koda dönüştürülmesi, demonte edilmesi ya da herhangi bir eMarketTurkey sitesinin kopyalanması;</li>
</ul>

<p><span><b>İçerik İhlali : </b></span>Hiçbir talep edilmeyen reklam, promosyonal materyal zincir mektuplar, veya başka herhangi bir biçimde ticari amaçlı metin, resim, ses, grafik ve diğer her türlü materyali yerleştirmeyeceğini veya iletmeyeceğini,</p>
<p><span><b>İçeriğin izinsiz kullanılması : </b></span>Kullanıcı, Framing ve/veya benzer teknolojileri kullanarak Web Sitesi’ni kendi amaçları doğrultusunda yönlendirmeyeceğini veya başka bir biçimde görüntülemeyeceğini, yasalarla (örn. telif hakkı, marka hakkı, patent, kullanım patenti veya tasarım patenti kanunları) korunan hiçbir içeriği izinsiz kullanmayacak veya yasal koruma altındaki hiçbir mal veya hizmetin reklam, tanıtım, arz veya dağıtımını yapmayacağını,</p>
<p><span><b>Zincir Emailleri : </b></span>Zincirleme mektuplar göndermeyeceğini,</p> 
<p><span><b>Spam Mesajlar : </b></span>Aynı anda bir (1)’den fazla kullanıcıya aynı özel mesajları göndermeyeceğini,</p>
<p><span><b>Cinsellik İçeren İçerik : </b></span>Herhangi bir şekilde, herhangi bir üye ile üstü kapalı ve/veya cinsel içerikli (müstehcen veya açık) iletişim kurmayacağını,</p> 
<p><span><b>İçeriği izinsiz İfşa Etmek : </b></span>eMarketTurkey veya başka herhangi bir kullanıcının web sitelerinin içeriğini dağıtmayacağını ve/veya özel bilgilerini alenen ifşa etmeyeceğini,</p>
<p><span><b>İçeriğin İzinsiz Kullanılması : </b></span>Bu Kullanım Koşulları’nda izin verilenler istisna olmak üzere, süresi dolan iş ilanları da dahil olmak üzere bir eMarketTurkey İçeriği’nin veya Web Sitesi’nde bulunan bir bilginin toplanmayacağını, kopyalanmayacağını veya bu hususlara teşebbüs edilmeyeceğini;</p>
<p><span><b>Haksız Rekabet : </b></span>Kademeli müşteri edinme uygulamaları (zincirleme dağıtım sistemleri, çok seviyeli satış veya piramit satış gibi) da dâhil olmak üzere haksız rekabet yarattığı düşünülen hiçbir ticari uygulamayı kullanmayacak veya bunların tanıtımını yapmayacaktır, Ayrıca Kullanıcı,  eMarketTurkey ve/veya www.emarketturkey.com ile doğrudan ve/veya dolaylı olarak haksız rekabete girmeyeceğini kabul, beyan ve taahhüt eder. Ayrıca;</p> 
<p><span><b>Yasadışı Silahlar, Yasak Bilgiler : </b></span>Yanıltıcı bilgiler veya yasadışı aktiviteleri tanıtan, destekleyen veya yasadışı silahların üretilmesi veya satın alınması, bir kişinin mahremiyetinin ihlal edilmesi, bilgisayar virüslerinin sağlanması veya oluşturulması veya medya korsanlığı yapılması gibi yasadışı aktivitelere ilişkin bir içeriğin veya bu Kullanım Koşulları’ın yasakladığı diğer aktivitelere ilişkin talimat niteliğindeki bilgileri teşvik eden veya sunan bir içeriğin veya materyalin ilan edilmesi;</p>
<p><span><b>Başkası Adına İş Başvurusunda Bulunmak : </b></span>Site’de üçüncü kişiler adına bir CV’nin ilan edilmesi veya üçüncü kişiler adına iş başvurusunda bulunulması, diğer Kullanıcıların herhangi bir kişisel hakkının, fikri ve sınai hakkının veya gizliliğini ihlal eden materyallerin ilan edilmesi;</p>
<p><span><b>İnsan Kaynakları Süreçlerini Sekteye Uğratmak : </b></span>Herhangi bir işveren ile acente, ajans veya sair üçüncü kişiler arasındaki irtibatın engellenmesi;</p>
<p><span><b>Mükerrer CV : </b></span>Herhangi bir zamanda aynı CV’nin birden fazla kopyasının umuma açık kılınması yahut mükerrer CV sunulması;</p>
<p><span><b>İzinsiz giriş : </b></span>Sizin için öngörülmeyen verilere erişim yapılması veya erişimde bulunma yetkinizin olmadığı bir sunucuya veya hesaba giriş yapılması;</p>
<p><span><b>Yanıltıcı CV : </b></span>Eksik, yanlış veya yanıltıcı biyografik bilgilerin veya Size ait olmayan bilgilerin Web Sitesi’nde ilan edilmesi veya sunulması;</p>
<p><span><b>İçeriğin İzinsiz Değiştirilmesi : </b></span>Diğer bir kişi veya kuruluşun ilan ettiği bir materyalin, bilginin silinmesi veya değiştirilmesi;</p>
<p><span><b>Taciz : </b></span>Bir grubun, şirketin veya kişinin taciz edilmesi, taciz edilmesi için teşvikte bulunulması veya taciz edilmesinin savunulması;</p>
<p>eMarketTurkey Hizmetleri’nin yasadışı bir maksat veya aktivite için kullanılması veya eMarketTurkey’ın takdirine bağlı olarak tespit edileceği üzere onur kırıcı, iftira niteliğindeki, açık veya dolaylı olarak saldırgan, amiyane, müstehcen, tehdit edici, nefret dolu, ırkçı, ayrımcılık yapan, tehditkar nitelikteki veya rahatsızlığa, tacize, endişeye neden olması muhtemel olan veya bir kişinin taciz edilmesine neden olabilecek olan veya pornografik, çirkin, cinsel istismar içeren materyallerin linklerini içeren bir içeriğin, CV’nin veya iş ilanının asılması veya sunulması. Toplumun genel ahlak kurallarına uymayan ifadeleri içeren metin, fotoğraf veya görseller, politik içerikli, başka kişi ve kurumların kişilik haklarına saldırı niteliği taşıyan içerikler yahut eksik, yanlış, hatalı ve yanıltıcı nitelikte resim ve/veya özgeçmiş bilgilerinin Site’ye kaydedilmesi;</p>

<p><u>yasaklanmış olup, kullanıcı bu maddeleri kabul, beyan ve taahhüt eder.</u></p>
</div>

<h5 id="4-3">4.3. İşverenlerin ve İş Arayanların Hak ve Yükümlülükleri</h5>     
<div>
<p><span><b>CV Kaydetme ve Kullanımına İzin Verme : </b></span>(Özgeçmişlerin Kaydedilmesi ve Bilgilerin Toplanması)</p>
<p>Kullanıcılar Web Sitesi’ne üye olup kayıt işlemini tamamladıktan sonra özgeçmişlerini Web Sitesi veritabanında saklanmak üzere kaydedebilirler. Kullanıcılar özgeçmişlerini Site’ye yükleyerek; özgeçmişlerinin genel kullanım için görüntülenmesine, potansiyel işverenler ile paylaşılmasına yahut eMarketTurkey tarafından istatiki amaçlarla ve işbu Kullanım Şartları’nda tesis edilen amaçlarla kullanılmasına izin verdiğini beyan ederler. Bu durumlarda özgeçmişlerin saklanmasından, kullanılmasından, değiştirilmesinden ve gizliliğinden yahut sair işlemlerden eMarketTurkey sorumlu değildir. Ayrıca Kullanıcı özgeçmiş bilgilerini bizzat oluşturduğunu ve her türlü bilginin doğru olduğunu beyan etmektedir. eMarketTurkey’ın kullanıcıların ilan ettiği hususları kontrol etmek gibi bir yükümlülüğü bulunmamaktadır.</p>
<p><span><b>CV'lerin Doğruluğu Ve İşverenlere Ulaştırılması : </b></span>Kullanıcılar, kendileri tarafından doldurulmuş ve kaydedilmiş özgeçmişlerinin içeriğinden ve doğruluğundan yalnızca kendilerinin sorumlu olduklarını kabul ederler. Kullanıcılar özgeçmişlerinde yer alan bilgilerin, potansiyel işverenlere sunulmak üzere Web Sitesi’ne kaydedildiğini bilmekte, kayıtları kendileri gerçekleştirmektedir. Bu nedenle ilgili bilgiler eMarketTurkey tarafından potansiyel işveren olduğunu beyan ederek Site’ye giriş yapan kişilere herhangi bir izne gerek kalmaksızın ifşa edilebilir.</p> 
<p><span><b>Özel Bilgilerin , Kullanımına İzin Verme : </b></span>Kullanıcılar, toplanılan iletişim bilgilerinin (GSM numarası, e-posta adresi vs.) eMarketTurkey tarafından, eMarketTurkey’ın sağlayacağı diğer ürünler veya hizmetler hakkında bilgilendirilmek ya da Web Sitesi’ndeki güncellemelerin bildirilmesi amacıyla kullanılabileceğini kabul ederler. Kullanıcılar, ayrıca iletişim bilgilerine, Web Sitesi’nden, potansiyel işverenlerden ya da üçüncü kişilerden ücretsiz bültenlerinin, hatırlatma bilgilerinin ya da tanıtım ve promosyon mesajlarının gönderilebileceğini bağlantılı bu kişilere ilgili bilgilerin ifşa edilebileceğini kabul ederler.</p>
<p><span><b>CV'leri Güncelleme : </b></span>Kullanıcılar Web Sitesi veri tabanına kaydettikleri özgeçmişlerini istedikleri zaman gözden geçirebilir, düzeltebilir veya güncelleyebilirler.</p>
<p><span><b>İşverenin Verdiği İş İlanlarına Dair Sorumluluğu : </b></span>İşverenler, Web Sitesi’nde yer alan ilanların içeriğinden münhasıran sorumludur. eMarketTurkey’ın söz konusu içerikleri önceden kontrol etmek gibi bir yükümlülüğü bulunmamaktadır. eMarketTurkey, bir işveren değildir ve eMarketTurkey, Web Sitesi’nde iş ilanları yayımlayan gerçek yahut tüzel kişilerin vermiş olduğu istihdam kararlarından her ne nam altında olursa olsun sorumlu tutulamaz. eMarketTurkey, Web Sitesi’nde yer alan her türlü bilgi, haber ve makale içeriği ile ilgili herhangi bir sorumluluk kabul etmez veya Kullanıcılar tarafından ifade edilmiş herhangi bir fikri onaylamış addedilemez.</p>
<p><span><b>Kişisel Bilgilerin Korunması ve İşverenin Sorumluluğu : </b></span>İşveren eMarketTurkey CV Veritabanı’nını genel gizlilik ve kişisel bilgilerin korunmasına dair yasalara uygun olarak kullanacak ve yetkilendirilmiş bir istihdam bürosu ve personel temin ajansı olmadığınız veya CV’leri açık bir şekilde istihdam maksatları için kullanmadığınız sürece eMarketTurkey CV Veritabanı’ndan alınmış olan verileri üçüncü kişilere ifşa etmeyeceğinizi kabul etmektesiniz. eMarketTurkey CV Veritabanı’ndan almış olduğunuz verileri, kayıplara, suistimallere, yetkisiz erişimlere, ifşalara, kurcalamalara veya imhalara karşı korumak için gereken fiziksel, teknik ve idari önlemleri alacaksınız. eMarketTurkey, özgeçmiş görüntüleme hizmetinin amaç dışı veya kötü niyetli kullanımının tesbiti halinde veritabanını potansiyel işverenlere haber vermeksizin kapatma hakkını gizli tutar. İşveren, eMarketTurkey ve adayın uğrayacağı maddi ve manevi tüm zararları ferileri ile birlikte ödemekle yükümlüdür. Potansiyel işveren ile CV sahibi arasındaki ilişkide eMarketTurkey muhatap olarak alınmayacak ve sorumlu tutulmayacaktır.</p>
<p><span><b>İşverenin İş Arayanı İstihdamı Etmesi : </b></span>İşveren, eMarketTurkey hizmetleri aracılığı ile bir adayı işe alır ise, bordro ve tüm özlük haklarından ve sair benzeri sorumluluklarından işveren sıfatı ile münhasıran sorumlu olacaktır. eMarketTurkey’ın hizmetleri Web Sitesi hizmetleri ile sınırlıdır.</p>
<p><span><b>İşveren Hesabının Kapatılması : </b></span>İşveren hesabının iptal edilmesi veya işveren hesabınızın feshedilmesi durumunda, kaydedilmiş CV’ler, network irtibatları ve elektronik posta listeleri de dahil olmak üzere eMarketTurkey hesabınıza ilişkin bütün bilgilerin silinmiş olarak işaretleneceğini ve eMarketTurkey’ın veritabanlarından silinebileceğini kabul ve taahhüt etmektesiniz. Söz konusu silme işlemlerinin eMarketTurkey’ın web sunucuları aracılığıyla gerçekleştirilmesinde yaşanabilecek gecikmelerden ötürü bilgiler bir süre boyunca saklanmaya devam edebilecektir. İşveren silinen ya da muhafaza edilen kayıtlar ile ilgili herhangi bir hak veya tazminat talebinde bulunamaz. İşveren, sona ermeye ilişkin olarak herhangi bir zarar – ziyan ve/veya hangi nam altında olursa olsun herhangi bir tazmin talebinde bulunmayacağını bu haklarından peşinen feragat ettiğini kabul ve beyan eder.</p>
<p><span><b>Bir iş ilanı aşağıda belirtilen hususları içeremez:</b></span></p>
<ul>
<li>eMarketTurkey’ın özel olarak onayladıkları dışında kalan hiperlinkler (gelen başvuruların Web Sitesi haricindeki bir faks numarası, e-posta, adres veya web adresine yönlendirilmesi);</li>
<li>eMarketTurkey tarafından tespit edilmek üzere, yanıltıcı, okunaksız veya “gizli” anahtar kelimeler, tekrar edilen anahtar kelimeler veya sunulan iş fırsatı ile ilişkisiz olan anahtar kelimeler;
<li>eMarketTurkey’ın açık şekilde mutabık kaldıkları istisna olmak üzere, müşterimizin yan kuruluş dışında kalan ve bağlı olmayan şirketlerin isimleri, logoları, ticari markaları yahut sair tanıtıcı işaretleri;
<li>İş ilanı ile ilişkili olmayan kolej, şehir, eyalet, kasaba veya ülke isimleri;
<li>Sitenin imkan tanıdığı haller istisna olmak üzere, birden fazla iş veya iş açıklaması, birden fazla yer veya birden fazla iş kategorisi;
<li>Yanlış veya yanıltıcı bilgiler ve
<li>Kişileri cinsellik, şiddet içerecek yahut sair bir şekilde istismar eden veya işbu Kullanım Şartları’nda belirtilen sakıncalı hususlar, 18 yaşın altındaki kişilerin kişisel bilgilerini talep eden materyaller veya bu tür materyallerin linkleri.</li>
</ul> 
<p><span><b>İçeriğin Şekli : </b></span>İş ilanlarını aşağıda belirtilen maksatlar için kullanamazsınız:</p>
<ul>
<li>İşgücü ve istihdama ilişkin, eşit istihdam fırsatı ve istihdam uygunluk koşullarına, veri gizliliğine, verilere erişim ve verileri kullanıma, fikri mülkiyet hakkına ilişkin yasalar da dahil fakat bunlarla sınırlı olmamak üzere, meri yerel, ulusal veya uluslararası yasalara uygun olmayan iş olanaklarının ilan edilmesi;</li>
<li>Yasalara, mevzuatlara ve sair resmi düzenlemelere uygunluk sağlamak için gerekli olan haller istisna olmak üzere, istihdamın bir koşulu olarak belirli bir ülkenin vatandaşı olunmasını veya bir ülkede daimi olarak ikamet edilmesini gerektiren iş ilanları;</li>
<li>İlgili koşul veya kriterin, ilan edilen işin fiili ve yasal bir koşulu olmadığı durumlarda, bir iş ilanı ile bağlantılı olarak bir tarama koşulunu veya kriterini içeren iş ilanları;</li>
<li>eMarketTurkey’ın dolaylı yahut doğrudan rakiplerine ait iş olanaklarının ve/veya diğer reklamların ilan edilmesi veya eMarketTurkey ile rekabet eden bir sitenin linklerini içeren hususların ilan edilmesi;</li>
<li>Ürünler veya hizmetlerin satılması, tanıtımının veya reklamının yapılması, sponsorluk alınması;Promosyonlar, ürünler veya hizmetlerin CV sahiplerine tanıtımının yapılması da dahil fakat bununla sınırlı olmamak üzere, bir işverenin personel araması dışındaki her türlü maksat için;</li>
<li>Bir franchise alanın, piramit planının, “kulüp üyeliğinin”, distribütörlüğün, çok seviyeli pazarlama fırsatının veya satış temsilcisi ajans düzenlemesinin ilan edilmesi;</li>
<li>Peşin bir ödemenin veya periyodik ödemelerin yapılmasını gerektiren veya diğer üyelerin, alt distribütörlerin veya alt acentelerin işe alınmasını gerektiren bir iş fırsatının ilan edilmesi yahut ücretli üyelik tesis eden imkanlar sunulması;</li>
<li>Teklif edilen iş için yalnızca komisyon ödendiğinin ilanda açık bir şekilde belirtilmemesi ve iş arayan kişinin satacağı ürün veya hizmetin açık bir şekilde tanımlanmaması durumunda yalnızca komisyon ödenen bir iş fırsatının ilan edilmesi;</li>
<li>Gerçek bir istihdamı temsil etmeyen bir fırsatın tanıtımının yapılması;</li>
<li>CV sahipleri ile CV sahiplerince talep edilmeyen telefon görüşmeleri yapmak veya fakslar göndermek veya CV sahiplerince talep edilmeyen postalar, elektronik postalar veya bültenler göndermek veya kendileri ile irtibat kurulmasını kabul etmedikleri halde (iznin gerekli olduğu durumlarda veya açık iznin gerekli olmaması halinde kendileri ile irtibat kurulmasını istemediklerini Size bildirmemiş olan kişiler) herhangi bir kişi ile irtibat kurmak;</li>
<li>Modellik, aktörlük, yetenek veya eğlence ajansları ile yetenek keşif pozisyonlarına yönelik iş ilanlarının Web Sitesi aracılığıyla duyurulması;</li>
<li>Cinsel hizmetlerin ya da ahlaka aykırı hizmetlerin reklamının yapılması veya cinsel mahiyetteki yahut ahlaka aykırı işler için işçi aranması;</li>
<li>Yumurta bağışı ve taşıyıcı annelik gibi üreme hizmetleri de dahil olmak fakat bununla sınırlı olmamak üzere, insan vücut parçalarının kullanımının veya insan parçalarının bağışlanmasının talep edilmesi;</li>
<li>Belirli bir siyasi partinin, siyasi gündemin, siyasi konumun veya konunun desteklenmesi;</li>
<li>Belirli bir dinin teşvik edilmesi ya da yerilmesi;</li>
<li>Türkiye’nin ekonomik ambargo uyguladığı ülkelerdeki işlere yönelik ilanların verilmesi ve</li>
<li>Meri yasaların izin verdiği haller istisna olmak üzere, Kullanıcının kendi (i) ırkı veya etnik kökeni, (ii) politik inançları, (iii) felsefi veya dini inançları, (iv) sendika üyeliği, (v) fiziksel veya zihinsel sağlığı, (vi) cinsel yaşamı, (vii) işlediği suçlar veya hakkında başlatılan takibatlar veya (vii) yaşı ya da tuttuğu spor takımı gibi ayırıcı nitelik taşıyan bilgileri sunmasını gerektiren iş ilanları,</li>
<li>eMarketTurkey, takdir hakkı tamamen kendisinde olmak üzere yukarıda yer alan Kulanım Koşulları’na uygun olmayan ve/veya amacına uygun olmayan herhangi bir iş ilanını veya içeriği Web Sitesi’nden kaldırma yahut ilanı askıya alma hakkını saklı tutmaktadır.</li>
</ul>
<p><span><b>eMarketTurkey'in CV Verileri Üzerinde Taktir Hakkı : </b></span>Müşterilerimizin tamamı için güvenli ve etkili bir deneyim sağlamak amacıyla, eMarketTurkey, herhangi bir süre içinde erişimde bulunabileceğiniz veri miktarını (CV görüntülemeleri dahil) sınırlandırma hakkını saklı tutmaktadır. Bu limitler, eMarketTurkey tarafından zaman zaman değiştirilebilecektir.</p>
</div>

<h5>5. Genel Koşullar</h5> 
<div>
<p><span><b>Kullanım Sözlemesinde Belirtilmeyen Hususların Geçerliliği : </b></span>Bir Kullanıcı’nın eMarketTurkey’dan veya Web Sitesi’nden elde ettiği yazılı veya şifahi hiç bir bilgi veya görüş, bu Kullanım Koşulları’nda açık bir şekilde belirtilmeyen bir garanti tesis etmeyecektir.</p>
<p><span><b>Ek Koşullar/ Sözleşmeler : </b></span>Web Sitesi’nin belirli alanları ilave koşullara tabi bulunmaktadır. Söz konusu alanların tamamını yahut bir kısmını kullanmak suretiyle, söz konusu alanlar için geçerli olan ilave koşulların bağlayıcılığını kabul etmektesiniz. </p>
<p><span><b>Sözleşme Süresi : </b></span>Kullanım Koşulları Web Sitesi’nin Kullanıcısı veya Üyesi olduğunuz sürece geçerli ve yürürlükte olmaya devam edecektir. </p>
<p><span><b>Kullanıcı İçeriğinin Kopyası : </b></span>eMarketTurkey, Kullanıcı İçeriği’nizin yedek bir kopyasını saklamanızı tavsiye etmektedir. eMarketTurkey hiç bir şekilde Kullanıcı İçeriği’nizin silinmesi, kaybolması veya yetkisiz bir şekilde değiştirilmesinden sorumlu olmayacaktır.</p>
<p><span><b>eMarketTurkey.com'un İçeriği : </b></span>eMarketTurkey.com'un İçeriği yanlışlıklar veya yazım hataları içerebilir. eMarketTurkey, Web Sitesi’nin ve/veya eMarketTurkey İçeriği’nin doğruluğu, güvenilirliği, eksiksizliği, kesintisizliğine ilişkin hiç bir taahhütte bulunmamaktadır. Web Sitesi içeriği, yanlışlıklar veya baskı hataları içerebilir.</p>
<p><span><b>Dikkatli Olmanızı Tavsiye Ediyoruz : </b></span>Web Sitesi aracılığıyla temas kurmuş olduğunuz diğer Kullanıcılar ile ilişki kurmanın içerdiği bütün riskleri üstlenmektesiniz. Mahiyetleri gereği diğer kişilerin bilgileri zararlı veya yanlış olabilir ve bazı durumlarda yanlış veya aldatıcı bir şekilde yönlendirilebilirsiniz. Web Sitesi’ni kullanırken ihtiyatlı ve sağduyulu hareket etmenizi tavsiye ediyoruz.</p>
<p><span><b>Temsil : </b></span>Kullanıcı'lar ve eMarketTurkey ve/veya www.emarketturkey.com hukuken bağımsız taraflardır. Aralarında ortaklık, temsilcilik veya işçi-işveren ilişkisi yoktur. Kullanıcı Sözleşmesi'nin onaylanması ve uygulanması sonucunda, ortaklık, temsilcilik veya işçi-işveren ilişkisi doğmaz.</p>
<p><span><b>Reşit Olmak : </b></span>Web Sitesini ziyaret edebilmeniz veya Site’den yararlanabilmeniz için en az 18 yaşında olmanız gerekmektedir.18 yaşın altında olmanız durumunda Web Sitesi’ni ebeveyninizin yahut yasal vasinizin gözetiminde ve izni ile kullanabilirsiniz. Bu nedenle Sizin belirtilen şartları taşıdığınız ve tespit edilen amaçlara yönelik bir Kullanıcı olduğunuz farz edilerek Web Sitesi hizmetinize sunulmaktadır.Kullanıcı, kişisel bilgilerin yer aldığı formu doldurarak Kullanım Şartları’nın yürürlüğe girdiğini kabul etmiş olur.</p>
<p><span><b>İş Bu Sözleşme Üzerinde Güncellemeler : </b></span>eMarketTurkey, Kullanım Koşulları’nı güncellemek hakkına sahiptir. Yasal açıdan Sizi bağladığından, en güncel Kullanım Koşulları’nı gözden geçirmek amacı ile bu Site’yi belirli aralıklarla ziyaret etmenizi önermekteyiz.</p>
<p><span><b>Sözleşmenin Geçerliliği : </b></span>İşbu Kullanım Koşulları Web Sitesi’ni kullandığınız, Web Sitesi’ne erişim yaptığınız yahut herhangi bir eMarketTurkey Servis ve Hizmetinden yararlandığınız hallerde tarafınızca kabul edilmiş olarak addedilecektir. Burada belirtilen Kullanım Koşulları’nı kabul etmiyorsanız Web Sitesi’ni ve/veya eMarketTurkey Servis ve Hizmetlerini kullanmayınız.</p>
<p><span><b>Ücretli Servisler : </b></span>Aksi açıkça ifade edilmedikçe, ücretli Servis ve Hizmetleri sadece Premium ve Gold Üyelere ve/veya eMarketTurkey tarafından serbestçe belirlenmiş şirket, kurum, üye ve gruplarına yöneliktir.</p>
<p><span><b>Sözleşmenin Bazı Hükümlerinin Geçersizliği : </b></span>Mahkeme Kararlarının iş bu Kullanım Koşulları’nın içerdiği, esaslı olmayan bir hükmün geçersiz olduğuna hükmedilmesi durumunda, söz konusu hükmün geçersizliği, bu Kullanım Koşulları’nın diğer hükümlerinin geçerliliğini etkilemeyecektir.</p>
<p><span><b>Feragat : </b></span>Bu Kullanım Koşulları’nın herhangi birisinden yapılan bir feragat, ilgili koşuldan veya diğer bir koşuldan yapılan feragatin devamı niteliğinde olacağı veya ilgili koşuldan ileride de feragat edildiği şeklinde yorumlanmayacaktır.</p> 
<p><span><b>İçeriğin Internet Üzerinde Yayınlanması : </b></span>eMarketTurkey, eMarketTurkey İçeriği’nin Türkiye dışında yasal olarak görüntülenebileceğine veya erişim yapılabileceğine ilişkin hiç bir beyan veya taahhütte bulunmamaktadır. eMarketTurkey İçeriği’ne yapılacak erişimler belirli kişiler için veya belirli ülkelerde yasal olmayabilir.</p> 
<p><span><b>Erişim Sorumluluğu : </b></span>Bir eMarketTurkey Sitesi’ne erişim yapıyorsanız, sorumluluğu Size ait olmak üzere bunu yapmaktasınız ve bulunduğunuz bölgenin yasalarına uygun hareket etmekten sorumlu bulunmaktasınız.</p> 

<p><span><b>İçerik</b></span></p>

<p>Web Sitesi’nde veya Web Sitesi aracılığıyla sunduğunuz, ilan ettiğiniz veya teşhir ettiğiniz bütün bilgiler, veriler, metinler, yazılımlar, forumlar, müzik ve ses unsurları, fotoğraflar, grafikler, videolar, reklamlar, mesajlar veya eser niteliğindeki diğer materyallerin ("Kullanıcı İçeriği"), söz konusu Kullanıcı İçeriği’nin alındığı kişinin münhasır sorumluluğunda olduğunu kabul etmektesiniz.</p> 
<p>eMarketTurkey, Kullanıcı İçerikleri üzerinde herhangi bir mülkiyet hakkına veya kontrole sahip bulunmamaktadır. Siz veya varsa üçüncü kişiler Web Sitesi’nde veya Web Sitesi aracılığıyla sunduğunuz, ilan ettiğiniz veya teşhir ettiğiniz Kullanıcı İçeriği’nden doğan bütün patentler, ticari markalar ve fikri ve snai mülkiyet haklarının sahibi olmaya devam edeceksiniz ve söz konusu hakların korunmasından münhasıran sorumlu bulunmaktasınız.</p> 
<p>Web Sitesi’nde veya Web Sitesi aracılığıyla Kullanıcı İçeriği’ni sunmak, ilan etmek veya teşhir etmek suretiyle, söz konusu Kullanıcı İçeriği’ni eMarketTurkey aracılığıyla çoğaltılması, uyarlanması, dağıtımının yapılması ve yayımlaması için eMarketTurkey’a dünya genelinde geçerli, münhasır olmayan ve lisans ücreti ödenmesini gerektirmeyen süre, yer ve muhteva açısından bir sınırlama olmaksızın, bir lisans vermektesiniz. Ayrıca umuma açık olması öngörülen Kullanıcı İçeriği’ni sunmak, ilan etmek veya teşhir etmek suretiyle, eMarketTurkey ve hizmetlerinin tanıtımını yapması maksadıyla (işleme, çoğaltma, yayma, umuma arz, temsil olarak Fikir ve Sanat Eserleri Kanunu kapsamında sayılan mali hakları içerecek şekilde) söz konusu Kullanıcı İçeriği’ni çoğaltması, uyarlaması, dağıtımını yapması ve yayımlaması için eMarketTurkey’a dünya genelinde geçerli, münhasır olmayan ve lisans ücreti ödenmesini gerektirmeyen bir lisans vermektesiniz.</p> 
<p>eMarketTurkey, söz konusu Kullanıcı İçeriği’nin eMarketTurkey’dan kaldırılmasından sonra ticari açıdan makul bir süre içinde bu kullanıma son verebilecektir. eMarketTurkey, takdir hakkı yalnızca kendisine ait olmak üzere, herhangi bir Kullanıcı İçeriği’ni kabul etmeyi, ilan etmeyi, teşhir etmeyi veya iletmeyi reddetme hakkını saklı tutmaktadır. Kullanıcılar Web Sitesi’ndeki her türlü sohbet, dosya paylaşımı ve kendi rızaları ile oluşturdukları her türlü kişisel profil bilgilerinin başkalarının görüntülemesini kendi rızaları ile kabul etmiştir. Bu bağlamda Site üzerindeki bu platformlarda 3.kişiler ile konuşulan sohbet, doküman, resim gibi araçlardan doğacak üçüncü kişi taleplerinden hiçbir şekilde eMarketTurkey sorumlu tutulamaz.</p>
<p>Kullanıcı İçeriği’ni Web Sitesi’nin umuma açık bir alanında teşhir etmeniz durumunda, diğer Kullanıcılar’a, söz konusu Kullanıcı İçeriği’ne kişisel kullanım için erişimde bulunmaları, teşhir etmeleri, görüntülemeleri, saklamaları ve çoğaltmaları için izin vermektesiniz. eMarketTurkey, bu Kullanım Koşulları’nı, meri yasaları, mevzuatları ve kuralları ihlal eden, kötüleyici, rahatsız edici, hakaret edici yahut yasadışı nitelikte olan veya bir eMarketTurkey sitesinin Kullanıcılarının haklarını ihlal eden veya emniyetlerine zarar veren veya tehdit eden veya işbu Kullanım Koşulları’nda belirtilen sakıncalı hususları içeren, Kullanıcı içeriklerini inceleyebilecek ve kaldırabilecektir. Bu Kullanım Koşulları’nın veya meri yasalar, mevzuatlar ve kuralların ihlal edilmesi durumunda, eMarketTurkey, Kullanıcıları feshetme ve Web Sitesi’ne erişimde bulunmalarını ve/veya eMarketTurkey Hizmetleri’ni kullanmalarını engelleme hakkını saklı tutmaktadır. Bu halde eMarketTurkey’ın zarara ilişkin yasal talep hakları mahfuzdur. eMarketTurkey, takdir hakkı yalnızca kendisine ait olmak üzere, bir Kullanıcı İçeriği’nin eMarketTurkey’ı bir mali yükümlülük altına sokabileceğini, eMarketTurkey’ın markasına veya imajına zarar verebileceğini veya eMarketTurkey’ın Kullanıcıları kaybetmesine veya (kısmen veya tamamen olmak üzere) internet hizmet sağlayıcılarının veya diğer tedarikçilerinin hizmetlerini kaybetmesine neden olabileceğini tespit etmesi durumunda, söz konusu Kullanıcı İçeriği ile ilgili olarak uygun olduğunu düşündüğü herhangi bir işlemde bulunabilecektir.</p>
<p>Tam zamanlı veya yarım zamanlı olarak iş arayan kişilere hitap eden mevcut bir iş pozisyonu için yapılmış doğrudan bir talep, reklam veya işe yerleştirme olarak yorumlanabilecek olan bilgileri eMarketTurkey Topluluklarına sunulmuş olan bir Kullanıcı İçeriğine dahil edemezsiniz. Ayrıca;  eMarketTurkey Topluluğu, Kullanıcılarını ticari reklamlar veya taleplerden korumak üzere, bir Kullanıcının diğer Kullanıcılara gönderebileceği elektronik postaların veya diğer mesajların sayısını ve büyüklüğünü, takdir hakkı yalnızca kendisine ait olmak üzere kısıtlama hakkını saklı tutmaktadır.</p>
</div>

<h5 id="5-1">5.1. Yasaklı Ürünler</h5>
<div>
<p>eMarketTurkey ve/veya www.emarketturkey.com tarafından Site'de verilen Servis ve Hizmet'ler kapsamında, bazı ürünlerin satışa arzı eMarketTurkey ve/veya www.emarketturkey.com tarafından yasaklanmıştır.</p> 
<p>Yasaklı Ürünler'in Satıcı tarafından Site'de satışa arz edilmesi ve bu durumun eMarketTurkey ve/veya www.emarketturkey.com tarafından tespit edilmesi halinde, eMarketTurkey ve/veya www.emarketturkey.com, ilgili Yasaklı Ürünler'in satışa arz bilgilerini ve satış süreçlerini durdurma ve/veya bu ürünlere ilişkin listeleme ücretlerini iade etmeme ve/veya Yasaklı Ürünler'i satışa arz eden Satıcı'nın üyeliğine geçici veya kalıcı olarak son verme ve/veya Kullanıcı sözleşmesini ihbara gerek olmaksızın feshetme haklarını saklı tutmaktadır.</p>
<p>eMarketTurkey ve/veya www.emarketturkey.com, gerekli gördüğü durumlarda (özellikle çalıntı, kaçak veya sahte ürün satışlarında), önceden uyarıda bulunmaksızın ilgili hakkında gerekli yasal işlemin yapılması amacıyla, Cumhuriyet Savcılığı'na ve ilgili denetleme ve düzenleme kuruluşlarına şikâyet veya ihbarda bulunabilir. Kullanıcı, Yasaklı Ürünler'in satışıyla bağlantılı olarak, eMarketTurkey ve/veya www.emarketturkey.com ihbarı ve/veya bilgi temini sonucu zarara uğraması durumunda, eMarketTurkey ve/veya www.emarketturkey.com'u hiç bir isim veya sıfatla sorumlu tutmamayı ve her ne suretle olursa olsun tazminat talep etmemeyi kabul, beyan ve taahhüt eder. Satıcı, aynı sebepten kaynaklanarak üçüncü kişi veya kurumlardan gelebilecek tazminat taleplerinde, eMarketTurkey ve/veya www.emarketturkey.com'un, doğabilecek tazminat ve avukatlık ücretleri dahil fakat bunlarla sınırlı olmaksızın, tüm dava ve diğer yükümlülüklerini karşılamayı peşinen kabul, beyan ve taahhüt eder. Satıcı, Site'de sergilediği ürünlerin tamamının, Türkiye Cumhuriyeti gümrük mevzuatı ve rejimine uygun olarak gümrük işlemine tabi tutulmuş ve serbest dolaşıma girmiş ürünler olduğunu kabul, beyan ve taahhüt eder.</p>
<p>Site'de yürürlükteki gümrük mevzuatı ve rejimine aykırı olarak veya hiç gümrük işlemine tabi tutulmaksızın, Türkiye'ye giriş yapmış ürünlerin sergilenmesi ve satışı yasaktır. Yurt dışında yerleşik Kullanıcı'ların, gümrük işlemine tabi tutularak serbest dolaşıma girmemiş ürünleri Site'de satışa sunmaları ve satmaları yasaktır. eMarketTurkey ve/veya www.emarketturkey.com, gümrük işlemine tabi tutulmamış ürünleri, doğrudan yurtdışı satışı olarak satmak teşebbüsünde bulunan Kullanıcı'ların sergilediği ürünleri, haberdar olduğu anda iptal eder ve bu tür teşebbüste bulunanlara listeleme ücreti iadesi yapmaz.</p>
</div>

<h5 id="5-2">5.2. Garantiden Feragat</h5>
<div>
<p>İşbu Kullanım Koşulları’nda eMarketTurkey’in sorumsuzluğuna ilişkin tesis edilen hükümlerde yahut sorumluluğunu sınırlayan hükümlerde, eMarketTurkey’in ağır kusuru ve hile hali istisnadır. Kullanıcılar, sorumlu olduklarını kabul ettikleri konulara ilişkin olarak eMarketTurkey’e yöneltilebilecek taleplerinden feragat etmektedir. eMarketTurkey’in sorumlu olmadığı belirtilen hususlarda, eMarketTurkey’in muhatap olarak alınmasi halinde eMarketTurkey tüm talep ve/veya ödemeleri ferileri ile kullanıcılara rücu edebilecektir.</p>
</div>

<h5 id="5-3">5.3. Mali Yükümlülüğün Sınırlandırılması</h5>
<div>
<p>WEB SİTESİ VEYA EMARKETTURKEY İÇERİĞİNİ KULLANMANIZ NEDENİYLE EMARKETTURKEY’IN SAHİP OLACAĞI AZAMİ MALİ SORUMLULUK, DAVA GEREKÇESİNE BAKILMAKSIZIN (DAVANIN KESİN OLARAK EMARKETTURKEY ALEYHİNE SONUÇLANMASI KAYDI İLE), 1US$ TUTARINI GEÇMEYECEKTİR.</p>
</div>

<h5 id="5-4">5.4. Talep ve Şikayet</h5>
<div>
<p>Sunduğumuz servis ve hizmetlere ilişkin talep ve şikayetlerinizi aşağıdaki iletişim bilgilerinden tarafımıza iletebilirsiniz:</p>
<p>Şirket adı  :</p>
<p>Adres   :</p>
<p>Telefon     :</p> 
<p>Email Adresi :</p>
</div>

<h5 id="6">6. Gizlilik</h5>
<div>
<p>eMarketTurkey ve/veya www.emarketturkey.com, Kullanıcı'lara ilişkin bilgileri, gizlilik politikası bölümündeki düzenlemelere uygun olarak üyelerine yönelik araştırmalarda, istatistikî verilerin temininde ve sair ihtiyaç duyacağı alanlarda kullanabilir. eMarketTurkey ve/veya www.emarketturkey.com, Kullanıcı'lara ait gizli bilgileri, Kullanıcı Sözleşmesi'nde aksine müsaade edilen durumlar haricinde, üçüncü kişi ve kurumlara kullandırılmaz.</p>
</div>

<h5 id="7">7. Fikri Mülkiyet Hakları</h5>
<div>
<p>Site'nin (tasarım, metin, imge, html kodu ve diğer kodlar da dâhil ve fakat bunlarla sınırlı olmamak kaydıyla) tüm elemanları (eMarketTurkey ve/veya www.emarketturkey.com'un telif haklarına tabi çalışmalar) eMarketTurkey ve/veya www.emarketturkey.com'a ait olarak ve/veya eMarketTurkey ve/veya www.emarketturkey.com tarafından üçüncü bir kişiden alınan lisans hakkı altında kullanılmaktadır.</p> 
<p>Kullanıcı'lar, e MarketTurkey ve/veya www.emarketturkey.com Servis ve Hizmet'lerini, eMarketTurkey ve/veya www.emarketturkey.com bilgilerini ve eMarketTurkey ve/veya www.emarketturkey.com'un telif haklarına tabi çalışmalarını yeniden satamaz, paylaşamaz, dağıtamaz, sergileyemez, çoğaltamaz, bunlardan türemiş çalışmalar yapamaz veya hazırlayamaz, veya başkasının eMarketTurkey ve/veya www.emarketturkey.com'un Servis ve Hizmet'lerine erişmesine veya kullanmasına izin veremez; aksi takdirde, lisans verenler de dâhil ancak bunlarla sınırlı olmaksızın, üçüncü kişilerin uğradıkları zararlardan dolayı eMarketTurkey ve/veya www.emarketturkey.com'dan talep edilen tazminat miktarını ve mahkeme masrafları ve avukatlık ücreti de dahil ancak bununla sınırlı olmamak üzere diğer her türlü yükümlülükleri karşılamakla sorumlu olacaklardır.</p>
<p>eMarketTurkey ve/veya www.emarketturkey.com'un, Servis ve Hizmet'leri, bilgileri, telif haklarına tabi çalışmalar, ticari markaları, ticari görünümü veya Site vasıtasıyla sahip olduğu her tür maddi ve fikri mülkiyet hakları da dâhil tüm malvarlığı, ayni ve şahsi hakları, ticari bilgi ve know-how'a yönelik tüm hakları saklıdır.</p>
<h5>Üçüncü Kişilerin Fikri ve Sınai Mülkiyet Haklarını İhlal Eden Kullanıcıların Üyelikten Çıkarılmalarına İlişkin Politika :</h5>
<p>eMarketTurkey üçüncü kişilerin fikri mülkiyetine saygı duymaktadır, bu nedenle Kullanıcılarımızın ve içerik ortaklarımızın da aynı şekilde davranmasını talep etmekteyiz. Fikri ve sınai mülkiyet haklarına tabi eserlerin yetkisiz olarak ilan edilmesi, çoğaltılması, kopyalanması, dağıtılması, değiştirilmesi, işlenmesi, umuma teşhir edilmesi veya umum önünde ifası ve mevzuatta belirtilen diğer izinsiz tasarruflar, ilgili hak sahiplerinin haklarının bir ihlalini teşkil etmektedir. Web Sitesi’ni kullanmanızın bir koşulu olarak, üçüncü kişilerin fikri ve sınai mülkiyet haklarını herhangi bir şekilde ihlal etmek maksadıyla Web Sitesi’ni kullanmamayı kabul etmektesiniz. eMarketTurkey, üçüncü kişilerin fikri ve sınai haklarını sürekli olarak ihlal etmekte olan Kullanıcılar’ın hesaplarını kapatma ve bu Kullanıcıların Web Sitesi’ne erişimde bulunmalarını bloke etme yahut askıya alma hakkını diğer yasal hakları ile birlikte saklı tutmaktadır.</p>
<p>Kullanıcılar Site’yi kullanırken Türk Ceza Kanunu, Türk Ticaret Kanunu, Borçlar Kanunu, Fikir ve Sanat Eserleri Kanunu, Marka ve Patent Haklarının Korunması ile ilgili kanun hükmünde kararnamesi ve halihazırda yürürlükte olan ilgili her türlü mevzuat hükümleri ile ileride yürürlüğe girecek olan mevzuata ve eMarketTurkey’in Site’ye ilişkin olarak yayımlayacağı bildirimlere uymayı kabul eder. Bildirimlere ve yasalara aykırı kullanım sebebiyle doğabilecek hukuki, cezai ve mali her türlü sorumluluk Kullanıcı’ya aittir. eMarketTurkey’ın bu sorumluluk nedeni ile uğrayacağı her türlü zararı Kullanıcı’ya fer’ileri ile birlikte rücu hakkı saklıdır.</p>
</div>

<h5 id="8">8. Sözleşme Üzerinde Yapılacak Değişiklikler</h5>
<div>
<p>eMarketTurkey ve/veya www.emarketturkey.com, tamamen kendi takdirine bağlı ve tek taraflı olarak, işbu Kullanıcı Sözleşmesi'ni, uygun göreceği herhangi bir zamanda, Site'de ilan etmek suretiyle değiştirebilir. İşbu Kullanıcı Sözleşmesi'nin değişen hükümleri, ilan edildikleri tarihte geçerlilik kazanacak; geri kalan hükümler, aynen yürürlükte kalarak hüküm ve sonuçlarını doğurmaya devam edecektir. İşbu Kullanıcı Sözleşmesi, Kullanıcı'nın tek taraflı beyanları ile değiştirilemez.</p>
</div>

<h5 id="9">9. Devir ve Temlik</h5>
<div>
<p>Kullanıcı, İşbu Kullanım Koşulları’ndan doğan hak ve yükümlülüklerini üçüncü kişilere devir ve temlik etmeyeceğinizi beyan ve kabul eder. Ayrıca herhangi bir www.emarketturkey.com sitesini yetkisiz ticari kullanım konusu yapmamayı kabul edecektir.</p>
</div>

<h5 id="10">10. Mücbir Sebepler</h5>
<div>
<p>Hukuken 'mücbir sebep' sayılan tüm hallerde, eMarketTurkey ve/veya www.emarketturkey.com, işbu Kullanıcı Sözleşmesi ile belirlenen yükümlülüklerinden herhangi birini geç veya eksik ifa etme veya ifa etmeme nedeniyle yükümlü değildir. Bu ve bunun gibi durumlar, eMarketTurkey ve/veya www.emarketturkey.comiçin, gecikme, eksik ifa etme veya ifa etmeme veya temerrüt addedilmeyecek veya bu durumlar için, eMarketTurkey ve/veya www.emarketturkey.com'dan herhangi bir nam altında tazminat talep edilemeyecektir.</p>
<p>"Mücbir sebep" terimi, doğal afet, isyan, savaş, grev, iletişim sorunları, altyapı ve internet arızaları, elektrik kesintisi ve kötü hava koşulları da dâhil ve fakat bunlarla sınırlı olmamak kaydıyla, ilgili tarafın makul kontrolü haricinde ve gerekli özeni göstermesine rağmen önleyemediği, kaçınılamayacak olaylar olarak yorumlanacaktır.</p>
</div>

<h5 id="11">11. İhtilafların Çözümü</h5>
<div>
<p>İşbu Kullanıcı Sözleşmesi'nin uygulanmasında, yorumlanmasında ve hükümleri dâhilinde doğan hukuki ilişkilerin yönetiminde T.C. Hukuk Kuralları uygulanacaktır. İşbu Kullanıcı Sözleşmesi'nden doğan veya doğabilecek her türlü ihtilafın hallinde, İzmir Mahkemeleri ve İcra Daireleri yetkilidir.</p>
</div>

<h5 id="12">12. Fesih</h5>
<div>
<p>Kullanıcı, Ücretsiz Üyeliği dilediği zaman herhangi bir gerekçe olmaksızın feshedebilir.  Fesih bildirimi, Kullanıcı’nın kayıtlı adını ve Kullanıcı’nın eMarketTurkey Web sitelerinden birinde kayıtlı bir e-posta adresini içerecektir.</p>
<p>Hem Kullanıcı hem eMarketTurkey, Gold ve Premium Üyeliği, Kullanıcı tarafından kayıt sürecinde seçilen minimum çalışma zamanının sonunda ya da söz konusu minimum çalışma zamanının dolmasını takiben herhangi bir yenileme döneminin sonunda, on dört (14) işgünü önceden bildirimde bulunmak kaydıyla gerekçesiz feshedebilir.</p> 
<p>Hem Kullanıcı hem de eMarketTurkey, faks,email, telefon veya mektup yoluyla da fesih bildiriminde bulunabilirler. Fesih bildirimi, Kullanıcı’nın kayıtlı adını ve Kullanıcı’nın eMarketTurkey Web sitelerinde kayıtlı e-posta adresini içerecektir.</p> 
<p>İşbu Kullanıcı Sözleşmesi, Kullanıcı Site'ye üye olduğu sürece yürürlükte kalacak ve taraflar arası hüküm ve sonuçlarını doğurmaya devam edecek; Kullanıcı'nın üyelik süresinin dolması veya geçici veya kalıcı olarak üyeliğinin durdurulması hallerinde sona ermiş sayılacaktır.</p>
<p>eMarketTurkey ve/veya www.emarketturkey.com, Kullanıcı'ların işbu Kullanıcı Sözleşmesi'ni ve/veya Site içinde yer alan kullanıma, üyeliğe ve Servis ve Hizmet'lere ilişkin benzeri kuralları ihlal etmeleri durumunda ve özellikle <b>aşağıda sayılan hallerde, sözleşmeyi tek taraflı olarak feshedebilecek ve Kullanıcı'lar, fesih sebebiyle, eMarketTurkey ve/veya eMarketTurkey.com'un uğradığı tüm zararları tazmin etmekle yükümlü olacaktır.</b></p>
<ul>
<li>Kullanıcı’nın geçerli herhangi bir kanun hükmüne uymaması,</li>
<li>Kullanıcı’nın özellikle işbu  sözleşmeden doğan bir yükümlülüğü ihlal etmesi,</li>
<li>Kullanıcı’nın çevrimiçi varlığının eMarketTurkey Web sitelerinde sunulan hizmetlerin ününe esaslı zarar vermesi (yüz kızartıcı ve ağır suçlar sebebiyle herhangi bir mahkumiyet kararının verilmesi),</li>
<li>Kullanıcı’nın başka herhangi bir kullanıcıya veya kullanıcılara zarar vermesi, üçüncü kişilerin haklarına tecavüz eden ve/veya etme tehlikesi bulunan fillerde bulunması,</li>
<li>Yasaklı Ürünler olarak belirtilen ürünlerin Satıcı tarafından Site'de satışa arz edilmesi ve bu durumun eMarketTurkey ve/veya www.emarketturkey.com tarafından tespit edilmesi,</li>
<li>Kullanıcı'nın, herhangi bir yöntem kullanarak, Site'nin işleyişini manipüle edecek davranışlarda bulunması,</li>
<li>Kullanıcı'nın kendisi için oluşturulmuş Kullanıcı profilini başkasına devretmesi veya kullanıma açması.</li>
</ul>
</div>

<h5 id="13">13. Tazminat</h5>
<div>
<p>İş bu Kullanım Koşulları’nı ihlal etmenizden kaynaklanan veya kaynaklandığı iddia edilen, yargılama giderleri ve muhasebe ücretleri de dahil fakat bunlarla sınırlı olmamak üzere, bütün tazmin taleplerine, davalara veya ödemelere karşı eMarketTurkey’ı, yan kuruluşlarını, bunların memurlarını, yöneticilerini, çalışanlarını ve acentelerini müdafaa etmeyi, bu kişileri tazmin etmeyi kabul etmektesiniz. eMarketTurkey bu türden tazmin talepleri, davalar veya takibatları derhal Size bildirecektir.</p>
</div>

<h5 id="14">14. Sözleşmenin Yürürlülüğü</h5>
<div>
<p>Kullanıcı, Site'ye üye olarak, Kullanıcı Sözleşmesi'nin tamamını okuduğunu, içeriğini bütünü ile anladığını ve tüm hükümlerini onayladığını kabul, beyan ve taahhüt eder.</p> 
<p>Kullanım Şartları Kullanıcı tarafından okunarak kabul edilmiş ve ilk oturum açtığı tarihte yürürlüğe girmiştir.</p>
</div>

<div class="hrsplit-1"></div>
