all: 
    propel: 
        class:   sfPropelDatabase 
        param: 
            phptype: oracle
            host: 
            dsn: oci:dbname=EMTBAG
            database: 
            username: geek 
            password: geeker
            encoding: utf8
            persistent: true
