<div class="privacy-policy">
<div>
<em>(22 Temmuz 2011 tarihinde güncellenmiştir)</em>
<div class="hrsplit-2"></div>
<p>Bu, <b>eMarketTurkey.com</b> Sitesini ("Site") kullanımınızı ve <b>eMarketTurkey.com</b> ile ilgili Premium Servisleri sağlayan bağlı kuruluşları (topluca "<b>eMarketTurkey.com</b>" veya "biz" olarak anılır) tarafından toplanan bilgilerinizin toplanması, kullanılması, transferi ve işlenmesini yöneten Gizlilik Politikasıdır. Bu Siteyi kullanarak aşağıda belirtilen Gizlilik Politikamıza rıza gösteriyorsunuz.</p>
<p><b>eMarketTurkey.com</b> gizliliğinizi koruma yönünde kesin bir taahhütte bulunur. Web Sitemizi ziyaret eden kullanıcıların kabul etmek zorunda olduğu Şartlar ve Koşulların bir parçası olan aşağıdaki politika bilgilerinizin nasıl işlem gördüğüne dair ayrıntıları sağlar. Bu politika ileride değişikliğe tabi olabilir. Ancak böyle bir durumda sizi bilgilendirecek ve onayınızı isteyeceğiz.</p>
<p><b>eMarketTurkey.com</b> sitesini Dünya çapındaki arkadaşlarınız, kişiler, şirketler ve kuruluşlarla bilgi paylaşımını kolaylaştırmak için hazırladık. Dünyadaki herkesin <b>eMarketTurkey.com</b> sitesinde paylaştığınız bilgilerinize sahip olmasını istemeyebileceğinizi anlıyoruz; bilgilerinizin denetimini size vermemizin nedeni bu. Varsayılan gizlilik ayarlarımız ağlarınızdaki profilinizde görüntülenen bilgileri sınırlar ve hakkında size bilgi verdiğimiz diğer makul topluluk sınırlamalarına sahiptir.</p>
<p>Kendi kişisel ve diğer bilgileriniz üzerinde denetiminiz olması gerekir. <b>eMarketTurkey.com</b> bilgilerinizi çevrenizdeki arkadaşlarınız, kişiler, şirketler ve kuruluşlarla paylaşmanızda size yardımcı olur. İrtibat bilgileri, kişisel bilgiler ve şirket(ler) ile ilgili bilgiler, resimler, özgeçmişler ve katıldığınız gruplar dahil olmak üzere profilinize ne gibi bilgiler koyacağınızı siz seçersiniz. Ayrıca Gizlilik Ayarları sayfasındaki gizlilik ayarları aracılığıyla bu bilgileri paylaşacağınız kullanıcıları da denetlersiniz.</p>
<p>Başkalarının paylaşmak istediği bilgilere erişiminiz olmalıdır. Ortalıkta bulunabilen bilgi miktarı giderek artıyor ve hangilerinin sizinle, arkadaşlarınızla ve çevrenizdeki kişiler ve şirketlerle ilgili olduğunu bilmek isteyebilirsiniz. Bu bilgileri kolayca elde etmenizde size yardımcı olmak istiyoruz.</p>
<p>Bu bilgileri nasıl ve kiminle paylaşacağınızı denetlemeniz için gerekli gizlilik araçlarını size sağlamak istiyoruz. Herhangi bir sorunuz veya düşünceniz olursa, lütfen Gizlilik Yardımı sayfamıza bir göz atın.</p>
<p><b>eMarketTurkey.com</b> sitesinde bizler kişisel bilgilerinize ilişkin iyi gizlilik uygulamalarına büyük önem veriyoruz. İş arayan, müşteri, satıcı, tedarikçi, imalatçı veya ziyaretçi olarak sadakatiniz önemlidir ve bu politikada açıklandığı gibi gizliliğinize gösterdiğimiz özenin <b>eMarketTurkey.com</b> ile yaşayacağınız deneyimin keyifli ve hoşnut edici kılmaya olan taahhüdümüzü gözler önüne sereceğini umuyoruz.</p>
<p><b>eMarketTurkey.com</b> sitesinde Web sitemizi ziyaret eden ve çevrimiçi hizmetlerimizi kullanan herkesin gizliliğine saygı gösterilmesine karşın, iş arayanlar, müşteriler, imalatçılar, tedarikçiler, satıcılar, vb. dahil olmak üzere ziyaretçilerimizden bilgi topluyoruz. Bu Gizlilik Politikası <b>eMarketTurkey.com</b> Web siteyle olan etkileşiminizi ve <b>eMarketTurkey.com</b>'un çevrimiçi hizmetlerine kaydolmanızı ve bu hizmetleri kullanmanızı yönetir. Bu Gizlilik Politikasında ve Kullanım Şartlarımızda belirtilenler dışında, üyelerimiz ve ziyaretçiler hakkındaki kişisel olarak saptanabilir bilgileri izinleri olmaksızın yayınlamıyoruz.</p>
<p>Hizmetleri kullanmanızın bu Gizlilik Politikasını kabul ettiğiniz anlamına geldiğine dikkat edin. Bu Politikayı kabul etmiyorsanız, lütfen Hizmetleri kullanmayın. Bu Politikadaki değişikliklerden sonra Hizmetleri kullanmaya devam etmeniz, söz konusu değişiklikleri kabul ettiğiniz anlamına gelecektir; bu nedenle lütfen bu sayfaya yer imi koyun ve düzenli aralıklarla inceleyin.</p>
</div>

<h5>Topladığımız Bilgiler</h5>
<div>
<p>Kayıt Bilgileri: Sitenin Kayıtlı Kullanıcısı haline gelmek için kaydolurken adınız, adresiniz, telefon/faks numaranız, e-posta adresiniz ve diğer kişisel bilgileriniz ile işiniz hakkındaki bilgiler gibi bilgileri ("Kayıt Bilgileri") sağlamanızı gerektiren bir kayıt formunu doldurmanız istenecek.</p>
<p>Yayınlanacak Bilgiler: “<b>eMarketTurkey.com</b>” sitesine yayınlama araçları aracılığıyla Sitede yayınlanacak, Şirket Profili, Ürün Katalogu, İş Gelişimleri ve herhangi bir tartışma forumu dahil olan ancak bunlarla sınırlı kalmayan herhangi bir bilgi verirseniz, söz konusu bilgilerin ("Yayınlanacak Bilgiler") yayınlanmasına rıza gösterdiğiniz kabul edilir.</p>
<p>İstatistik Bilgileri: Buna ek olarak Sitemiz ve Kullanıcılar hakkında IP adresleri, tarayıcı yazılımı, işletim sistemi, görüntülenen sayfalar, oturum sayıları, benzersiz ziyaretçiler ve bunun gibi toplu istatistik bilgilerini topluyoruz. ("İstatistik Bilgileri").</p>
<p>Kayıt Bilgileri: Yayınlanacak Bilgiler, Ödeme Bilgileri, İstatistik Bilgiler ve çerezler yada her türlü başka yolla sizden toplayabileceğimiz tüm bilgiler topluca "Toplanan Bilgiler" olarak anılacaktır.</p>
<p>Hesap Bilgileri: <b>eMarketTurkey.com</b> sitesindeki hesabınızda bulunan şirket adınız, adresiniz, irtibat kurulacak kişi, telefon numarası, faks numarası, e-posta, vb. gibi bilgilerin tümünü topluyoruz. Bu, sizinle <b>eMarketTurkey.com</b> arasındaki anlaşmayı yürürlüğe koymak, potansiyel ticari ortaklar, iş arayanlar tarafından erişilebilir olmanızı sağlamak ve hesabınızla ilgili sorunları gidermek içindir.</p>
<p>Gizli Bilgiler: Hesap bilgilerinizin yanı sıra, çerezler, IP adresleri, vb. dahil olmak üzere ancak bunlarla sınırlı kalmayacak şekilde Web sitemize göz attığınızda veya sitemizi ziyaret ettiğinizde kaydedilen bilgileri de topluyoruz. Bu bilgiler sizi tespit etmek için kullanılmıyor, izinsiz giren yazılımcılar (hacker) tarafından yapılan saldırılardan kaçınmak için zorunlu olarak ve kullanıcılar kişiselleştirilmiş içerik hizmeti sunmak amacıyla yapılıyor. Ek olarak kapsamlı istatistik analizini işleyerek hizmetimizi kolaylaştıracak daha da etkili özellikleri sizlere sağlamaya gayret gösteriyoruz. <b>eMarketTurkey.com</b> sitesini ziyaret edebilmeniz için tarayıcınızın çerezleri kabul edecek şekilde yapılandırılmış olması gerekir.</p>
<p>Kişisel Olarak Saptanabilen Bilgiler:  Bir profili doldurduğunuz, özgeçmişinizi verdiğiniz, yeni bir hesap oluşturduğunuz veya sponsorlu yarışmalar ya da promosyonlar gibi Hizmetlerin bazı alanlarında e-posta adresiniz, adınız, posta kodunuz, mesleğiniz veya iş deneyiminiz gibi kişisel olarak saptanabilen bilgileri bize sağlamanızı isteyebiliriz. Bu gibi durumlarda hangi bilgi öğelerinin gerekli, hangilerinin isteğe bağlı olduğunu belirlemeye çalışacağız.</p>
<p>İş arayanlar yalnızca bu bilgilerin <b>eMarketTurkey.com</b>'un müşterileri tarafından görüntülenmesini istiyorlarsa profillerini ve özgeçmişlerini <b>eMarketTurkey.com</b> sitesine koymalıdır. İş arayanlar diledikleri zaman hesaplarında oturum açarak ve profillerinin durumunu değiştirerek profillerinin ve özgeçmişlerinin <b>eMarketTurkey.com</b>'un müşterileri tarafından aranabilir olmamasını tercih edebilirler veya bu mümkün olmadığında <b>eMarketTurkey.com</b> ile   yoluyla bağlantı kurabilirler ve biz de değişikliği onlar için yaparız.</p>
<p>Ayrıca iş arayanlar profillerinin <b>eMarketTurkey.com</b> müşterileri tarafından yalnızca gizlilik esasına göre aranabilir olmasını tercih edebilirler. Bu durumda kullanıcı adı ve irtibat bilgileri <b>eMarketTurkey.com</b>'da arama yapan müşterilere görüntülenmez. Müşteri bir iş fırsatıyla ilgili olarak gizli iş arayanla bağlantı kurmak isterse, iş arayana <b>eMarketTurkey.com</b> sistemi aracılığıyla bir e-posta gönderir. <b>eMarketTurkey.com</b> söz konusu e-postayı iş arayanın e-posta adresine yönlendirir. İş arayanın e-posta adresi doğrudan müşteriye temin edilmez. Bir özgeçmişi gizli olarak koyarken irtibat bilgilerinin özgeçmiş ekine dahil edilmediğinden emin olmak iş arayanın sorumluluğundadır.</p>
<p><b>eMarketTurkey.com</b> sitesinin Hizmetlerin kullanıcılarının eylemlerini denetleyemeyeceğine lütfen dikkat edin. Tüm üyeler ve ziyaretçiler, kişisel olarak saptanabilen bilgileri bir özgeçmiş veya profilde ya da başka bir ortamda ifşa ettiklerinde bu bilgilerin <b>eMarketTurkey.com</b> dışındaki diğer taraflardan o kişiye istenmeyen e-posta gönderilmesi amacıyla toplanabileceğinin ve kullanılabileceğinin farkında olmaları gerekir. Hakkınızdaki veya başka kullanıcılar hakkındaki bilgileri uygun olmayan şekilde toplayan veya kullanan herhangi bir <b>eMarketTurkey.com</b> kullanıcısıyla karşılaşmanız halinde lütfen <?php echo image_tag('layout/gizlilik.post.gif') ?>  ile bağlantı kurun.</p>
<p>Kullanıcı İçeriğini (“<b>eMarketTurkey.com</b>” Kullanım Şartlarında tanımlandığı şekliyle) Siteye koymanızla ilişkili riskler size aittir. Sayfalarınıza erişimi sınırlandıran gizlilik seçeneklerini ayarlamanıza izin vermemize rağmen lütfen hiçbir güvenlik tedbirinin mükemmel veya delinemez olmadığını unutmayın. Sayfalarınızı ve bilgilerinizi paylaşmayı seçtiğiniz diğer Kullanıcıların eylemlerini denetleyemeyiz. Bu nedenle Siteye koyduğunuz Kullanıcı İçeriğinin yetkisiz kişilerce görüntülenmeyeceğini garanti edemeyiz ve etmiyoruz. Sitede bulunan her türlü gizlilik ayarının veya güvenlik tedbirinin atlatılmasından sorumlu değiliz. Kullanıcı İçeriğinizin kopyalarının kaldırılmalarından sonra dahi, önbelleklenmiş veya arşivlenmiş sayfalarda veya diğer Kullanıcıların sizin Kullanıcı İçeriğinizi kopyalamış veya saklamış olması halinde görüntülenebileceğini kabul ediyor ve biliyorsunuz.</p>
<p><b>eMarketTurkey.com</b>'da sağlanan bilgilerin her türlü uygunsuz toplanması veya kötüye kullanımı <b>eMarketTurkey.com</b> Hizmet Şartlarının ihlalidir ve gizlilik yardımı sayfamızda bulunan form aracılığıyla bildirilmesi gerekir.</p>
<p>Sitemiz hakkında bir arkadaşınıza bilgi vermek için davet hizmetimizi kullanmayı seçerseniz, arkadaşınızın e-posta adresi gibi daveti göndermek için gerekli bilgileri sizden isteyeceğiz. Arkadaşınıza kendisini Siteyi ziyaret etmeye davet ettiğinize dair adınıza bir e-posta veya anlık ileti göndereceğiz. <b>eMarketTurkey.com</b> davetiyeler göndermek, davetinizin kabul edilmesi halinde bir arkadaşınızı kaydetmek, gönderdiğiniz davetiyeleri görmenizi sağlamak ve tavsiye programımızın başarısını takip etmek için bu bilgileri saklar. Arkadaşınız bu bilginin veritabanımızdan kaldırılmasını istemek amacıyla <?php echo link_to(__('Bize Ulaşın'), '@contactus') ?> sayfamızdaki form aracılığıyla bizimle bağlantı kurabilir.</p>
<p><b>eMarketTurkey.com</b> size daha yararlı bilgiler ve daha kişiselleştirilmiş bir deneyim sunmak amacıyla aynı zamanda gazeteler, günlük yazılar (blog), anlık ileti hizmetleri ve <b>eMarketTurkey.com</b> hizmetinin diğer kullanıcıları gibi diğer kaynaklardan hizmetin işletilmesi yoluyla (örneğin, fotoğraf etiketleri) hakkınızda bilgi toplayabilir. <b>eMarketTurkey.com</b> sitesini kullanarak kişisel bilgilerinizin Türkiye'ye aktarılmasına ve orada işlenmesine rıza gösteriyorsunuz.</p>
</div>

<h5>Bilgileri Nasıl Kullanabiliriz</h5>
<div>
<p>Toplanan Bilgilerinizi pazarlama ve tanıtım çabalarımızı iyileştirmek, Site kullanımını istatistik açısından incelemek, içeriğimizi ve ürün önerilerimizi iyileştirmek ve Sitemizin içeriğini, düzenini ve hizmetlerini size göre özelleştirmek için kullanıyoruz. Toplanan Bilgilerinizi ayrıca sorunların araştırılması, anlaşmazlıkların giderilmesi ve bizimle olan anlaşmaların yürütülmesi dahil olacak ancak bunlarla sınırlı kalmayacak şekilde bizdeki Hesabınıza servis vermek amacıyla kullanabiliriz. Sitenin ve hizmetlerimizin işletimini desteklemek amacıyla Toplanan Bilgilerinizi bağlı kuruluşlarımıza ve sözleşme altındaki hizmet sağlayıcılarımıza (müşteri hizmetleri gibi) temin edebiliriz. Toplanan Bilgilerin analizine göre bazı toplu bilgileri ortaklarımız, müşterilerimiz, reklam veren taraflar veya potansiyel Kullanıcılarımızla paylaşabiliriz. Toplanan Bilgilerinizi pazarlama kampanyaları, tanıtımlar veya üçüncü taraflar adına reklam mesajları uygulamak için kullanabiliriz ancak bu durumlarda pazarlama, tanıtım veya reklam iletisine yanıt vermezseniz Toplanan Bilgileriniz üçüncü taraflara ifşa edilmeyecektir. Toplanan Bilgileriniz bulunduğunuz ülkenin dışına aktarılabilir, orada saklanabilir, kullanılabilir ve işlenebilir. Başka bir ticari kuruluşla birleşme veya devir olması halinde Toplanan Bilgilerinizi işi edinen kuruluşa devredeceğiz (Böyle bir birleşimin olması halinde yeni birleşen kuruluşun Toplanan Bilgilerinizle ilgili olarak bu Gizlilik Politikasını takip etmesini isteyeceğiz).</p>
<p>Kayıt Bilgileri: Kayıt Bilgilerinizi talep ettiğiniz hizmetleri sağlamak veya <b>eMarketTurkey.com</b>'un ilginizi çekebileceğini belirlediği ek hizmetler hakkında sizinle bağlantı kurmak için kullanabiliriz. Özellikle e-posta adresinizi, posta adresinizi, telefon numaranızı veya faks numaranızı bildirimler, anketler, ürün uyarıları, yeni hizmet veya ürün önerileri ile Sitemizin kullanımıyla ilgili iletişimlerle ilgili sizinle bağlantı kurmak için kullanabiliriz. İç analiz, izleme ve pazarlama kararları için Kayıt Bilgilerinizi temel alan raporlar ve analizler üretebiliriz.</p>
<p>Yayınlanacak Bilgiler: Yayınlanacak Bilgilerinizin tamamı kamuya açık olarak Sitede bulunabilecek ve bu nedenle herhangi bir İnternet kullanıcısı tarafından erişilebilir olacaktır. <b>eMarketTurkey.com</b>'a ifşa ettiğiniz her türlü Yayınlanacak Bilgi kamuya açık bilgi haline gelir ve söz konusu bilgilerdeki her türlü telif hakkından (gizlilik hakları ile telif hakları dahildir ancak bunlarla sınırlı değildir) feragat edersiniz. Bize verdiğiniz Yayınlanacak Bilgilere kişisel veya özel bilgileri dahil etmeye karar verirken dikkatli hareket etmelisiniz.</p>
<p>İstatistik Bilgileri: İstatistik Bilgilerini bilgisayar sunucularımızdaki sorunları tanılamaya ve bu cihazları sürdürmeye yardımcı olmaları, Sitemizi yönetmek ve Sitemizle hizmetlerimizi aldığımız kullanım deseni verilerine göre geliştirmek için kullanıyoruz. İç analiz, izleme ve pazarlama kararları için İstatistik Bilgilerini temel alan raporlar ve analizler üretebiliriz. İstatistik Bilgilerini üçüncü taraflara temin edebiliriz ancak bunu yaparken kişisel olarak saptanabilen bilgileri izniniz olmadan temin etmeyiz.</p>
<p>Şirket adı, adresi, irtibat kurulacak kişi, telefon numarası, vb. gibi bilgiler <b>eMarketTurkey.com</b>'a kamuya açık olarak ve tüm kullanıcılar tarafından erişilebilir halde konulacaktır. Bu nedenle kullanıcılar kendisinin saptanabileceği herhangi bir bilginin yayınlanmasına karar verirken dikkatli davranmalıdırlar. <b>eMarketTurkey.com</b> kullanıcıların sektöre, coğrafi konuma, vb. göre dağılımına ilişkin yukarıdaki bilgiler üzerinde analizler ve araştırmalar yapar. Bu araştırmanın amacı kullanıcılarımıza dair daha iyi bir anlayış elde etmektir ve bu araştırma toplu esasa göre derlenir ve analiz edilir. <b>eMarketTurkey.com</b> analitik sonuçları ticari ortaklarıyla paylaşma hakkını saklı tutar.</p>
<p><b>eMarketTurkey.com</b>'a kaydolduğunuzda kendi profilinizi ve gizlilik ayarlarınızı oluşturursunuz. <b>eMarketTurkey.com</b> sitesinde kişilerle bağlantı kurmanıza olanak tanımak için profil bilgileriniz ile adınız, e-postanız ve fotoğrafınız gizlilik ayarlarınızda belirtilen ağlardaki kişilere görüntülenir. Zaman zaman adınızı ve e-posta adresinizi "<b>eMarketTurkey.com</b>" tarafından sunulan ve değerli bulabileceğinizi düşündüğümüz yeni hizmetlere ilişkin bildirimleri size göndermek için kullanabiliriz.</p>
<p>Profil bilgileri <b>eMarketTurkey.com</b> tarafından temelde hizmete eriştiğinizde size geri sunulacak ve tarafınızdan düzenlenecek ve gizlilik ayarlarını tarafından o bilgilerin görüntülenmesine izin verilen başkalarına sunulacak şekilde kullanılır. Gizlilik ayarlarınızın izin verdiği bazı durumlarda <b>eMarketTurkey.com</b> kullanıcıları profilinize katkıda bulunabilir.</p>
<p><b>eMarketTurkey.com</b>'a sunduğunuz profil bilgileri, gizlilik ayarlarınız aracılığıyla bu bilgilere erişmesine izin verdiğiniz ağlardan en az birine ait olan <b>eMarketTurkey.com</b> kullanıcılarına açık olacaktır. Adınız, ağ adınız ve profil küçük resminiz <b>eMarketTurkey.com</b> ağında yapılan arama sonuçlarında bulunacaktır ve bu sınırlı bilgi parçaları üçüncü taraf arama motorlarına açılabilir. Bu temel olarak arkadaşlarınızın ve şirketlerin sizi bulabilmeleri ve size bir istek gönderebilmeleri içindir. Ancak adınızı aramalarda gören kişiler gizlilik ayarlarınıza göre söz konusu erişime izin verecek şekilde sizinle bir ilişkileri olmadıkça (arkadaş, arkadaşınızın arkadaşı, ağınızın üyesi, vb.) profil bilgilerinize erişemeyecektir.</p>
<p>Kişisel olarak saptanabilir olmayan bilgileri toplu halde daha yüksek kalite, daha kullanışlı Hizmetler oluşturmak için, toplu hizmetler ile ziyaretçilerimizin ve üyelerimizin davranışlarının istatistiksel analizini yaparak ve Hizmetlerin özgül alanlarına ilişkin demografik bilgileri ve ilgileri ölçerek kullanıyoruz. Bu verileri temel alan istatistiksel bilgileri reklam verenlere ve diğer geçerli ve muhtemel iş ortaklarına temin edebiliriz. Aynı zamanda toplu verileri Sitelerine olan bağlantıları gören ve tıklayan kişilerin sayıları konusunda üçüncü tarafları bilgilendirmek için de kullanabiliriz.</p>
<p><b>eMarketTurkey.com</b> kişisel olarak saptanabilen bilgilerinizi satmaz, yeniden satışını veya dağıtımını yapmaz. <b>eMarketTurkey.com</b>'un müşterileri iş arayanların özgeçmişlerinde ve profillerindeki bilgileri yalnızca iş arayanların müşterilerin açık iş pozisyonlarına yönelik niteliklerini değerlendirmek amacıyla kullanabilir. Ancak iş arayanlar <b>eMarketTurkey.com</b> sitesinin bir müşterinin hizmeti gerçekten nasıl kullandığını ile özgeçmiş ve profil bilgilerini nasıl kullandığını denetlemek için hiçbir yolu olmadığının farkında olmalıdırlar. <b>eMarketTurkey.com</b> müşterilerinden birinin kişisel olarak saptanabilir bilgileri uygunsuz şekilde kullandığına inanıyorsanız, lütfen <b>eMarketTurkey.com</b> sitesini <?php echo image_tag('layout/gizlilik.post.gif') ?> yoluyla bilgilendirin.</p>
<p><b>eMarketTurkey.com</b> sitesinin kendi sistemlerini veya ticaretini korumak için gerekli olduğuna makul şekilde kanaat getirdiği herhangi bir ziyaretçi veya üye tarafından verilen veya bunlarla ilgili bilgileri ifşa etme hakkını saklı tuttuğuna lütfen dikkat edin. Özellikle ancak sınırlama olmaksızın bir ziyaretçi veya üyenin Kullanım Şartlarımızı veya diğer yayınlanmış yönlendirici kılavuzları ihlal etmesi veya herhangi bir zararlı, aykırı veya yasadışı faaliyete katıldığı (veya makul olarak katıldığından kuşkulanıldığı) hallerde, celp, müzekkere veya başka bir mahkeme emri olmaksızın söz konusu bilgileri ifşa etme ve mahkeme ve devlet emirlerine, hukuki celplere, keşif taleplerine ve yasaların gerektirdiği başka şekillerde yanıt olarak veya aykırılık isnatlarına yanıt olarak söz konusu bilgileri ifşa etme hakkımızı saklı tutarız. Sunucularımızı veya hizmetlerimizi yasadışı faaliyetler için kimin kullanmış olabileceğinin belirlenmesinde icra makamlarıyla işbirliğinde bulunuruz. Aynı zamanda kuşkulanılan herhangi bir yasadışı faaliyeti soruşturulmak veya kovuşturulmak üzere icra makamlarına bildirme veya kuşkulanılan herhangi bir yasadışı veya aykırı faaliyetle bağlantılı olarak üyeliğinizi askıya alma veya sonlandırma hakkımızı saklı tutarız. Son olarak <b>eMarketTurkey.com</b>, <b>eMarketTurkey.com</b>'un veya bağlı kuruluşlarının varlıklarının veya hisselerinin tamamını veya herhangi bir kısmının devri, satışı, ortak girişimi veya başka bir şekilde devredilmesi veya tasarrufuna sunulmasına yönelik bir anlaşmayla bağlantılı olarak kişisel olarak saptanabilen bilgilerinizi üçüncü bir tarafa devretme, satma, lisansını verme veya başka şekilde transfer etme hakkını saklı tutar.</p>
<p><b>eMarketTurkey.com</b> yukarıdakilere tabi olacak şekilde kişisel olarak saptanabilen bilgileri birkaç yolla şu amaçlar için kullanır:</p>
<ul>
    <li>Hizmetlerin çeşitli özelliklerini tercihlerinize göre özelleştirilmek;</li>
    <li>hangi reklamların veya sponsor mesajlarının ekranda görüneceğini belirlemek;</li>
    <li>ilginizi çekebileceği kanaatinde olduğumuz <b>eMarketTurkey.com</b> davetlerini, ürün duyurularını ve benzerlerini size göndermek (aşağıda belirtildiği gibi bu materyalleri "almamayı" tercih edebilirsiniz);</li>
    <li>sistem durumu güncellemeleri veya sipariş onayları gibi Hizmetleri kullanımınız açısından kritik olan bazı e-posta iletilerini size göndermek (bu iletilerde önemli bilgiler yer aldığından bu tür iletileri "almamayı" tercih edemeyebilirsiniz). Bu tür e-posta iletilerini almayı istemiyorsanız, hesabınızı Hesap Ayarları sayfasından askıya almanız gerekebilir;</li>
    <li>üçüncü taraf reklam verenlerin bazı e-posta iletilerini size göndermek (aşağıda belirtildiği gibi bu iletileri "almamayı" tercih edebilirsiniz). Bu tür üçüncü taraf reklamlar <b>eMarketTurkey.com</b> tarafından reklam veren adına dağıtılır. <b>eMarketTurkey.com</b> e-posta adresinizi reklam verenlere ifşa etmez. Bununla birlikte doğrudan reklam verenle etkileşime geçeceksiniz ve bir reklama "tıklama yoluyla" devam ettiğinizde onların gizlilik politikasına tabi olacaksınız.</li>
    <li><b>eMarketTurkey.com</b> ve/veya sponsorları tarafından bireysel verilerin toplanması amacıyla görüntülenen formları "önceden doldurmak" (bir formun önceden doldurulması hiçbir durumda verilerin hiçbirini bir reklam verene veya üçüncü tarafa otomatik olarak aktarmayacaktır - bu durum yalnızca "Gönder" düğmesini tıklamak gibi kendi isteğinizle söz konusu verilerin aktarılmasını istemeniz halinde bu aktarım gerçekleşecektir).</li>
    <li>hesap bakımı gibi Hizmetlerin işleyişini desteklemek ve kayıt tutma amaçları açısından gerekli olabilecek şekilde.</li>
</ul>
<p>Yukarıda açıklanan durumlara ek olarak <b>eMarketTurkey.com</b> kişisel olarak saptanabilen bilgilerinizi üçüncü taraflara aşağıdaki gibi ifşa edebilir:</p>
<ul>
    <li>Bir iş arayan <b>eMarketTurkey.com</b> sitesine gizli olmayan şekilde bir profil veya özgeçmiş koyduğunda, söz konusu bilgiler <b>eMarketTurkey.com</b> müşterileriyle paylaşılacaktır. (İş arayanların diledikleri zaman hesaplarında oturum açarak ve profillerinin durumunu değiştirerek profillerinin ve özgeçmişlerinin <b>eMarketTurkey.com</b>'un müşterileri tarafından aranabilir olmamasını tercih edebileceklerine veya <b>eMarketTurkey.com</b> ile <?php echo image_tag('layout/gizlilik.post.gif') ?> yoluyla bağlantı kurabileceklerine ve bizim de değişikliği onlar için yapacağımıza dikkat edin).</li>
    <li>Bir iş arayan kendi profilini <b>eMarketTurkey.com</b> müşterileri tarafından yalnızca gizlilik esasına göre aranabilir hale getirmeyi tercih ettiğinde, kullanıcı adı ve irtibat bilgileri <b>eMarketTurkey.com</b> sitesinde arama yapan müşterilere görüntülenmeyecektir. Müşteri gizli iş arayanla herhangi bir iş pozisyonuyla ilgili bağlantı kurmak istediğinde, iş arayana <b>eMarketTurkey.com</b> sistemi aracılığıyla bir e-posta gönderecektir. <b>eMarketTurkey.com</b> bu e-postayı iş arayanın e-posta adresine iletecektir. İş arayanın e-posta adresi doğrudan müşteriye temin edilmez. Bir özgeçmişi gizli olarak koyarken irtibat bilgilerinin özgeçmiş ekine dahil edilmediğinden emin olmak iş arayanın sorumluluğundadır.</li>
    <li><b>eMarketTurkey.com</b>'a sunulan tüm bilgiler taşeronlarımız ve danışmanlarımız ile profesyonel müşavirlerimize (avukatlar veya mali müşavirler gibi) açılacaktır ancak bu yalnızca kendi adımıza hizmetleri yapmaları için gerekli olduğu ölçüde ve yalnızca bir gizlilik sorumluluğuyla yapılacaktır.</li>
</ul>
</div>

<h5>Bilgilerinizin Üçüncü Taraflarla Paylaşılması</h5>
<div>
<p><b>eMarketTurkey.com</b> bilgileri başkalarıyla, ağınızdaki arkadaşlar, kişiler ve şirketlerle paylaşmakla ilgilidir ve diğer kullanıcıların bilgilerinize erişmesini kısıtlayan gizlilik ayarlarını size temin eder. <b>eMarketTurkey.com</b> aracılığıyla arkadaşlarınıza ve ağlara sağladığınız bilgiler seçme olanağını size tanırız. Ağımızın mimarisi ve gizlilik ayarlarınız size bilgilerinize kimin erişimi olduğuna dair bilgilendirilmiş seçim yapma fırsatı tanır. İzniniz olmadan üçüncü taraf pazarlamacılara irtibat bilgilerinizi temin etmeyiz. Bilgilerinizi yalnızca söz konusu bilgileri paylaşmanın şunlara uygun olduğuna kanaat getirdiğimiz sınırlı durumlarda üçüncü taraflarla paylaşırız:</p>
<ul>
    <li>hizmetin sunulması için makul oranda gerekli olması,</li>
    <li>yasal olarak gerekli olması veya</li>
    <li>tarafınızdan izin verilmiş olması.</li>
</ul>
<p><b>eMarketTurkey.com</b> sitesini kullandığınızda koyduğunuz veya üçüncü taraflarla (örneğin bir arkadaş, şirketler veya dünyada birisi) paylaştığınız kişisel bilgiler, özgeçmişler, yorumlar, iletiler, fotoğraflar, videolar, ürünler, hizmetler, pazar listeleri veya diğer bilgiler gibi bazı bilgiler seçtiğiniz gizlilik ayarlarına uygun olarak diğer kullanıcılarla paylaşılabilir. Bu bilgi paylaşımları riski size ait olacak şekilde yapılır. Profilinizde kişisel bilgileri ifşa ederseniz veya yorum, ileti, fotoğraf, video, Pazar listeleri veya diğer öğeleri koyarken bu bilgilerin kamuya açık hale gelebileceğini lütfen unutmayın.</p>
</div>

<h5>Çerezler, Reklamlar ve 3. taraf uygulamaları</h5>
<div>
<p>"Çerezleri" size özgü bilgileri saklamak ve Sitemizi ziyaretlerinizi izlemek için kullanıyoruz. Web sitelerinin kendi kullanıcılarının saptanmasını iyileştirmek için çerezleri kullanması yaygın bir uygulamadır. "Çerez", tarayıcınıza gönderilen ve bilgisayarınızın sabit sürücüsünde saklanan az miktarda bir bilgidir. Bir çerez bilgisayarınızın sabit sürücüsüne yalnızca Sitemize bilgisayarı kullanarak erişim sağladığınızda gönderilebilir. Çerezi devre dışı bırakmaz veya silmezseniz, Sitemize erişmek için aynı bilgisayarı her kullanışınızda Web sunucularımız Sitemizi ziyaretiniz konusunda bilgilendirilecektir ve bunun karşılığında ziyaretinizin ve kullanım şeklinizin bilgisine sahip olacağız. Genel olarak çerezleri sizi saptamak ve yeniden girmemeniz için Kayıt Bilgilerinize, Yayınlanacak Bilgilerinize veya Ödeme Bilgilerinize ulaşmamızı sağlaması; Kullanıcıların kullanımları hakkında istatistiksel bilgileri toplamak; ziyaret etme şekillerini araştırmak ve reklamları Kullanıcıların ilgi alanlarına göre hedeflemek; Kullanıcıların Siteyi ziyaretlerini izlemek ve siparişleri işlemek için ortaklarımıza yardımcı olmak ve tanıtımların ilerleyişini ve bunlara katılımı izlemek için kullanırız.</p>
<p>Bir çerezin kabul edilip edilmeyeceğini ve nasıl kabul edileceğini Siteye erişmekte kullandığınız bilgisayarda kurulu tarayıcıyı yapılandırarak belirleyebilirsiniz. İsterseniz, tarayıcınızdaki bu yapılandırmaları değiştirebilirsiniz. Tarayıcınızdaki tercihleri değiştirerek tüm çerezleri kabul edebilir, bir çerez gönderildiğinde bilgi almayı isteyebilir veya tüm çerezleri reddedebilirsiniz. Tarayıcınızdaki çerez iptal etme özelliğini seçerek tüm çerezleri reddederseniz, Sitemize bilgilerinizi daha sık olarak yeniden girmeniz gerekebilir ve Sitemizin bazı özellikleri kullanılamaz hale gelebilir.</p>
<p><b>eMarketTurkey.com</b>'da görünen reklamlar kimi zaman kullanıcılara doğrudan üçüncü taraf reklam verenler tarafından ulaştırılır. Bu gerçekleştiğinde IP adresinizi otomatik olarak alırlar. Bu üçüncü taraf reklam verenler aynı zamanda bilgisayarınıza çerezler indirebilir veya reklamlarının etkisini ölçmek ve reklam içeriğini kişiselleştirmek için JavaScript ile Web işaretleri gibi diğer teknolojileri kullanabilirler. Bunun yapılması reklamlarının etkisini ölçmek ve reklam içeriğini kişiselleştirmek için size bir reklamı her gönderişinde reklam veren ağın bilgisayarınızı tanımasına olanak tanır. Bu yolla bilgisayarınızı veya tarayıcınızı kullanan kişilerin kendi reklamlarını görmelerini ve hangi reklamların tıklandığını belirlemelerini sağlayacak bilgileri derleyebilirler. <b>eMarketTurkey.com</b>'un üçüncü taraf reklam verenler tarafından yerleştirilebilecek çerezlere erişimi veya bunlar üzerinde denetimi yoktur. Siz onlarla paylaşmayı seçmediğiniz sürece üçüncü taraf reklam verenlerin <b>eMarketTurkey.com</b> sitesinde saklı irtibat bilgilerinize erişimi yoktur.</p>
<p>Bu gizlilik politikası çerezlerin <b>eMarketTurkey.com</b> tarafından kullanımını kapsar, ancak reklam verenlerinin herhangi biri tarafından kullanılan çerezlerin veya diğer izleme teknolojilerinin kullanımını kapsamaz.</p>
</div>

<h5>Güvenlik</h5>
<div>
<p>Yetkisiz erişimi önlemek, veri kesinliğini korumak ve bilgilerin doğru şekilde kullanılmasını sağlamak için ticari açıdan makul güvenlik yöntemlerini kullanıyoruz.</p>
<p>Kayıtlı Kullanıcı olarak Kayıt Bilgilerinizi ve Yayınlanacak Bilgilerinizi Parola korumalı Hesabınız aracılığıyla görüntüleyebilir ve düzenleyebilirsiniz. Parolanızı hiç kimseyle paylaşmamanızı tavsiye ederiz. Personelimiz istenmeyen bir telefon çağrısı veya istenmeyen bir e-posta aracılığıyla Parolanızı asla sormayacaktır. Bir bilgisayarı başkalarıyla paylaşıyorsanız, oturum açma bilgilerinizi (örneğin Kullanıcı Kimliği ve Parolası) bilgisayara kaydetmeyi seçmemelisiniz. Oturumunuzu tamamladığınızda Hesabınızda oturumu ve tarayıcı pencerenizi kapatmayı unutmayın.</p>
<p>İnternet veya herhangi bir kablosuz ağ üzerinden yapılan hiçbir veri iletiminin mükemmel şekilde güvenli olması garanti edilemez. Sonuç olarak, bizler bilgilerinizi korumaya çalışırken bizimkiler de dahil hiçbir Web sitesi veya şirket bize ilettiğiniz herhangi bir bilginin güvenliğini mutlak şekilde sağlayamaz ve garanti edemez ve bunu riski size ait olacak şekilde yaparsınız.</p>
<p>Bağlantımız olan diğer Web sitelerinin gizlilik koruma yöntemlerinden sorumlu değiliz.</p>
<p><b>eMarketTurkey.com</b> başka Web sitelerine giden bağlantılar içerebilir. Kuşkusuz diğer Web sitelerinin gizlilik uygulamalarından sorumlu değiliz. Kullanıcılarımızı Sitemizden ayrılırken kişisel olarak saptanabilir bilgileri toplayan her bir sitenin gizlilik beyanlarını okumayı unutmamaya özendiriyoruz. Bu Gizlilik Politikası yalnızca <b>eMarketTurkey.com</b> tarafından toplanan bilgiler için geçerlidir.</p>
<p><b>eMarketTurkey.com</b> kullanıcıların bilgilerini korumak için uygun önlemler alır. Hesap bilgileriniz ateş duvarı ardından güvenli bir sunucuda bulunur. Parolanız gibi hassas bilgileri girdiğinizde bu bilgileri güvenli soket katmanı (SSL) teknolojisini kullanarak şifreliyoruz. E-posta ve anlık ileti gönderme güvenli iletişim olarak kabul edilmez, özel bilgilerinizi bize e-posta veya anlık ileti hizmetleriyle göndermemenizi istiyoruz. <b>eMarketTurkey.com</b> Web sitesinin güvenliğiyle ilgili herhangi bir sorunuz olursa, lütfen gizlilik yardım sayfamızda bulunan form aracılığıyla bizimle bağlantı kurun.</p>
<h5>18 Yaşın Altındakiler (Reşit olmayanlar)</h5>
<p><b>eMarketTurkey.com</b> 18 yaşın altında hiç kimsenin kişisel bilgilerini bilerek toplamaz veya istemez veya söz konusu kişilerin kaydolmasına bilerek izin vermez. 18 yaşın altındaysanız, lütfen <b>eMarketTurkey.com</b> sitesine kaydolmaya veya adınız, adresiniz, telefon numaranız veya e-posta adresiniz gibi kendinizle ilgili hiçbir bilgiyi bize göndermeye kalkışmayın. 18 yaşın altında hiç kimse <b>eMarketTurkey.com</b> sitesine veya sitesinde hiçbir kişisel bilgiyi sağlayamaz. 18 yaşın altında bir çocuğun kişisel bilgilerini topladığımızı öğrenirsek, o bilgileri mümkün olduğunca çabuk sileceğiz. 18 yaşın altında bir çocuktan veya çocuk hakkında herhangi bir bilgiye sahip olduğumuzu düşünüyorsanız, lütfen gizlilik yardım sayfamızdaki form aracılığıyla bizimle bağlantı kurun.</p>
</div>

<h5>Tüm Bilgilerinize Erişme ve Düzeltme</h5>
<div>
<p><b>eMarketTurkey.com</b> sitesindeki Hesabınız aracılığıyla Kayıt Bilgilerinize, Yayınlanacak Bilgilerinize ve Ödeme Bilgilerinize (varsa) erişebilir, bunları görüntüleyip düzenleyebilirsiniz.</p>
<p><b>eMarketTurkey.com</b> sitesindeki en kişisel bilgilere erişim ve bunlar üzerindeki denetim profil düzenleme araçlarında kullanıma hazır durumdadır. <b>eMarketTurkey.com</b> kullanıcıları hesaplarında oturum açarak profil bilgilerinin herhangi birini diledikleri zaman değiştirebilir veya silebilirler. Bilgiler derhal güncellenecektir. <b>eMarketTurkey.com</b> hesaplarını etkisiz kılmak isteyen kişiler bunu Hesabım sayfasından yapabilirler. Kaldırılan bilgiler makul bir süre boyunca yedek kopyalarda kalabilir ancak genellikle <b>eMarketTurkey.com</b> üyelerinin kullanımında değildir. Ancak <b>eMarketTurkey.com</b> sitesinde diğer kişilerle bilgi paylaşma hizmetinin iletişim özelliklerini kullandığınız hallerde genellikle bu iletişimleri kaldıramazsınız.</p>
<p>Kişisel olarak saptanabilen bilgilerinizin <b>eMarketTurkey.com</b>'un veritabanından kaldırılmasını veya söz konusu bilgilerdeki bir hatanın düzeltilmesini istiyorsanız, lütfen <?php echo image_tag('layout/gizlilik.post.gif') ?> yoluyla bizimle bağlantı kurun; talebinize uygun hareket etmek için her türlü makul çabayı göstereceğiz. Ancak <b>eMarketTurkey.com</b> veritabanlarında, erişim günlüklerinde ve diğer kayıtlarda söz konusu kişisel olarak saptanabilen bilgiler içerebilecek veya içermeyebilecek artık bilgilerin bulunabileceğini unutmayın. Artık bilgiler ticari amaçlar için kullanılmaz ancak <b>eMarketTurkey.com</b> <b>eMarketTurkey.com</b>'un eski müşterileri veya aboneleriyle zaman zaman yeniden bağlantı kurma hakkını saklı tutar.</p>
</div>

<h5>Anketler ve Çekilişler</h5>
<div>
<p><b>eMarketTurkey.com</b> reklamları ve içeriği daha iyi sunmak ve Hizmetlere ilişkin ihtiyaçlarınızı daha iyi anlamak amacıyla arada sırada anket araştırmaları yapabilir. Anket bilgilerinizi toplu şekil hariç hiçbir üçüncü şahısla paylaşmayacağız. Ayrıca, çekilişleri veya diğer tanıtımlara sponsorluk yaparsak veya yaptığımızda veya söz konusu tanıtımlara üçüncü taraflar bizimle birlikte sponsorluk yaparsa veya yaptığında, biz veya üçüncü taraf ilgili gizlilik bilgilerini çekilişlerin veya tanıtımların resmi kurallarına ve/veya kayıt alanına koyacağız. Bu Politikayla çeliştiği ölçüde bu gizlilik bilgileri söz konusu tanıtımı veya çekilişi yöneteceğinden lütfen bunları dikkatli okumayı unutmayın.</p>
<h5>Gizlilik Politikasındaki Değişiklikler</h5>
<p>Bu Gizlilik Politikasındaki tüm değişiklikler değiştirilmiş ve yeniden beyan edilmiş Gizlilik Politikamızı Sitemize koymamız aracılığıyla bildirilecektir. Değiştirilmiş ve yeniden beyan edilmiş Gizlilik Politikamızı koymamız söz konusu Gizlilik Politikasının anında yürürlüğe girmesini sağlayacaktır. Toplanan Bilgilerin tümünün bu anlamda en yeni Gizlilik Politikasının yönetiminde olacağını kabul ediyorsunuz. Gizlilik Politikamızdaki yeni değişiklikleri kabul etmiyorsanız, <b>eMarketTurkey.com</b> ile yazılı olarak bağlantı kurmanız ve <b>eMarketTurkey.com</b>'un Toplanan Bilgilerinizin tamamının veya bir kısmının <b>eMarketTurkey.com</b>'un elinde olan tüm kopyalarını iade ve/veya yok etmesini özellikle istemelisiniz.</p>
<p><b>eMarketTurkey.com</b> sitesini kullanımınız ve bundan doğan her türlü anlaşmazlık bu Gizlilik Politikasına olduğu kadar Kullanım Şartlarımıza ve tahkim, zararlarda sınırlamalar ve hukuk seçimi dahil anlaşmazlıkların çözümü hükümlerinin tümüne tabidir. Gizlilik Politikamızı ve Kullanım Şartlarımızı dilediğimiz zaman değiştirme hakkımızı saklı tutarız. Maddi olmayan değişiklikler ve açıklamalar derhal, maddi değişiklikler ise bu Sitede yer almalarından itibaren 30 gün içinde yürürlüğe girecektir. Değişiklik yaptığımızda bunları yayınlayacağız ve bu sayfanın en üstünde politikanın yeni yürürlük tarihini belirteceğiz. Bu politikada maddi değişiklikler yaparsak, e-posta yoluyla veya ana sayfamızda bildirimde bulunarak size buradan bilgi vereceğiz. Geçerli gizlilik politikamızı anlamak için sizi bu politikaya sürekli başvurmaya teşvik ediyoruz. Aksi belirtilmedikçe geçerli gizlilik politikamız siz ve hesabınız hakkındaki tüm bilgiler için geçerlidir.</p>
</div>

<h5>Gizliliğinizin Korunması</h5>
<div>
<p>Özgeçmişinizde Sosyal Güvenlik veya Banka Hesap numaralarınızı kullanmaktan kaçının.</p>
<p>Telefonda veya çevrimiçi olarak işle ilgili olmayan kişisel bilgilerin hiçbirini vermeyin.</p>
<p>Kredi kartı veya banka hesap numaralarınızı veya ilgili bilgileri biz talep etmeden önce kesinlikle vermeyin.</p>
<p><b>eMarketTurkey.com</b> kullanıcı adınızı veya parolanızı asla başkasına vermeyin.</p>
</div>

<h5>Geribildiriminiz</h5>
<div>
<p><b>eMarketTurkey.com</b> Gizlilik Politikamıza ve size sunulan hizmetlerimize ilişkin sürekli katkınızı memnuniyetle karşılar. Yorumlarınızı ve tepkilerinizi bize <?php echo image_tag('layout/gizlilik.post.gif') ?> yoluyla e-posta ile gönderebiliriniz.</p>
</div>

<h5>Fiziksel Posta Adresi</h5>
<div>
<p><b>EMTPORT Bilgi Teknolojileri A.Ş.</b><br />
Mansuroğlu Mah. Cumhuriyet Cad. No:15/1 Bayraklı 35040 İzmir TÜRKİYE
</p>
</div>
</div>
<style>
.privacy-policy ul { list-style-type: disc; }
.privacy-policy a { font: inherit;}
</style>