<div class="privacy-policy">
<div>
<em>(Updated on July 22, 2011)</em>
<div class="hrsplit-2"></div>
<p>This is the Privacy Policy governing your use of the <b>eMarketTurkey.com Site</b> ("<b>Site</b>") and the collection, use, transfer and processing of your collected information by <b>eMarketTurkey.com</b> and those affiliates which provide the relevant Premium Services (collectively referred to as "<b>eMarketTurkey.com</b>","we" or "us"). By using this <b>Site</b>, you consent to our Privacy Policy set out below.</p>
<p><b>eMarketTurkey.com</b> makes a firm commitment to protect your privacy. The following policy, as part of Terms & Conditions which has to be agreed with by users while visiting our web<b>Site</b>, provides details of how your information is treated. This policy may be subject to change in the future. However, we will notify you and request your confirmation, in such case.</p>
<p>We built <b>eMarketTurkey.com</b> to make it easy to share information with your friends, people, companies and organizations around the World. We understand you may not want everyone in the world to have the information you share on <b>eMarketTurkey.com</b>; that is why we give you control of your information. Our default privacy settings limit the information displayed in your profile to your networks and other reasonable community limitations that we tell you about.</p>
<p>You should have control over your personal and the other informations. <b>eMarketTurkey.com</b> helps you share information with your friends, people, companies, organizations around you. You choose what information you put in your profile, including contact, personal and company(ies) informations; pictures, resumes and groups you join. And you control the users with whom you share that information through the privacy settings on the <?php echo link_to(__('Privacy Settings'), '@myemt.setup-privacy') ?> page.</p>
<p>You should have access to the information others want to share. There is an increasing amount of information available out there, and you may want to know what relates to you, your friends, people and companies around you. We want to help you easily get that information.</p>
<p>We want to provide you with the privacy tools necessary to control how and with whom you share that information. If you have questions or ideas, please check out our <a href="http://emarketturkey.com/en/help/privacy">Privacy Help</a> page.</p>
<p>We at <b>eMarketTurkey.com</b> are committed to good privacy practices regarding your personal information. Your loyalty as a job seeker, customer, reseller, supplier, manufacturer or visitor is important and we hope that our concerns regarding your privacy, as described in this policy, demonstrate our commitment to making your experience with <b>eMarketTurkey.com</b> an enjoyable and satisfying one.</p>
<p>Although <b>eMarketTurkey.com</b> respects the privacy of all those who visit our web sites and use our online services, we do collect information from our visitors, including job seekers, customers, manufacturers, suppliers, reseller etc. This Privacy Policy governs your interaction with <b>eMarketTurkey.com</b> web site and your registration for and use of <b>eMarketTurkey.com</b>'s online services. Except as set forth within this Privacy Policy and our <?php echo link_to(__('Terms of Use'), '@terms') ?>, we do not release personally identifiable information about our members and visitors without their permission.</p>
<p>Note that, by using the Services, you signify your agreement to this Privacy Policy. If you do not agree to this Policy, please do not use the Services. Your continued use of the Services subsequent to changes to this Policy will mean that you accept the changes; therefore, please bookmark this page and review it periodically.</p>
</div>

<h5>The Information We Gather</h5>
<div>
<p><b>Registration Information:</b> At the time you register to become a Registered User of the <b>Site</b>, you will be asked to complete a registration form which requires you provide information such as your name, address, phone/fax number, email address and other personal information as well as information about your business ("Registration Information.")</p>
<p><b>Publishing Information:</b> If you submit any information to "<b>eMarketTurkey.com</b>" to be published on the <b>Site</b> through the publishing tools, including but not limited to Company Profile, Product Catalog, Trade Leads and any discussion forum, then you are deemed to have given consent to the publication of such information ("Publishing Information").</p>
<p><b>Statistical Information:</b> In addition, we gather aggregate statistical information about our <b>Site</b> and Users, such as IP addresses, browser software, operating system, pages viewed, number of sessions, unique visitors and so forth. ("Statistical Information").</p>
<p><b>Registration Information:</b> Publishing Information, Payment Information, Statistical Information and any information we may collect from you through the use of cookies or any other means, shall collectively be referred to as "Collected Information".</p>
<p><b>Account Data:</b> We collect all the information in your account on <b>eMarketTurkey.com</b>, such as your company name, address, contact person, telephone number, fax number, email and etc. This is to enforce the agreement between you and <b>eMarketTurkey.com</b>, to ensure that you are reachable by potential trade partners, job seeker or to troubleshoot problems with your account.</p>
<p><b>Hidden Data:</b> In addition to your account data, we also collect information recorded when you browse and visit our web site, including but not limited to, cookies, IP address, etc. This information is not used to identify you, but for the necessary purpose to avoid being attacked by hackers, and for the purpose of making customized content service to users. Additionally, through processing comprehensive statistic analysis, we are endeavoring to provide you with more and more efficient functionalities to facilitate our service. To visit <b>eMarketTurkey.com</b>, your browser has to be configured to accept cookies.</p>
<p><b>Personally Identifiable Information:</b>  In certain areas of the Services - such as those in which you complete a profile, submit your résumé, create a new account- sponsored contests or promotions - we may request that you provide us with certain personally identifiable information, such as your e-mail address, name, zip code, profession, or work experience. We will, in such situations, seek to identify which informational items are required and which are optional.</p>
<p>Job seekers should post profiles and resumes on <b>eMarketTurkey.com</b> only if they wish such information to be viewed by <b>eMarketTurkey.com</b>'s customers. At any time, job seekers may elect that their profile and resume not be searchable by <b>eMarketTurkey.com</b>'s customers by logging into their account and changing the status of their profile or, if that is not possible, they may contact <b>eMarketTurkey.com</b> at <?php echo image_tag('layout/privacy.post.gif') ?> and we will make the change for them.</p>
<p>In addition, job seekers may elect to make their profile searchable by <b>eMarketTurkey.com</b> customers on a confidential basis only. In this case, the user's name and contact information will not be displayed to customers performing searches on <b>eMarketTurkey.com</b>. If the customer desires to contact the confidential job seeker regarding an employment opportunity, they will send an email to the job seeker through the <b>eMarketTurkey.com</b> system. <b>eMarketTurkey.com</b> will forward the email to the seeker's email address. The seeker's email address will not be provided directly to the customer. When posting a resume confidentially, it is the job seeker's responsibility to ensure that their contact information is not included within their resume attachment.</p>
<p>Please note that <b>eMarketTurkey.com</b> cannot control the acts of users of the Services. All members and visitors should be aware that, when they disclose personally identifiable information in a resume or profile or other medium, the information may be collected and used by others to send that person unsolicited email from other parties outside <b>eMarketTurkey.com</b>. In the event that you encounter any <b>eMarketTurkey.com</b> user who is improperly collecting or using information about you or other users, please contact <?php echo image_tag('layout/privacy.post.gif') ?></p>  

<p>You post User Content (as defined in the "<b>eMarketTurkey.com</b>" Terms of Use) on the <b>Site</b> at your own risk. Although we allow you to set privacy options that limit access to your pages, please be aware that no security measures are perfect or impenetrable. We cannot control the actions of other Users with whom you may choose to share your pages and information. Therefore, we cannot and do not guarantee that User Content you post on the <b>Site</b> will not be viewed by unauthorized persons. We are not responsible for circumvention of any privacy settings or security measures contained on the <b>Site</b>. You understand and acknowledge that, even after removal, copies of User Content may remain viewable in cached and archived pages or if other Users have copied or stored your User Content.</p>
<p>Any improper collection or misuse of information provided on <b>eMarketTurkey.com</b> is a violation of the <b>eMarketTurkey.com</b> Terms of Service and should be reported through the form on our privacy help page.</p>
<p>If you choose to use our invitation service to tell a friend about our <b>Site</b>, we will ask you for information needed to send the invitation, such as your friend's email address. We will send your friend an email or instant message in your name inviting him or her to visit the <b>Site</b>. <b>eMarketTurkey.com</b> stores this information to send invitations, to register a friend connection if your invitation is accepted, to allow you to see invitations you have sent, and to track the success of our referral program. Your friend may contact us through the form on our <?php echo link_to(__('Contact Us'), '@contactus') ?> page to request that we remove this information from our database.</p>
<p><b>eMarketTurkey.com</b> may also collect information about you from other sources, such as newspapers, blogs, instant messaging services, and other users of the <b>eMarketTurkey.com</b> service through the operation of the service (e.g., photo tags) in order to provide you with more useful information and a more personalized experience. By using <b>eMarketTurkey.com</b>, you are consenting to have your personal data transferred to and processed in Turkey.</p>
</div>

<h5>How We May Use Information</h5>
<div>
<p>We use your Collected Information to improve our marketing and promotional efforts, to statistically analyze <b>Site</b> usage, to improve our content and product offerings and to customize our <b>Site</b>'s content, layout and service specifically for you. We may use your Collected Information to service your Account with us, including but not limited to investigating problems, resolving disputes and enforcing agreements with us. We may provide your Collected Information to our affiliates and service providers under contract (such as customer care) to support the operation of the <b>Site</b> and our services. We may share certain aggregate information based on analysis of Collected Information with our partners, customers, advertisers or potential Users. We may use your Collected Information to execute marketing campaigns, promotions or advertising messages on behalf of third parties; however, in these circumstances, your Collected Information will not be disclosed to such third parties unless you respond to the marketing, promotion or advertising message. Your Collected Information may be transferred, stored, used and processed outside your home jurisdiction. In case of a merger with or transfer of business to another business entity, we will transfer your Collected Information to the entity which acquires the business (Should such a combination occur, we will require that the new combined entity follow this Privacy Policy with respect to your Collected Information).</p>
<p><b>Registration Information:</b> We may use your Registration Information to provide services that you request or to contact you regarding additional services about which <b>eMarketTurkey.com</b> determines that you might be interested. Specifically, we may use your email address, mailing address, phone number or fax number to contact you regarding notices, surveys, product alerts, new service or product offerings and communications relevant to your use of our <b>Site</b>. We may generate reports and analysis based on the Registration Information for internal analysis, monitoring and marketing decisions.</p>
<p><b>Publishing Information:</b> All of your Publishing Information will be publicly available on the <b>Site</b> and therefore accessible by any internet user. Any Publishing Information that you disclose to <b>eMarketTurkey.com</b> becomes public information and you relinquish any proprietary rights (including but not limited to the rights of confidentiality and copyrights) in such information. You should exercise caution when deciding to include personal or proprietary information in the Publishing Information that you submit to us.</p>
<p><b>Statistical Information:</b> We use Statistical Information to help diagnose problems with and maintain our computer servers, to manage our <b>Site</b>, and to enhance our <b>Site</b> and services based on the usage pattern data we receive. We may generate reports and analysis based on the Statistical Information for internal analysis, monitoring and marketing decisions. We may provide Statistical Information to third parties, but when we do so, we do not provide personally-identifying information without your permission.</p>
<p>Information, such as company name, address, contact person, telephone number, etc., will be posted on <b>eMarketTurkey.com</b> publicly, and accessible to all users. Users should thus exercise caution when deciding to release any information that is identifiable to you. <b>eMarketTurkey.com</b> conducts analysis and research on the above information regarding users' distribution of industry, geographic location, and so on. The purpose of this research is to gain a better understanding of our users, and is compiled and analyzed on an aggregated basis. <b>eMarketTurkey.com</b> maintains the right to share analytic results with its business partners.</p>
<p>When you register with <b>eMarketTurkey.com</b>, you create your own profile and privacy settings. Your profile information, as well as your name, email and photo, are displayed to people in the networks specified in your privacy settings to enable you to connect with people on <b>eMarketTurkey.com</b>. We may occasionally use your name and email address to send you notifications regarding new services offered by "<b>eMarketTurkey.com</b>" that we think you may find valuable.</p>
<p>Profile information is used by <b>eMarketTurkey.com</b> primarily to be presented back to and edited by you when you access the service and to be presented to others permitted to view that information by your privacy settings. In some cases where your privacy settings permit it other <b>eMarketTurkey.com</b> users may be able to supplement your profile.</p>
<p>Profile information you submit to <b>eMarketTurkey.com</b> will be available to users of <b>eMarketTurkey.com</b> who belong to at least one of the networks you allow to access the information through your privacy settings Your name, network names, and profile picture thumbnail will be available in search results across the <b>eMarketTurkey.com</b> network and those limited pieces of information may be made available to third party search engines. This is primarily so your friends and companies can find you and send a request. People who see your name in searches, however, will not be able to access your profile information unless they have a relationship to you (friend, friend of friend, member of your networks, etc.) that allows such access based on your privacy settings.</p>
<p>We use non-personally identifiable information in aggregate form to build higher quality, more useful Services by performing statistical analyses of the collective characteristics and behavior of our visitors and members, and by measuring demographics and interests regarding specific areas of the Services. We may provide statistical information based on this data to advertisers and other current and potential business partners. We may also use the aggregate data to inform these third parties as to the number of people who have seen and clicked through links to their <b>Site</b>s.</p>
<p><b>eMarketTurkey.com</b> does not sell, re-sell or distribute for re-sale your personally identifiable information. <b>eMarketTurkey.com</b>'s customers may only use the information provided in resumes and profiles of job seekers to evaluate seekers' qualifications for the customer's open job opportunities. Job seekers should be aware, however, that <b>eMarketTurkey.com</b> has no way to control how a customer actually uses the service and how they use the resume and profile information. If you believe a <b>eMarketTurkey.com</b> customer is using personally identifiable information inappropriately , please notify <b>eMarketTurkey.com</b> at <?php echo image_tag('layout/privacy.post.gif') ?>.</p>
<p>Please note that <b>eMarketTurkey.com</b> reserves the right to disclose information submitted by or concerning any visitor or member as we reasonably feel is necessary to protect our systems or business. Specifically, but without limitation, we reserve the right to disclose such information when a visitor or member is in violation of our Terms of Use or other published guidelines or partakes (or is reasonably suspected of partaking) in any harmful, infringing or illegal activity, even without a subpoena, warrant, or other court order, and to disclose such information in response to court and governmental orders, civil subpoenas, discovery requests, and as otherwise required by law, as well as in response to allegations of infringement. We cooperate with law enforcement agencies in identifying those who may be using our servers or services for illegal activities. We also reserve the right to report any suspected illegal activity to law enforcement for investigation or prosecution, or to suspend or terminate your membership in connection with any suspected illegal or infringing activity. Finally, <b>eMarketTurkey.com</b> reserves the right to assign, sell, license, or otherwise transfer to a third party your personally identifiable information in connection with an assignment, sale, joint venture, or other transfer or disposition of any portion or all of <b>eMarketTurkey.com</b>'s or its affiliated entities' assets or stock.</p>
<p>Subject to the foregoing, <b>eMarketTurkey.com</b> uses your personally identifying information in several ways:</p>
<ul>
    <li>to cutomize various aspects of the Services to your preferences;</li>
    <li>to determine which advertisements or sponsor messages will appear on your screen;</li>
    <li>to send to you <b>eMarketTurkey.com</b> solicitations, product announcements, and the like that we feel may be of interest to you (you may "opt out" of receiving these materials, as provided below);</li>
    <li>to send to you certain e-mail messages that are critical to your use of the Services, such as system status updates or order confirmations (because these messages contain important information, you may not be able to "opt out" of receiving such messages). If you do not want to receive these type of email notifications, you would have to suspend your account through <?php echo link_to(__('Account Settings'), '@myemt.account') ?> page;</li>
    <li>to send you certain e-mail messages from third party advertisers (you may "opt-out" of receiving these materials, as provided below). Such third-party advertisements are distributed by <b>eMarketTurkey.com</b> on behalf of the advertiser. <b>eMarketTurkey.com</b> does not disclose your email address to its advertisers. However, you will be interacting directly with the advertiser and will be subject to their privacy policy once you "click-through" on an advertisement.</li>
    <li>to "pre-populate" forms that are displayed for the purpose of collecting individual data by <b>eMarketTurkey.com</b> and/or its sponsors (in no case will pre-populating a form automatically transfer any data to an advertiser or other third party - only if you voluntarily request that such data be transferred will any such transfer take place, e.g., by clicking the "Submit" button); and</li>
    <li>as may be necessary to support the operation of the Services, such as account maintenance, and record-keeping purposes.</li>
</ul>
<p>In addition to the circumstances described above, <b>eMarketTurkey.com</b> may disclose your personally-identifiable information to third parties as follows:</p>
<ul>
    <li>When a job seeker posts a profile or resume on <b>eMarketTurkey.com</b> on a non-confidential basis, such information will be shared with <b>eMarketTurkey.com</b>'s customers. (Note that at any time, job seekers may elect that their profile and resume not be searchable by <b>eMarketTurkey.com</b>'s customers by logging into their account and changing the status of their profile or they may contact <b>eMarketTurkey.com</b> at <?php echo image_tag('layout/privacy.post.gif') ?> and we will make the change for them.)</li>
    <li>When a job seeker elects to make his or her profile searchable by <b>eMarketTurkey.com</b> customers on a confidential basis only, the user's name and contact information will not be displayed to customers performing searches on <b>eMarketTurkey.com</b>. If the customer desires to contact the confidential job seeker regarding an employment opportunity, it will send an email to the job seeker through the <b>eMarketTurkey.com</b> system. <b>eMarketTurkey.com</b> will forward the email to the seeker's email address. The seeker's email address will not be provided directly to the customer. When posting a resume confidentially, it is the job seeker's responsibility to ensure that their contact information is not included within their resume attachment.</li>
    <li>All information made available to <b>eMarketTurkey.com</b> may be made available to our contractors and consultants, and professional advisors (such as attorneys or accountants), but only to the extent necessary for them to perform services on our behalf, and only under a duty of confidentiality.</li>
</ul>
</div>

<h5>Sharing Your Information with Third Parties</h5>
<div>
<p><b>eMarketTurkey.com</b> is about sharing information with others — friends, people and compaines in your networks — while providing you with privacy settings that restrict other users from accessing your information. We allow you to choose the information you provide to friends and networks through <b>eMarketTurkey.com</b>. Our network architecture and your privacy settings allow you to make informed choices about who has access to your information. We do not provide contact information to third party marketers without your permission. We share your information with third parties only in limited circumstances where we believe such sharing is</p>
<ul>
    <li>reasonably necessary to offer the service,</li>
    <li>legally required or,</li>
    <li>permitted by you.</li>
</ul>

<p>When you use <b>eMarketTurkey.com</b>, certain information you post or share with third parties (e.g., a friend, companies or someone in the world), such as personal information, resumes, comments, messages, photos, videos, products, services, marketplace listings or other information, may be shared with other users in accordance with the privacy settings you select. All such sharing of information is done at your own risk. Please keep in mind that if you disclose personal information in your profile or when posting comments, messages, photos, videos, Marketplace listings or other items , this information may become publicly available.</p>
</div>

<h5>Cookies, Advertisements and 3.party applications</h5>
<div>
<p>We use "cookies" to store specific information about you and track your visits to our <b>Site</b>. It is not uncommon for websites to use cookies to enhance identification of their users. A "cookie" is a small amount of data that is sent to your browser and stored on your computer's hard drive. A cookie can be sent to your computer's hard drive only if you access our <b>Site</b> using the computer. If you do not de-activate or erase the cookie, each time you use the same computer to access our <b>Site</b>, our web servers will be notified of your visit to our <b>Site</b> and in turn we may have knowledge of your visit and the pattern of your usage. Generally, we use cookies to identify you and enable us to access your Registration Information, Publishing Information or Payment Information so you do not have to re-enter it; gather statistical information about usage by Users; research visiting patters and help target advertisements based on User interests; assist our partners to track User visits to the <b>Site</b> and process orders; and track progress and participation in promotions.</p>
<p>You can determine if and how a cookie will be accepted by configuring your browser's which is installed in the computer you are using to access the <b>Site</b>. If you desire, you can change those configurations in your browser. By setting your preferences in the browser, you can accept all cookies, you can be notified when a cookie is sent, or you can reject all cookies. If you reject all cookies by choosing the cookie-disabling function in your browser, you may be required to re-enter your information on our <b>Site</b> more often and certain features of our <b>Site</b> may be unavailable.</p>
<p>Advertisements that appear on <b>eMarketTurkey.com</b> are sometimes delivered directly to users by third party advertisers. They automatically receive your IP address when this happens. These third party advertisers may also download cookies to your computer, or use other technologies such as JavaScript and web beacons to measure the effectiveness of their ads and to personalize advertising content. Doing this allows the advertising network to recognize your computer each time they send you an advertisement in order to measure the effectiveness of their ads and to personalize advertising content. In this way, they may compile information about where individuals using your computer or browser saw their advertisements and determine which advertisements are clicked. <b>eMarketTurkey.com</b> does not have access to or control of the cookies that may be placed by the third party advertisers. Third party advertisers have no access to your contact information stored on <b>eMarketTurkey.com</b> unless you choose to share it with them.</p>
<p>This privacy policy covers the use of cookies by <b>eMarketTurkey.com</b> and does not cover the use of cookies or other tracking technologies by any of its advertisers.</p>
</div>

<h5>Security</h5>
<div>
<p>We employ commercially reasonable security methods to prevent unauthorized access, maintain data accuracy and ensure correct use of information.</p>
<p>As a Registered User, your Registration Information and Publishing Information can be viewed and edited through your Account which is protected by Password. We recommend that you do not divulge your Password to anyone. Our personnel will never ask you for your Password in an unsolicited phone call or in an unsolicited e-mail. If you share a computer with others, you should not choose to save your log-in information (e.g., User ID and Password) on the computer. Remember to sign out of your Account and close your browser window when you have finished your session.</p>
<p>No data transmission over the Internet or any wireless network can be guaranteed to be perfectly secured. As a result, while we try to protect your information, no web site or company, including ourselves, can absolutely ensure or guarantee the security of any information you transmit to us and you do so at your own risk.</p>
<p>We are not responsible for the privacy protection methods of other web sites who are linked to .</p>
<p><b>eMarketTurkey.com</b> may contain links to other web sites. We are of course not responsible for the privacy practices of other web sites. We encourage our users to be aware when they leave our <b>Site</b> to read the privacy statements of each and every web site that collects personally identifiable information. This Privacy Policy applies solely to information collected by <b>eMarketTurkey.com</b>.</p>
<p><b>eMarketTurkey.com</b> takes appropriate precautions to protect our users' information. Your account information is located on a secured server behind a firewall. When you enter sensitive information such as your password), we encrypt that information using secure socket layer technology (SSL). Email and instant messaging are not recognized as secure communications, we request that you not send private information to us by email or instant messaging services. If you have any questions about the security of <b>eMarketTurkey.com</b> web site, please contact us through the form on our privacy help page.</p>
</div>

<h5>Under Age 18 (Minors)</h5>
<div>
<p><b>eMarketTurkey.com</b> does not knowingly collect or solicit personal information from anyone under the age of 18 or knowingly allow such persons to register. If you are under 18, please do not attempt to register for <b>eMarketTurkey.com</b> or send any information about yourself to us, including your name, address, telephone number, or email address. No one under age 18 may provide any personal information to or on <b>eMarketTurkey.com</b>. In the event that we learn that we have collected personal information from a child under age 18, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 18, please contact us through the form on our privacy help page.</p>
</div>

<h5>Accessing and Correcting Your All Information</h5>
<div>
<p>You can access, view and edit your Registration Information, Publishing Information and Payment Information (if any) through your Account with <b>eMarketTurkey.com</b>.</p>
<p>Access and control over most personal information on <b>eMarketTurkey.com</b> is readily available through the profile editing tools. <b>eMarketTurkey.com</b> users may modify or delete any of their profile information at any time by logging into their account. Information will be updated immediately. Individuals who wish to deactivate their <b>eMarketTurkey.com</b> account may do so on the My Account page. Removed information may persist in backup copies for a reasonable period of time but will not be generally available to members of <b>eMarketTurkey.com</b> Where you make use of the communication features of the service to share information with other individuals on <b>eMarketTurkey.com</b> however, you generally cannot remove such communications.</p>
<p>If you would like to have your personally identifiable information removed from <b>eMarketTurkey.com</b>'s database, or would like to correct an error in such information, please contact us at <?php echo image_tag('layout/privacy.post.gif') ?>, and we will use reasonable efforts to comply with your request. Keep in mind, however, that there will be residual information that will remain within <b>eMarketTurkey.com</b> databases, access logs, and other records, which may or may not contain such personally identifiable information. The residual information will not be used for commercial purposes; however <b>eMarketTurkey.com</b> reserves the right, from time to time, to re-contact former customers or users of <b>eMarketTurkey.com</b>.</p>
</div>

<h5>Surveys and Sweepstakes</h5>
<div>
<p>Occasionally, <b>eMarketTurkey.com</b> may conduct surveys in order to better deliver advertisements and content and to better understand your needs relating to the Services. We will not share your survey information with any third party, except in aggregate form. In addition, if and when we sponsor sweepstakes or other promotions, or third parties sponsor such promotions in conjunction with us, either we or the third party will post relevant privacy information in the official rules and/or registration area for the sweepstakes or promotion. That privacy information, to the extent it conflicts with this Policy, will govern that particular promotion or sweepstakes - please remember to read it carefully.</p>
</div>

<h5>Changes to Privacy Policy</h5>
<div>
<p>Any changes to this Privacy Policy will be communicated through our posting an amended and restated Privacy Policy on our <b>Site</b>. Our posting the amended and restated Privacy Policy will make such new Privacy Policy immediately effective. You agree that all Collected Information will be governed by the newest Privacy Policy then in effect. If you do not agree to the new changes in our Privacy Policy, you should contact <b>eMarketTurkey.com</b> in writing and specifically request that <b>eMarketTurkey.com</b> return and/or destroy all copies of all or part of your Collected Information in <b>eMarketTurkey.com</b>'s possession.</p>
<p>Your use of <b>eMarketTurkey.com</b> and any disputes arising from it, is subject to this Privacy Policy as well as our Terms of Use and all of its dispute resolution provisions including arbitration, limitation on damages and choice of law. We reserve the right to change our Privacy Policy and our Terms of Use at any time. Non-material changes and clarifications will take effect immediately, and material changes will take effect within 30 days of their posting on this <b>Site</b>. If we make changes, we will post them and will indicate at the top of this page the policy's new effective date. If we make material changes to this policy, we will notify you here, by email, or through notice on our home page. We encourage you to refer to this policy on an ongoing basis so that you understand our current privacy policy. Unless stated otherwise, our current privacy policy applies to all information that we have about you and your account.</p>
</div>

<h5>Protecting your privacy</h5>
<div>
<p>Avoid using a Social Security or Bank(s) Accout numbers on your resume.</p>
<p>Don't provide any non-work related personal information over the phone or online.</p>
<p>Never provide credit card or bank account numbers or related information before we demand.</p>
<p>Never give out your <b>eMarketTurkey.com</b> username or password to anyone.</p>
</div>

<h5>Your feedback</h5>
<div>
<p><b>eMarketTurkey.com</b> welcomes your continuous input regarding our Privacy Policy or our services provided to you. You may send us your comments and responses by email to <?php echo image_tag('layout/privacy.post.gif') ?>.</p>
</div>

<h5>Physical mailing address</h5>
<div>
<p>EMTPORT A.S.<br />
Mansuroglu Mah. Cumhuriyet Cad. No:15/1 Bayrakli 35040 Izmir TURKEY</p>
<div class="hrsplit-1"></div>
</div>
</div>
<style>.privacy-policy ul { list-style-type: disc; }</style>