default:
  http_metas:
    content-type: text/html

  metas:
    title:        'Business to Business | eMarketTurkey'
    description:  'eMarketTurkey B2B Directory'
    keywords:     'import, export, product, sell, buy, leads, trade, tools, trade events, companies, profiles, business groups'
    #language:     en
    robots:       index, follow
    base:         'http://b2b.emarketturkey.com'

  stylesheets:    [master-1.2.css, b2b-styles.css]

  javascripts:    [jquery-1.7.1.min.js, jquery-ui-1.8.13.core.min.js, jquery.tools-1.2.5.min.js, emt-dynabox-1.0.js, emt-toolbar-init.js]

  has_layout:     on
  layout:         layoutBoxModel
  