<?php
// auto-generated by sfViewConfigHandler
// date: 2012/03/08 00:06:05
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layoutBoxModel' ? false : 'layoutBoxModel'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Jobs | eMarketTurkey', false, false);
  $response->addMeta('description', 'eMarketTurkey Jobs Platform', false, false);
  $response->addMeta('keywords', 'jobs, cv, resumes, job search, bulletin job application, human resources, hr', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('base', 'http://hr.emarketturkey.com', false, false);

  $response->addStylesheet('master-1.0.css', '', array ());
  $response->addStylesheet('hr-styles.css', '', array ());
  $response->addStylesheet('jquery-tools/dateinput.css', '', array ());
  $response->addJavascript('jquery-1.7.1.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.13.core.min.js', '', array ());
  $response->addJavascript('jquery.tools-1.2.5.min.js', '', array ());
  $response->addJavascript('emt-dynabox-1.0.js', '', array ());
  $response->addJavascript('emt-toolbar-init.js', '', array ());
  $response->addJavascript('jquery.customCheckbox.js', '', array ());


