all:
#    layout:  layoutRightColumn
    metas:
        title:  'MY EMT | eMarketTurkey'
    javascripts:   [jquery.cookie.min.js, /jquery-ui-1.8.4.custom/js/jquery-ui-1.8.4.custom.min.js]

setupProfileSuccess:
    metas:
        title:  'Setup Your Profile | eMarketTurkey'
    layout:  'layoutBoxModel-island'
    stylesheets:  [jquery.Jcrop.css]
    javascripts:  [jquery.Jcrop.min.js, jquery.ui-1.8.14.dragdrop.js, emt-logoWidget.js]

uploadProfileSuccess:
    has_layout: off

indexSuccess:        
    javascripts:   [jquery.json-2.3.min.js]

error404Success:
  metas:
    title:        'Page Not Found'
  layout: layoutTitleOnly
  stylesheets:    [-*, error.css]
  javascripts:    [-*]