all:
  metas:
    title:        'Academy | eMarketTurkey'
    description:  'eMarketTurkey Academy Portal'
    keywords:     'article, trade, information, research, survey, news, import, export, knowledgebase'
  stylesheets:    [ac-styles-0.1.css]

showSuccess:
    metas:
        title:  'Article Content'
    